
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Clinic: 'Clinic',
  User: 'User',
  Membership: 'Membership',
  Doctor: 'Doctor',
  Service: 'Service',
  AvailableSlot: 'AvailableSlot',
  ConversationSession: 'ConversationSession',
  ConversationMessage: 'ConversationMessage',
  StateTransitionLog: 'StateTransitionLog',
  Patient: 'Patient',
  Appointment: 'Appointment',
  Conversation: 'Conversation',
  Message: 'Message',
  Reminder: 'Reminder',
  NotificationJob: 'NotificationJob',
  Campaign: 'Campaign',
  ClinicSettings: 'ClinicSettings',
  BusinessHours: 'BusinessHours',
  Lead: 'Lead',
  EscalationLog: 'EscalationLog'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const ClinicScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  address: 'address',
  phone: 'phone',
  email: 'email',
  website: 'website',
  timezone: 'timezone',
  twilioPhoneNumber: 'twilioPhoneNumber',
  isActive: 'isActive',
  subscriptionPlan: 'subscriptionPlan',
  subscriptionExpiresAt: 'subscriptionExpiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ClinicScalarFieldEnum = (typeof ClinicScalarFieldEnum)[keyof typeof ClinicScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  passwordHash: 'passwordHash',
  firstName: 'firstName',
  lastName: 'lastName',
  phone: 'phone',
  isEmailVerified: 'isEmailVerified',
  lastLoginAt: 'lastLoginAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const MembershipScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  clinicId: 'clinicId',
  role: 'role',
  isActive: 'isActive',
  invitedBy: 'invitedBy',
  invitedAt: 'invitedAt',
  joinedAt: 'joinedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MembershipScalarFieldEnum = (typeof MembershipScalarFieldEnum)[keyof typeof MembershipScalarFieldEnum]


export const DoctorScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  userId: 'userId',
  firstName: 'firstName',
  lastName: 'lastName',
  email: 'email',
  phone: 'phone',
  specialty: 'specialty',
  licenseNumber: 'licenseNumber',
  availabilitySchedule: 'availabilitySchedule',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DoctorScalarFieldEnum = (typeof DoctorScalarFieldEnum)[keyof typeof DoctorScalarFieldEnum]


export const ServiceScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  name: 'name',
  description: 'description',
  durationMinutes: 'durationMinutes',
  price: 'price',
  category: 'category',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ServiceScalarFieldEnum = (typeof ServiceScalarFieldEnum)[keyof typeof ServiceScalarFieldEnum]


export const AvailableSlotScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  serviceId: 'serviceId',
  startTime: 'startTime',
  endTime: 'endTime',
  isHeld: 'isHeld',
  heldBySessionId: 'heldBySessionId',
  heldAt: 'heldAt',
  isBooked: 'isBooked',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AvailableSlotScalarFieldEnum = (typeof AvailableSlotScalarFieldEnum)[keyof typeof AvailableSlotScalarFieldEnum]


export const ConversationSessionScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  phoneNumber: 'phoneNumber',
  currentState: 'currentState',
  previousState: 'previousState',
  slotServiceId: 'slotServiceId',
  slotDate: 'slotDate',
  slotTimeId: 'slotTimeId',
  slotPatientName: 'slotPatientName',
  slotPatientDob: 'slotPatientDob',
  slotPhoneConfirmed: 'slotPhoneConfirmed',
  detectedLanguage: 'detectedLanguage',
  retryCount: 'retryCount',
  maxRetriesPerState: 'maxRetriesPerState',
  invalidInputCount: 'invalidInputCount',
  ambiguousIntents: 'ambiguousIntents',
  escalationReason: 'escalationReason',
  escalationClaimedBy: 'escalationClaimedBy',
  escalationClaimedAt: 'escalationClaimedAt',
  bookingId: 'bookingId',
  handoffActive: 'handoffActive',
  slotOfferedAt: 'slotOfferedAt',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  resolvedAt: 'resolvedAt'
} as const

export type ConversationSessionScalarFieldEnum = (typeof ConversationSessionScalarFieldEnum)[keyof typeof ConversationSessionScalarFieldEnum]


export const ConversationMessageScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  clinicId: 'clinicId',
  role: 'role',
  channel: 'channel',
  content: 'content',
  contentNormalized: 'contentNormalized',
  twilioMessageSid: 'twilioMessageSid',
  twilioStatus: 'twilioStatus',
  claudeModel: 'claudeModel',
  claudeInputTokens: 'claudeInputTokens',
  claudeOutputTokens: 'claudeOutputTokens',
  claudeToolsUsed: 'claudeToolsUsed',
  sessionStateAtSend: 'sessionStateAtSend',
  createdAt: 'createdAt'
} as const

export type ConversationMessageScalarFieldEnum = (typeof ConversationMessageScalarFieldEnum)[keyof typeof ConversationMessageScalarFieldEnum]


export const StateTransitionLogScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  clinicId: 'clinicId',
  fromState: 'fromState',
  toState: 'toState',
  triggerType: 'triggerType',
  triggerPayload: 'triggerPayload',
  triggeredBy: 'triggeredBy',
  createdAt: 'createdAt'
} as const

export type StateTransitionLogScalarFieldEnum = (typeof StateTransitionLogScalarFieldEnum)[keyof typeof StateTransitionLogScalarFieldEnum]


export const PatientScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  firstName: 'firstName',
  lastName: 'lastName',
  email: 'email',
  phone: 'phone',
  dateOfBirth: 'dateOfBirth',
  address: 'address',
  emergencyContactName: 'emergencyContactName',
  emergencyContactPhone: 'emergencyContactPhone',
  medicalHistory: 'medicalHistory',
  allergies: 'allergies',
  notes: 'notes',
  lastVisitAt: 'lastVisitAt',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PatientScalarFieldEnum = (typeof PatientScalarFieldEnum)[keyof typeof PatientScalarFieldEnum]


export const AppointmentScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  patientId: 'patientId',
  doctorId: 'doctorId',
  serviceId: 'serviceId',
  scheduledAt: 'scheduledAt',
  durationMinutes: 'durationMinutes',
  status: 'status',
  confirmationRequestedAt: 'confirmationRequestedAt',
  confirmedAt: 'confirmedAt',
  reminder24hSentAt: 'reminder24hSentAt',
  reminder3hSentAt: 'reminder3hSentAt',
  lastReminderType: 'lastReminderType',
  lastPatientMessageAt: 'lastPatientMessageAt',
  notes: 'notes',
  cancellationReason: 'cancellationReason',
  rescheduledFromId: 'rescheduledFromId',
  createdBy: 'createdBy',
  source: 'source',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AppointmentScalarFieldEnum = (typeof AppointmentScalarFieldEnum)[keyof typeof AppointmentScalarFieldEnum]


export const ConversationScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  patientId: 'patientId',
  channel: 'channel',
  externalId: 'externalId',
  isActive: 'isActive',
  lastMessageAt: 'lastMessageAt',
  assignedTo: 'assignedTo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ConversationScalarFieldEnum = (typeof ConversationScalarFieldEnum)[keyof typeof ConversationScalarFieldEnum]


export const MessageScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  senderType: 'senderType',
  senderId: 'senderId',
  content: 'content',
  messageType: 'messageType',
  externalId: 'externalId',
  status: 'status',
  sentAt: 'sentAt',
  deliveredAt: 'deliveredAt',
  readAt: 'readAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MessageScalarFieldEnum = (typeof MessageScalarFieldEnum)[keyof typeof MessageScalarFieldEnum]


export const ReminderScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  appointmentId: 'appointmentId',
  type: 'type',
  scheduledAt: 'scheduledAt',
  sentAt: 'sentAt',
  status: 'status',
  template: 'template',
  customMessage: 'customMessage',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ReminderScalarFieldEnum = (typeof ReminderScalarFieldEnum)[keyof typeof ReminderScalarFieldEnum]


export const NotificationJobScalarFieldEnum = {
  retryCount: 'retryCount',
  id: 'id',
  clinicId: 'clinicId',
  reminderId: 'reminderId',
  appointmentId: 'appointmentId',
  patientId: 'patientId',
  channel: 'channel',
  destination: 'destination',
  messageBody: 'messageBody',
  provider: 'provider',
  providerMessageId: 'providerMessageId',
  status: 'status',
  errorMessage: 'errorMessage',
  scheduledFor: 'scheduledFor',
  sentAt: 'sentAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type NotificationJobScalarFieldEnum = (typeof NotificationJobScalarFieldEnum)[keyof typeof NotificationJobScalarFieldEnum]


export const CampaignScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  name: 'name',
  description: 'description',
  type: 'type',
  targetAudience: 'targetAudience',
  channel: 'channel',
  template: 'template',
  scheduledAt: 'scheduledAt',
  status: 'status',
  sentCount: 'sentCount',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CampaignScalarFieldEnum = (typeof CampaignScalarFieldEnum)[keyof typeof CampaignScalarFieldEnum]


export const ClinicSettingsScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  appointmentBufferMinutes: 'appointmentBufferMinutes',
  maxAdvanceBookingDays: 'maxAdvanceBookingDays',
  timezone: 'timezone',
  currency: 'currency',
  workingHours: 'workingHours',
  reminderSettings: 'reminderSettings',
  notificationSettings: 'notificationSettings',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ClinicSettingsScalarFieldEnum = (typeof ClinicSettingsScalarFieldEnum)[keyof typeof ClinicSettingsScalarFieldEnum]


export const BusinessHoursScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  dayOfWeek: 'dayOfWeek',
  isOpen: 'isOpen',
  openTime: 'openTime',
  closeTime: 'closeTime',
  breakStart: 'breakStart',
  breakEnd: 'breakEnd',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BusinessHoursScalarFieldEnum = (typeof BusinessHoursScalarFieldEnum)[keyof typeof BusinessHoursScalarFieldEnum]


export const LeadScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  patientPhone: 'patientPhone',
  patientName: 'patientName',
  serviceInterest: 'serviceInterest',
  datePreference: 'datePreference',
  dropReason: 'dropReason',
  sessionId: 'sessionId',
  createdAt: 'createdAt'
} as const

export type LeadScalarFieldEnum = (typeof LeadScalarFieldEnum)[keyof typeof LeadScalarFieldEnum]


export const EscalationLogScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  entityType: 'entityType',
  entityId: 'entityId',
  eventType: 'eventType',
  severity: 'severity',
  message: 'message',
  metadata: 'metadata',
  userId: 'userId',
  createdAt: 'createdAt'
} as const

export type EscalationLogScalarFieldEnum = (typeof EscalationLogScalarFieldEnum)[keyof typeof EscalationLogScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

