
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.6.0
 * Query Engine version: 75cbdc1eb7150937890ad5465d861175c6624711
 */
export const prismaVersion: PrismaVersion = {
  client: "7.6.0",
  engine: "75cbdc1eb7150937890ad5465d861175c6624711"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  Clinic: 'Clinic',
  User: 'User',
  Membership: 'Membership',
  Doctor: 'Doctor',
  Service: 'Service',
  AvailableSlot: 'AvailableSlot',
  ConversationSession: 'ConversationSession',
  ConversationMessage: 'ConversationMessage',
  StateTransitionLog: 'StateTransitionLog',
  Patient: 'Patient',
  Appointment: 'Appointment',
  Conversation: 'Conversation',
  Message: 'Message',
  Reminder: 'Reminder',
  NotificationJob: 'NotificationJob',
  Campaign: 'Campaign',
  ClinicSettings: 'ClinicSettings',
  BusinessHours: 'BusinessHours',
  EscalationLog: 'EscalationLog'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "clinic" | "user" | "membership" | "doctor" | "service" | "availableSlot" | "conversationSession" | "conversationMessage" | "stateTransitionLog" | "patient" | "appointment" | "conversation" | "message" | "reminder" | "notificationJob" | "campaign" | "clinicSettings" | "businessHours" | "escalationLog"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    Clinic: {
      payload: Prisma.$ClinicPayload<ExtArgs>
      fields: Prisma.ClinicFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ClinicFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClinicPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ClinicFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClinicPayload>
        }
        findFirst: {
          args: Prisma.ClinicFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClinicPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ClinicFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClinicPayload>
        }
        findMany: {
          args: Prisma.ClinicFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClinicPayload>[]
        }
        create: {
          args: Prisma.ClinicCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClinicPayload>
        }
        createMany: {
          args: Prisma.ClinicCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ClinicCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClinicPayload>[]
        }
        delete: {
          args: Prisma.ClinicDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClinicPayload>
        }
        update: {
          args: Prisma.ClinicUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClinicPayload>
        }
        deleteMany: {
          args: Prisma.ClinicDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ClinicUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ClinicUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClinicPayload>[]
        }
        upsert: {
          args: Prisma.ClinicUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClinicPayload>
        }
        aggregate: {
          args: Prisma.ClinicAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateClinic>
        }
        groupBy: {
          args: Prisma.ClinicGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ClinicGroupByOutputType>[]
        }
        count: {
          args: Prisma.ClinicCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ClinicCountAggregateOutputType> | number
        }
      }
    }
    User: {
      payload: Prisma.$UserPayload<ExtArgs>
      fields: Prisma.UserFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findFirst: {
          args: Prisma.UserFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findMany: {
          args: Prisma.UserFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        create: {
          args: Prisma.UserCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        createMany: {
          args: Prisma.UserCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        delete: {
          args: Prisma.UserDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        update: {
          args: Prisma.UserUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        deleteMany: {
          args: Prisma.UserDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        upsert: {
          args: Prisma.UserUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        aggregate: {
          args: Prisma.UserAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUser>
        }
        groupBy: {
          args: Prisma.UserGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserCountAggregateOutputType> | number
        }
      }
    }
    Membership: {
      payload: Prisma.$MembershipPayload<ExtArgs>
      fields: Prisma.MembershipFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MembershipFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MembershipFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPayload>
        }
        findFirst: {
          args: Prisma.MembershipFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MembershipFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPayload>
        }
        findMany: {
          args: Prisma.MembershipFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPayload>[]
        }
        create: {
          args: Prisma.MembershipCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPayload>
        }
        createMany: {
          args: Prisma.MembershipCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.MembershipCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPayload>[]
        }
        delete: {
          args: Prisma.MembershipDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPayload>
        }
        update: {
          args: Prisma.MembershipUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPayload>
        }
        deleteMany: {
          args: Prisma.MembershipDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MembershipUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.MembershipUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPayload>[]
        }
        upsert: {
          args: Prisma.MembershipUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPayload>
        }
        aggregate: {
          args: Prisma.MembershipAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMembership>
        }
        groupBy: {
          args: Prisma.MembershipGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MembershipGroupByOutputType>[]
        }
        count: {
          args: Prisma.MembershipCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MembershipCountAggregateOutputType> | number
        }
      }
    }
    Doctor: {
      payload: Prisma.$DoctorPayload<ExtArgs>
      fields: Prisma.DoctorFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DoctorFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DoctorPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DoctorFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DoctorPayload>
        }
        findFirst: {
          args: Prisma.DoctorFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DoctorPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DoctorFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DoctorPayload>
        }
        findMany: {
          args: Prisma.DoctorFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DoctorPayload>[]
        }
        create: {
          args: Prisma.DoctorCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DoctorPayload>
        }
        createMany: {
          args: Prisma.DoctorCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DoctorCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DoctorPayload>[]
        }
        delete: {
          args: Prisma.DoctorDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DoctorPayload>
        }
        update: {
          args: Prisma.DoctorUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DoctorPayload>
        }
        deleteMany: {
          args: Prisma.DoctorDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DoctorUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DoctorUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DoctorPayload>[]
        }
        upsert: {
          args: Prisma.DoctorUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DoctorPayload>
        }
        aggregate: {
          args: Prisma.DoctorAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDoctor>
        }
        groupBy: {
          args: Prisma.DoctorGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DoctorGroupByOutputType>[]
        }
        count: {
          args: Prisma.DoctorCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DoctorCountAggregateOutputType> | number
        }
      }
    }
    Service: {
      payload: Prisma.$ServicePayload<ExtArgs>
      fields: Prisma.ServiceFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ServiceFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ServiceFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicePayload>
        }
        findFirst: {
          args: Prisma.ServiceFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ServiceFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicePayload>
        }
        findMany: {
          args: Prisma.ServiceFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicePayload>[]
        }
        create: {
          args: Prisma.ServiceCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicePayload>
        }
        createMany: {
          args: Prisma.ServiceCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ServiceCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicePayload>[]
        }
        delete: {
          args: Prisma.ServiceDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicePayload>
        }
        update: {
          args: Prisma.ServiceUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicePayload>
        }
        deleteMany: {
          args: Prisma.ServiceDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ServiceUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ServiceUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicePayload>[]
        }
        upsert: {
          args: Prisma.ServiceUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicePayload>
        }
        aggregate: {
          args: Prisma.ServiceAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateService>
        }
        groupBy: {
          args: Prisma.ServiceGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ServiceGroupByOutputType>[]
        }
        count: {
          args: Prisma.ServiceCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ServiceCountAggregateOutputType> | number
        }
      }
    }
    AvailableSlot: {
      payload: Prisma.$AvailableSlotPayload<ExtArgs>
      fields: Prisma.AvailableSlotFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AvailableSlotFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvailableSlotPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AvailableSlotFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvailableSlotPayload>
        }
        findFirst: {
          args: Prisma.AvailableSlotFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvailableSlotPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AvailableSlotFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvailableSlotPayload>
        }
        findMany: {
          args: Prisma.AvailableSlotFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvailableSlotPayload>[]
        }
        create: {
          args: Prisma.AvailableSlotCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvailableSlotPayload>
        }
        createMany: {
          args: Prisma.AvailableSlotCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AvailableSlotCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvailableSlotPayload>[]
        }
        delete: {
          args: Prisma.AvailableSlotDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvailableSlotPayload>
        }
        update: {
          args: Prisma.AvailableSlotUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvailableSlotPayload>
        }
        deleteMany: {
          args: Prisma.AvailableSlotDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AvailableSlotUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AvailableSlotUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvailableSlotPayload>[]
        }
        upsert: {
          args: Prisma.AvailableSlotUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvailableSlotPayload>
        }
        aggregate: {
          args: Prisma.AvailableSlotAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAvailableSlot>
        }
        groupBy: {
          args: Prisma.AvailableSlotGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AvailableSlotGroupByOutputType>[]
        }
        count: {
          args: Prisma.AvailableSlotCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AvailableSlotCountAggregateOutputType> | number
        }
      }
    }
    ConversationSession: {
      payload: Prisma.$ConversationSessionPayload<ExtArgs>
      fields: Prisma.ConversationSessionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ConversationSessionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationSessionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ConversationSessionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationSessionPayload>
        }
        findFirst: {
          args: Prisma.ConversationSessionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationSessionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ConversationSessionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationSessionPayload>
        }
        findMany: {
          args: Prisma.ConversationSessionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationSessionPayload>[]
        }
        create: {
          args: Prisma.ConversationSessionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationSessionPayload>
        }
        createMany: {
          args: Prisma.ConversationSessionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ConversationSessionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationSessionPayload>[]
        }
        delete: {
          args: Prisma.ConversationSessionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationSessionPayload>
        }
        update: {
          args: Prisma.ConversationSessionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationSessionPayload>
        }
        deleteMany: {
          args: Prisma.ConversationSessionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ConversationSessionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ConversationSessionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationSessionPayload>[]
        }
        upsert: {
          args: Prisma.ConversationSessionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationSessionPayload>
        }
        aggregate: {
          args: Prisma.ConversationSessionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateConversationSession>
        }
        groupBy: {
          args: Prisma.ConversationSessionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ConversationSessionGroupByOutputType>[]
        }
        count: {
          args: Prisma.ConversationSessionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ConversationSessionCountAggregateOutputType> | number
        }
      }
    }
    ConversationMessage: {
      payload: Prisma.$ConversationMessagePayload<ExtArgs>
      fields: Prisma.ConversationMessageFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ConversationMessageFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationMessagePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ConversationMessageFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationMessagePayload>
        }
        findFirst: {
          args: Prisma.ConversationMessageFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationMessagePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ConversationMessageFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationMessagePayload>
        }
        findMany: {
          args: Prisma.ConversationMessageFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationMessagePayload>[]
        }
        create: {
          args: Prisma.ConversationMessageCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationMessagePayload>
        }
        createMany: {
          args: Prisma.ConversationMessageCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ConversationMessageCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationMessagePayload>[]
        }
        delete: {
          args: Prisma.ConversationMessageDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationMessagePayload>
        }
        update: {
          args: Prisma.ConversationMessageUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationMessagePayload>
        }
        deleteMany: {
          args: Prisma.ConversationMessageDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ConversationMessageUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ConversationMessageUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationMessagePayload>[]
        }
        upsert: {
          args: Prisma.ConversationMessageUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationMessagePayload>
        }
        aggregate: {
          args: Prisma.ConversationMessageAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateConversationMessage>
        }
        groupBy: {
          args: Prisma.ConversationMessageGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ConversationMessageGroupByOutputType>[]
        }
        count: {
          args: Prisma.ConversationMessageCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ConversationMessageCountAggregateOutputType> | number
        }
      }
    }
    StateTransitionLog: {
      payload: Prisma.$StateTransitionLogPayload<ExtArgs>
      fields: Prisma.StateTransitionLogFieldRefs
      operations: {
        findUnique: {
          args: Prisma.StateTransitionLogFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StateTransitionLogPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.StateTransitionLogFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StateTransitionLogPayload>
        }
        findFirst: {
          args: Prisma.StateTransitionLogFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StateTransitionLogPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.StateTransitionLogFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StateTransitionLogPayload>
        }
        findMany: {
          args: Prisma.StateTransitionLogFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StateTransitionLogPayload>[]
        }
        create: {
          args: Prisma.StateTransitionLogCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StateTransitionLogPayload>
        }
        createMany: {
          args: Prisma.StateTransitionLogCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.StateTransitionLogCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StateTransitionLogPayload>[]
        }
        delete: {
          args: Prisma.StateTransitionLogDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StateTransitionLogPayload>
        }
        update: {
          args: Prisma.StateTransitionLogUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StateTransitionLogPayload>
        }
        deleteMany: {
          args: Prisma.StateTransitionLogDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.StateTransitionLogUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.StateTransitionLogUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StateTransitionLogPayload>[]
        }
        upsert: {
          args: Prisma.StateTransitionLogUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StateTransitionLogPayload>
        }
        aggregate: {
          args: Prisma.StateTransitionLogAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateStateTransitionLog>
        }
        groupBy: {
          args: Prisma.StateTransitionLogGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StateTransitionLogGroupByOutputType>[]
        }
        count: {
          args: Prisma.StateTransitionLogCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StateTransitionLogCountAggregateOutputType> | number
        }
      }
    }
    Patient: {
      payload: Prisma.$PatientPayload<ExtArgs>
      fields: Prisma.PatientFieldRefs
      operations: {
        findUnique: {
          args: Prisma.PatientFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PatientPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.PatientFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PatientPayload>
        }
        findFirst: {
          args: Prisma.PatientFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PatientPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.PatientFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PatientPayload>
        }
        findMany: {
          args: Prisma.PatientFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PatientPayload>[]
        }
        create: {
          args: Prisma.PatientCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PatientPayload>
        }
        createMany: {
          args: Prisma.PatientCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.PatientCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PatientPayload>[]
        }
        delete: {
          args: Prisma.PatientDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PatientPayload>
        }
        update: {
          args: Prisma.PatientUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PatientPayload>
        }
        deleteMany: {
          args: Prisma.PatientDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.PatientUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.PatientUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PatientPayload>[]
        }
        upsert: {
          args: Prisma.PatientUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PatientPayload>
        }
        aggregate: {
          args: Prisma.PatientAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregatePatient>
        }
        groupBy: {
          args: Prisma.PatientGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PatientGroupByOutputType>[]
        }
        count: {
          args: Prisma.PatientCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PatientCountAggregateOutputType> | number
        }
      }
    }
    Appointment: {
      payload: Prisma.$AppointmentPayload<ExtArgs>
      fields: Prisma.AppointmentFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AppointmentFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AppointmentPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AppointmentFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AppointmentPayload>
        }
        findFirst: {
          args: Prisma.AppointmentFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AppointmentPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AppointmentFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AppointmentPayload>
        }
        findMany: {
          args: Prisma.AppointmentFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AppointmentPayload>[]
        }
        create: {
          args: Prisma.AppointmentCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AppointmentPayload>
        }
        createMany: {
          args: Prisma.AppointmentCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AppointmentCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AppointmentPayload>[]
        }
        delete: {
          args: Prisma.AppointmentDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AppointmentPayload>
        }
        update: {
          args: Prisma.AppointmentUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AppointmentPayload>
        }
        deleteMany: {
          args: Prisma.AppointmentDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AppointmentUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AppointmentUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AppointmentPayload>[]
        }
        upsert: {
          args: Prisma.AppointmentUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AppointmentPayload>
        }
        aggregate: {
          args: Prisma.AppointmentAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAppointment>
        }
        groupBy: {
          args: Prisma.AppointmentGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AppointmentGroupByOutputType>[]
        }
        count: {
          args: Prisma.AppointmentCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AppointmentCountAggregateOutputType> | number
        }
      }
    }
    Conversation: {
      payload: Prisma.$ConversationPayload<ExtArgs>
      fields: Prisma.ConversationFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ConversationFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ConversationFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationPayload>
        }
        findFirst: {
          args: Prisma.ConversationFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ConversationFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationPayload>
        }
        findMany: {
          args: Prisma.ConversationFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationPayload>[]
        }
        create: {
          args: Prisma.ConversationCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationPayload>
        }
        createMany: {
          args: Prisma.ConversationCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ConversationCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationPayload>[]
        }
        delete: {
          args: Prisma.ConversationDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationPayload>
        }
        update: {
          args: Prisma.ConversationUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationPayload>
        }
        deleteMany: {
          args: Prisma.ConversationDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ConversationUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ConversationUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationPayload>[]
        }
        upsert: {
          args: Prisma.ConversationUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationPayload>
        }
        aggregate: {
          args: Prisma.ConversationAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateConversation>
        }
        groupBy: {
          args: Prisma.ConversationGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ConversationGroupByOutputType>[]
        }
        count: {
          args: Prisma.ConversationCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ConversationCountAggregateOutputType> | number
        }
      }
    }
    Message: {
      payload: Prisma.$MessagePayload<ExtArgs>
      fields: Prisma.MessageFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MessageFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessagePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MessageFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessagePayload>
        }
        findFirst: {
          args: Prisma.MessageFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessagePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MessageFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessagePayload>
        }
        findMany: {
          args: Prisma.MessageFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessagePayload>[]
        }
        create: {
          args: Prisma.MessageCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessagePayload>
        }
        createMany: {
          args: Prisma.MessageCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.MessageCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessagePayload>[]
        }
        delete: {
          args: Prisma.MessageDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessagePayload>
        }
        update: {
          args: Prisma.MessageUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessagePayload>
        }
        deleteMany: {
          args: Prisma.MessageDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MessageUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.MessageUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessagePayload>[]
        }
        upsert: {
          args: Prisma.MessageUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessagePayload>
        }
        aggregate: {
          args: Prisma.MessageAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMessage>
        }
        groupBy: {
          args: Prisma.MessageGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MessageGroupByOutputType>[]
        }
        count: {
          args: Prisma.MessageCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MessageCountAggregateOutputType> | number
        }
      }
    }
    Reminder: {
      payload: Prisma.$ReminderPayload<ExtArgs>
      fields: Prisma.ReminderFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ReminderFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReminderPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ReminderFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReminderPayload>
        }
        findFirst: {
          args: Prisma.ReminderFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReminderPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ReminderFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReminderPayload>
        }
        findMany: {
          args: Prisma.ReminderFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReminderPayload>[]
        }
        create: {
          args: Prisma.ReminderCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReminderPayload>
        }
        createMany: {
          args: Prisma.ReminderCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ReminderCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReminderPayload>[]
        }
        delete: {
          args: Prisma.ReminderDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReminderPayload>
        }
        update: {
          args: Prisma.ReminderUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReminderPayload>
        }
        deleteMany: {
          args: Prisma.ReminderDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ReminderUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ReminderUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReminderPayload>[]
        }
        upsert: {
          args: Prisma.ReminderUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReminderPayload>
        }
        aggregate: {
          args: Prisma.ReminderAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateReminder>
        }
        groupBy: {
          args: Prisma.ReminderGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ReminderGroupByOutputType>[]
        }
        count: {
          args: Prisma.ReminderCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ReminderCountAggregateOutputType> | number
        }
      }
    }
    NotificationJob: {
      payload: Prisma.$NotificationJobPayload<ExtArgs>
      fields: Prisma.NotificationJobFieldRefs
      operations: {
        findUnique: {
          args: Prisma.NotificationJobFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationJobPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.NotificationJobFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationJobPayload>
        }
        findFirst: {
          args: Prisma.NotificationJobFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationJobPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.NotificationJobFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationJobPayload>
        }
        findMany: {
          args: Prisma.NotificationJobFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationJobPayload>[]
        }
        create: {
          args: Prisma.NotificationJobCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationJobPayload>
        }
        createMany: {
          args: Prisma.NotificationJobCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.NotificationJobCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationJobPayload>[]
        }
        delete: {
          args: Prisma.NotificationJobDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationJobPayload>
        }
        update: {
          args: Prisma.NotificationJobUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationJobPayload>
        }
        deleteMany: {
          args: Prisma.NotificationJobDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.NotificationJobUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.NotificationJobUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationJobPayload>[]
        }
        upsert: {
          args: Prisma.NotificationJobUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationJobPayload>
        }
        aggregate: {
          args: Prisma.NotificationJobAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateNotificationJob>
        }
        groupBy: {
          args: Prisma.NotificationJobGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationJobGroupByOutputType>[]
        }
        count: {
          args: Prisma.NotificationJobCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationJobCountAggregateOutputType> | number
        }
      }
    }
    Campaign: {
      payload: Prisma.$CampaignPayload<ExtArgs>
      fields: Prisma.CampaignFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CampaignFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampaignPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CampaignFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampaignPayload>
        }
        findFirst: {
          args: Prisma.CampaignFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampaignPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CampaignFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampaignPayload>
        }
        findMany: {
          args: Prisma.CampaignFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampaignPayload>[]
        }
        create: {
          args: Prisma.CampaignCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampaignPayload>
        }
        createMany: {
          args: Prisma.CampaignCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.CampaignCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampaignPayload>[]
        }
        delete: {
          args: Prisma.CampaignDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampaignPayload>
        }
        update: {
          args: Prisma.CampaignUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampaignPayload>
        }
        deleteMany: {
          args: Prisma.CampaignDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CampaignUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.CampaignUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampaignPayload>[]
        }
        upsert: {
          args: Prisma.CampaignUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampaignPayload>
        }
        aggregate: {
          args: Prisma.CampaignAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCampaign>
        }
        groupBy: {
          args: Prisma.CampaignGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CampaignGroupByOutputType>[]
        }
        count: {
          args: Prisma.CampaignCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CampaignCountAggregateOutputType> | number
        }
      }
    }
    ClinicSettings: {
      payload: Prisma.$ClinicSettingsPayload<ExtArgs>
      fields: Prisma.ClinicSettingsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ClinicSettingsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClinicSettingsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ClinicSettingsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClinicSettingsPayload>
        }
        findFirst: {
          args: Prisma.ClinicSettingsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClinicSettingsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ClinicSettingsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClinicSettingsPayload>
        }
        findMany: {
          args: Prisma.ClinicSettingsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClinicSettingsPayload>[]
        }
        create: {
          args: Prisma.ClinicSettingsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClinicSettingsPayload>
        }
        createMany: {
          args: Prisma.ClinicSettingsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ClinicSettingsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClinicSettingsPayload>[]
        }
        delete: {
          args: Prisma.ClinicSettingsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClinicSettingsPayload>
        }
        update: {
          args: Prisma.ClinicSettingsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClinicSettingsPayload>
        }
        deleteMany: {
          args: Prisma.ClinicSettingsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ClinicSettingsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ClinicSettingsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClinicSettingsPayload>[]
        }
        upsert: {
          args: Prisma.ClinicSettingsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClinicSettingsPayload>
        }
        aggregate: {
          args: Prisma.ClinicSettingsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateClinicSettings>
        }
        groupBy: {
          args: Prisma.ClinicSettingsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ClinicSettingsGroupByOutputType>[]
        }
        count: {
          args: Prisma.ClinicSettingsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ClinicSettingsCountAggregateOutputType> | number
        }
      }
    }
    BusinessHours: {
      payload: Prisma.$BusinessHoursPayload<ExtArgs>
      fields: Prisma.BusinessHoursFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BusinessHoursFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BusinessHoursPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BusinessHoursFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BusinessHoursPayload>
        }
        findFirst: {
          args: Prisma.BusinessHoursFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BusinessHoursPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BusinessHoursFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BusinessHoursPayload>
        }
        findMany: {
          args: Prisma.BusinessHoursFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BusinessHoursPayload>[]
        }
        create: {
          args: Prisma.BusinessHoursCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BusinessHoursPayload>
        }
        createMany: {
          args: Prisma.BusinessHoursCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.BusinessHoursCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BusinessHoursPayload>[]
        }
        delete: {
          args: Prisma.BusinessHoursDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BusinessHoursPayload>
        }
        update: {
          args: Prisma.BusinessHoursUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BusinessHoursPayload>
        }
        deleteMany: {
          args: Prisma.BusinessHoursDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BusinessHoursUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.BusinessHoursUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BusinessHoursPayload>[]
        }
        upsert: {
          args: Prisma.BusinessHoursUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BusinessHoursPayload>
        }
        aggregate: {
          args: Prisma.BusinessHoursAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBusinessHours>
        }
        groupBy: {
          args: Prisma.BusinessHoursGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BusinessHoursGroupByOutputType>[]
        }
        count: {
          args: Prisma.BusinessHoursCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BusinessHoursCountAggregateOutputType> | number
        }
      }
    }
    EscalationLog: {
      payload: Prisma.$EscalationLogPayload<ExtArgs>
      fields: Prisma.EscalationLogFieldRefs
      operations: {
        findUnique: {
          args: Prisma.EscalationLogFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EscalationLogPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.EscalationLogFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EscalationLogPayload>
        }
        findFirst: {
          args: Prisma.EscalationLogFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EscalationLogPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.EscalationLogFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EscalationLogPayload>
        }
        findMany: {
          args: Prisma.EscalationLogFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EscalationLogPayload>[]
        }
        create: {
          args: Prisma.EscalationLogCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EscalationLogPayload>
        }
        createMany: {
          args: Prisma.EscalationLogCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.EscalationLogCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EscalationLogPayload>[]
        }
        delete: {
          args: Prisma.EscalationLogDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EscalationLogPayload>
        }
        update: {
          args: Prisma.EscalationLogUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EscalationLogPayload>
        }
        deleteMany: {
          args: Prisma.EscalationLogDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.EscalationLogUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.EscalationLogUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EscalationLogPayload>[]
        }
        upsert: {
          args: Prisma.EscalationLogUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EscalationLogPayload>
        }
        aggregate: {
          args: Prisma.EscalationLogAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateEscalationLog>
        }
        groupBy: {
          args: Prisma.EscalationLogGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EscalationLogGroupByOutputType>[]
        }
        count: {
          args: Prisma.EscalationLogCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EscalationLogCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const ClinicScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  address: 'address',
  phone: 'phone',
  email: 'email',
  website: 'website',
  timezone: 'timezone',
  twilioPhoneNumber: 'twilioPhoneNumber',
  isActive: 'isActive',
  subscriptionPlan: 'subscriptionPlan',
  subscriptionExpiresAt: 'subscriptionExpiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ClinicScalarFieldEnum = (typeof ClinicScalarFieldEnum)[keyof typeof ClinicScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  passwordHash: 'passwordHash',
  firstName: 'firstName',
  lastName: 'lastName',
  phone: 'phone',
  isEmailVerified: 'isEmailVerified',
  lastLoginAt: 'lastLoginAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const MembershipScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  clinicId: 'clinicId',
  role: 'role',
  isActive: 'isActive',
  invitedBy: 'invitedBy',
  invitedAt: 'invitedAt',
  joinedAt: 'joinedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MembershipScalarFieldEnum = (typeof MembershipScalarFieldEnum)[keyof typeof MembershipScalarFieldEnum]


export const DoctorScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  userId: 'userId',
  firstName: 'firstName',
  lastName: 'lastName',
  email: 'email',
  phone: 'phone',
  specialty: 'specialty',
  licenseNumber: 'licenseNumber',
  availabilitySchedule: 'availabilitySchedule',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DoctorScalarFieldEnum = (typeof DoctorScalarFieldEnum)[keyof typeof DoctorScalarFieldEnum]


export const ServiceScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  name: 'name',
  description: 'description',
  durationMinutes: 'durationMinutes',
  price: 'price',
  category: 'category',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ServiceScalarFieldEnum = (typeof ServiceScalarFieldEnum)[keyof typeof ServiceScalarFieldEnum]


export const AvailableSlotScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  serviceId: 'serviceId',
  startTime: 'startTime',
  endTime: 'endTime',
  isHeld: 'isHeld',
  heldBySessionId: 'heldBySessionId',
  heldAt: 'heldAt',
  isBooked: 'isBooked',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AvailableSlotScalarFieldEnum = (typeof AvailableSlotScalarFieldEnum)[keyof typeof AvailableSlotScalarFieldEnum]


export const ConversationSessionScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  phoneNumber: 'phoneNumber',
  currentState: 'currentState',
  previousState: 'previousState',
  slotServiceId: 'slotServiceId',
  slotDate: 'slotDate',
  slotTimeId: 'slotTimeId',
  slotPatientName: 'slotPatientName',
  slotPatientDob: 'slotPatientDob',
  slotPhoneConfirmed: 'slotPhoneConfirmed',
  detectedLanguage: 'detectedLanguage',
  retryCount: 'retryCount',
  maxRetriesPerState: 'maxRetriesPerState',
  invalidInputCount: 'invalidInputCount',
  ambiguousIntents: 'ambiguousIntents',
  escalationReason: 'escalationReason',
  escalationClaimedBy: 'escalationClaimedBy',
  escalationClaimedAt: 'escalationClaimedAt',
  bookingId: 'bookingId',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  resolvedAt: 'resolvedAt'
} as const

export type ConversationSessionScalarFieldEnum = (typeof ConversationSessionScalarFieldEnum)[keyof typeof ConversationSessionScalarFieldEnum]


export const ConversationMessageScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  clinicId: 'clinicId',
  role: 'role',
  channel: 'channel',
  content: 'content',
  contentNormalized: 'contentNormalized',
  twilioMessageSid: 'twilioMessageSid',
  twilioStatus: 'twilioStatus',
  claudeModel: 'claudeModel',
  claudeInputTokens: 'claudeInputTokens',
  claudeOutputTokens: 'claudeOutputTokens',
  claudeToolsUsed: 'claudeToolsUsed',
  sessionStateAtSend: 'sessionStateAtSend',
  createdAt: 'createdAt'
} as const

export type ConversationMessageScalarFieldEnum = (typeof ConversationMessageScalarFieldEnum)[keyof typeof ConversationMessageScalarFieldEnum]


export const StateTransitionLogScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  clinicId: 'clinicId',
  fromState: 'fromState',
  toState: 'toState',
  triggerType: 'triggerType',
  triggerPayload: 'triggerPayload',
  triggeredBy: 'triggeredBy',
  createdAt: 'createdAt'
} as const

export type StateTransitionLogScalarFieldEnum = (typeof StateTransitionLogScalarFieldEnum)[keyof typeof StateTransitionLogScalarFieldEnum]


export const PatientScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  firstName: 'firstName',
  lastName: 'lastName',
  email: 'email',
  phone: 'phone',
  dateOfBirth: 'dateOfBirth',
  address: 'address',
  emergencyContactName: 'emergencyContactName',
  emergencyContactPhone: 'emergencyContactPhone',
  medicalHistory: 'medicalHistory',
  allergies: 'allergies',
  notes: 'notes',
  lastVisitAt: 'lastVisitAt',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PatientScalarFieldEnum = (typeof PatientScalarFieldEnum)[keyof typeof PatientScalarFieldEnum]


export const AppointmentScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  patientId: 'patientId',
  doctorId: 'doctorId',
  serviceId: 'serviceId',
  scheduledAt: 'scheduledAt',
  durationMinutes: 'durationMinutes',
  status: 'status',
  confirmationRequestedAt: 'confirmationRequestedAt',
  confirmedAt: 'confirmedAt',
  reminder24hSentAt: 'reminder24hSentAt',
  reminder3hSentAt: 'reminder3hSentAt',
  lastReminderType: 'lastReminderType',
  lastPatientMessageAt: 'lastPatientMessageAt',
  notes: 'notes',
  cancellationReason: 'cancellationReason',
  rescheduledFromId: 'rescheduledFromId',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AppointmentScalarFieldEnum = (typeof AppointmentScalarFieldEnum)[keyof typeof AppointmentScalarFieldEnum]


export const ConversationScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  patientId: 'patientId',
  channel: 'channel',
  externalId: 'externalId',
  isActive: 'isActive',
  lastMessageAt: 'lastMessageAt',
  assignedTo: 'assignedTo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ConversationScalarFieldEnum = (typeof ConversationScalarFieldEnum)[keyof typeof ConversationScalarFieldEnum]


export const MessageScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  senderType: 'senderType',
  senderId: 'senderId',
  content: 'content',
  messageType: 'messageType',
  externalId: 'externalId',
  status: 'status',
  sentAt: 'sentAt',
  deliveredAt: 'deliveredAt',
  readAt: 'readAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MessageScalarFieldEnum = (typeof MessageScalarFieldEnum)[keyof typeof MessageScalarFieldEnum]


export const ReminderScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  appointmentId: 'appointmentId',
  type: 'type',
  scheduledAt: 'scheduledAt',
  sentAt: 'sentAt',
  status: 'status',
  template: 'template',
  customMessage: 'customMessage',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ReminderScalarFieldEnum = (typeof ReminderScalarFieldEnum)[keyof typeof ReminderScalarFieldEnum]


export const NotificationJobScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  reminderId: 'reminderId',
  appointmentId: 'appointmentId',
  patientId: 'patientId',
  channel: 'channel',
  destination: 'destination',
  messageBody: 'messageBody',
  provider: 'provider',
  providerMessageId: 'providerMessageId',
  status: 'status',
  errorMessage: 'errorMessage',
  scheduledFor: 'scheduledFor',
  sentAt: 'sentAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type NotificationJobScalarFieldEnum = (typeof NotificationJobScalarFieldEnum)[keyof typeof NotificationJobScalarFieldEnum]


export const CampaignScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  name: 'name',
  description: 'description',
  type: 'type',
  targetAudience: 'targetAudience',
  channel: 'channel',
  template: 'template',
  scheduledAt: 'scheduledAt',
  status: 'status',
  sentCount: 'sentCount',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CampaignScalarFieldEnum = (typeof CampaignScalarFieldEnum)[keyof typeof CampaignScalarFieldEnum]


export const ClinicSettingsScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  appointmentBufferMinutes: 'appointmentBufferMinutes',
  maxAdvanceBookingDays: 'maxAdvanceBookingDays',
  timezone: 'timezone',
  currency: 'currency',
  workingHours: 'workingHours',
  reminderSettings: 'reminderSettings',
  notificationSettings: 'notificationSettings',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ClinicSettingsScalarFieldEnum = (typeof ClinicSettingsScalarFieldEnum)[keyof typeof ClinicSettingsScalarFieldEnum]


export const BusinessHoursScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  dayOfWeek: 'dayOfWeek',
  isOpen: 'isOpen',
  openTime: 'openTime',
  closeTime: 'closeTime',
  breakStart: 'breakStart',
  breakEnd: 'breakEnd',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BusinessHoursScalarFieldEnum = (typeof BusinessHoursScalarFieldEnum)[keyof typeof BusinessHoursScalarFieldEnum]


export const EscalationLogScalarFieldEnum = {
  id: 'id',
  clinicId: 'clinicId',
  entityType: 'entityType',
  entityId: 'entityId',
  eventType: 'eventType',
  severity: 'severity',
  message: 'message',
  metadata: 'metadata',
  userId: 'userId',
  createdAt: 'createdAt'
} as const

export type EscalationLogScalarFieldEnum = (typeof EscalationLogScalarFieldEnum)[keyof typeof EscalationLogScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'SubscriptionPlan'
 */
export type EnumSubscriptionPlanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SubscriptionPlan'>
    


/**
 * Reference to a field of type 'SubscriptionPlan[]'
 */
export type ListEnumSubscriptionPlanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SubscriptionPlan[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'Role'
 */
export type EnumRoleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Role'>
    


/**
 * Reference to a field of type 'Role[]'
 */
export type ListEnumRoleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Role[]'>
    


/**
 * Reference to a field of type 'Json'
 */
export type JsonFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Json'>
    


/**
 * Reference to a field of type 'QueryMode'
 */
export type EnumQueryModeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'QueryMode'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    


/**
 * Reference to a field of type 'ConversationState'
 */
export type EnumConversationStateFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ConversationState'>
    


/**
 * Reference to a field of type 'ConversationState[]'
 */
export type ListEnumConversationStateFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ConversationState[]'>
    


/**
 * Reference to a field of type 'DetectedLanguage'
 */
export type EnumDetectedLanguageFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DetectedLanguage'>
    


/**
 * Reference to a field of type 'DetectedLanguage[]'
 */
export type ListEnumDetectedLanguageFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DetectedLanguage[]'>
    


/**
 * Reference to a field of type 'EscalationReason'
 */
export type EnumEscalationReasonFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'EscalationReason'>
    


/**
 * Reference to a field of type 'EscalationReason[]'
 */
export type ListEnumEscalationReasonFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'EscalationReason[]'>
    


/**
 * Reference to a field of type 'SenderType'
 */
export type EnumSenderTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SenderType'>
    


/**
 * Reference to a field of type 'SenderType[]'
 */
export type ListEnumSenderTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SenderType[]'>
    


/**
 * Reference to a field of type 'Channel'
 */
export type EnumChannelFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Channel'>
    


/**
 * Reference to a field of type 'Channel[]'
 */
export type ListEnumChannelFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Channel[]'>
    


/**
 * Reference to a field of type 'AppointmentStatus'
 */
export type EnumAppointmentStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'AppointmentStatus'>
    


/**
 * Reference to a field of type 'AppointmentStatus[]'
 */
export type ListEnumAppointmentStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'AppointmentStatus[]'>
    


/**
 * Reference to a field of type 'MessageType'
 */
export type EnumMessageTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'MessageType'>
    


/**
 * Reference to a field of type 'MessageType[]'
 */
export type ListEnumMessageTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'MessageType[]'>
    


/**
 * Reference to a field of type 'MessageStatus'
 */
export type EnumMessageStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'MessageStatus'>
    


/**
 * Reference to a field of type 'MessageStatus[]'
 */
export type ListEnumMessageStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'MessageStatus[]'>
    


/**
 * Reference to a field of type 'ReminderType'
 */
export type EnumReminderTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ReminderType'>
    


/**
 * Reference to a field of type 'ReminderType[]'
 */
export type ListEnumReminderTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ReminderType[]'>
    


/**
 * Reference to a field of type 'ReminderStatus'
 */
export type EnumReminderStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ReminderStatus'>
    


/**
 * Reference to a field of type 'ReminderStatus[]'
 */
export type ListEnumReminderStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ReminderStatus[]'>
    


/**
 * Reference to a field of type 'NotificationJobStatus'
 */
export type EnumNotificationJobStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'NotificationJobStatus'>
    


/**
 * Reference to a field of type 'NotificationJobStatus[]'
 */
export type ListEnumNotificationJobStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'NotificationJobStatus[]'>
    


/**
 * Reference to a field of type 'CampaignType'
 */
export type EnumCampaignTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'CampaignType'>
    


/**
 * Reference to a field of type 'CampaignType[]'
 */
export type ListEnumCampaignTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'CampaignType[]'>
    


/**
 * Reference to a field of type 'CampaignStatus'
 */
export type EnumCampaignStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'CampaignStatus'>
    


/**
 * Reference to a field of type 'CampaignStatus[]'
 */
export type ListEnumCampaignStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'CampaignStatus[]'>
    


/**
 * Reference to a field of type 'EntityType'
 */
export type EnumEntityTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'EntityType'>
    


/**
 * Reference to a field of type 'EntityType[]'
 */
export type ListEnumEntityTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'EntityType[]'>
    


/**
 * Reference to a field of type 'Severity'
 */
export type EnumSeverityFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Severity'>
    


/**
 * Reference to a field of type 'Severity[]'
 */
export type ListEnumSeverityFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Severity[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
}
export type GlobalOmitConfig = {
  clinic?: Prisma.ClinicOmit
  user?: Prisma.UserOmit
  membership?: Prisma.MembershipOmit
  doctor?: Prisma.DoctorOmit
  service?: Prisma.ServiceOmit
  availableSlot?: Prisma.AvailableSlotOmit
  conversationSession?: Prisma.ConversationSessionOmit
  conversationMessage?: Prisma.ConversationMessageOmit
  stateTransitionLog?: Prisma.StateTransitionLogOmit
  patient?: Prisma.PatientOmit
  appointment?: Prisma.AppointmentOmit
  conversation?: Prisma.ConversationOmit
  message?: Prisma.MessageOmit
  reminder?: Prisma.ReminderOmit
  notificationJob?: Prisma.NotificationJobOmit
  campaign?: Prisma.CampaignOmit
  clinicSettings?: Prisma.ClinicSettingsOmit
  businessHours?: Prisma.BusinessHoursOmit
  escalationLog?: Prisma.EscalationLogOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

