
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AvailableSlot` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AvailableSlot
 * 
 */
export type AvailableSlotModel = runtime.Types.Result.DefaultSelection<Prisma.$AvailableSlotPayload>

export type AggregateAvailableSlot = {
  _count: AvailableSlotCountAggregateOutputType | null
  _min: AvailableSlotMinAggregateOutputType | null
  _max: AvailableSlotMaxAggregateOutputType | null
}

export type AvailableSlotMinAggregateOutputType = {
  id: string | null
  clinicId: string | null
  serviceId: string | null
  startTime: Date | null
  endTime: Date | null
  isHeld: boolean | null
  heldBySessionId: string | null
  heldAt: Date | null
  isBooked: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AvailableSlotMaxAggregateOutputType = {
  id: string | null
  clinicId: string | null
  serviceId: string | null
  startTime: Date | null
  endTime: Date | null
  isHeld: boolean | null
  heldBySessionId: string | null
  heldAt: Date | null
  isBooked: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AvailableSlotCountAggregateOutputType = {
  id: number
  clinicId: number
  serviceId: number
  startTime: number
  endTime: number
  isHeld: number
  heldBySessionId: number
  heldAt: number
  isBooked: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AvailableSlotMinAggregateInputType = {
  id?: true
  clinicId?: true
  serviceId?: true
  startTime?: true
  endTime?: true
  isHeld?: true
  heldBySessionId?: true
  heldAt?: true
  isBooked?: true
  createdAt?: true
  updatedAt?: true
}

export type AvailableSlotMaxAggregateInputType = {
  id?: true
  clinicId?: true
  serviceId?: true
  startTime?: true
  endTime?: true
  isHeld?: true
  heldBySessionId?: true
  heldAt?: true
  isBooked?: true
  createdAt?: true
  updatedAt?: true
}

export type AvailableSlotCountAggregateInputType = {
  id?: true
  clinicId?: true
  serviceId?: true
  startTime?: true
  endTime?: true
  isHeld?: true
  heldBySessionId?: true
  heldAt?: true
  isBooked?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AvailableSlotAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AvailableSlot to aggregate.
   */
  where?: Prisma.AvailableSlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AvailableSlots to fetch.
   */
  orderBy?: Prisma.AvailableSlotOrderByWithRelationInput | Prisma.AvailableSlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AvailableSlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AvailableSlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AvailableSlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AvailableSlots
  **/
  _count?: true | AvailableSlotCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AvailableSlotMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AvailableSlotMaxAggregateInputType
}

export type GetAvailableSlotAggregateType<T extends AvailableSlotAggregateArgs> = {
      [P in keyof T & keyof AggregateAvailableSlot]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAvailableSlot[P]>
    : Prisma.GetScalarType<T[P], AggregateAvailableSlot[P]>
}




export type AvailableSlotGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AvailableSlotWhereInput
  orderBy?: Prisma.AvailableSlotOrderByWithAggregationInput | Prisma.AvailableSlotOrderByWithAggregationInput[]
  by: Prisma.AvailableSlotScalarFieldEnum[] | Prisma.AvailableSlotScalarFieldEnum
  having?: Prisma.AvailableSlotScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AvailableSlotCountAggregateInputType | true
  _min?: AvailableSlotMinAggregateInputType
  _max?: AvailableSlotMaxAggregateInputType
}

export type AvailableSlotGroupByOutputType = {
  id: string
  clinicId: string
  serviceId: string
  startTime: Date
  endTime: Date
  isHeld: boolean
  heldBySessionId: string | null
  heldAt: Date | null
  isBooked: boolean
  createdAt: Date
  updatedAt: Date
  _count: AvailableSlotCountAggregateOutputType | null
  _min: AvailableSlotMinAggregateOutputType | null
  _max: AvailableSlotMaxAggregateOutputType | null
}

export type GetAvailableSlotGroupByPayload<T extends AvailableSlotGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AvailableSlotGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AvailableSlotGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AvailableSlotGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AvailableSlotGroupByOutputType[P]>
      }
    >
  >



export type AvailableSlotWhereInput = {
  AND?: Prisma.AvailableSlotWhereInput | Prisma.AvailableSlotWhereInput[]
  OR?: Prisma.AvailableSlotWhereInput[]
  NOT?: Prisma.AvailableSlotWhereInput | Prisma.AvailableSlotWhereInput[]
  id?: Prisma.StringFilter<"AvailableSlot"> | string
  clinicId?: Prisma.StringFilter<"AvailableSlot"> | string
  serviceId?: Prisma.StringFilter<"AvailableSlot"> | string
  startTime?: Prisma.DateTimeFilter<"AvailableSlot"> | Date | string
  endTime?: Prisma.DateTimeFilter<"AvailableSlot"> | Date | string
  isHeld?: Prisma.BoolFilter<"AvailableSlot"> | boolean
  heldBySessionId?: Prisma.StringNullableFilter<"AvailableSlot"> | string | null
  heldAt?: Prisma.DateTimeNullableFilter<"AvailableSlot"> | Date | string | null
  isBooked?: Prisma.BoolFilter<"AvailableSlot"> | boolean
  createdAt?: Prisma.DateTimeFilter<"AvailableSlot"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AvailableSlot"> | Date | string
  clinic?: Prisma.XOR<Prisma.ClinicScalarRelationFilter, Prisma.ClinicWhereInput>
  service?: Prisma.XOR<Prisma.ServiceScalarRelationFilter, Prisma.ServiceWhereInput>
  sessions?: Prisma.ConversationSessionListRelationFilter
}

export type AvailableSlotOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  clinicId?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  isHeld?: Prisma.SortOrder
  heldBySessionId?: Prisma.SortOrderInput | Prisma.SortOrder
  heldAt?: Prisma.SortOrderInput | Prisma.SortOrder
  isBooked?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  clinic?: Prisma.ClinicOrderByWithRelationInput
  service?: Prisma.ServiceOrderByWithRelationInput
  sessions?: Prisma.ConversationSessionOrderByRelationAggregateInput
}

export type AvailableSlotWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AvailableSlotWhereInput | Prisma.AvailableSlotWhereInput[]
  OR?: Prisma.AvailableSlotWhereInput[]
  NOT?: Prisma.AvailableSlotWhereInput | Prisma.AvailableSlotWhereInput[]
  clinicId?: Prisma.StringFilter<"AvailableSlot"> | string
  serviceId?: Prisma.StringFilter<"AvailableSlot"> | string
  startTime?: Prisma.DateTimeFilter<"AvailableSlot"> | Date | string
  endTime?: Prisma.DateTimeFilter<"AvailableSlot"> | Date | string
  isHeld?: Prisma.BoolFilter<"AvailableSlot"> | boolean
  heldBySessionId?: Prisma.StringNullableFilter<"AvailableSlot"> | string | null
  heldAt?: Prisma.DateTimeNullableFilter<"AvailableSlot"> | Date | string | null
  isBooked?: Prisma.BoolFilter<"AvailableSlot"> | boolean
  createdAt?: Prisma.DateTimeFilter<"AvailableSlot"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AvailableSlot"> | Date | string
  clinic?: Prisma.XOR<Prisma.ClinicScalarRelationFilter, Prisma.ClinicWhereInput>
  service?: Prisma.XOR<Prisma.ServiceScalarRelationFilter, Prisma.ServiceWhereInput>
  sessions?: Prisma.ConversationSessionListRelationFilter
}, "id">

export type AvailableSlotOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  clinicId?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  isHeld?: Prisma.SortOrder
  heldBySessionId?: Prisma.SortOrderInput | Prisma.SortOrder
  heldAt?: Prisma.SortOrderInput | Prisma.SortOrder
  isBooked?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AvailableSlotCountOrderByAggregateInput
  _max?: Prisma.AvailableSlotMaxOrderByAggregateInput
  _min?: Prisma.AvailableSlotMinOrderByAggregateInput
}

export type AvailableSlotScalarWhereWithAggregatesInput = {
  AND?: Prisma.AvailableSlotScalarWhereWithAggregatesInput | Prisma.AvailableSlotScalarWhereWithAggregatesInput[]
  OR?: Prisma.AvailableSlotScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AvailableSlotScalarWhereWithAggregatesInput | Prisma.AvailableSlotScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AvailableSlot"> | string
  clinicId?: Prisma.StringWithAggregatesFilter<"AvailableSlot"> | string
  serviceId?: Prisma.StringWithAggregatesFilter<"AvailableSlot"> | string
  startTime?: Prisma.DateTimeWithAggregatesFilter<"AvailableSlot"> | Date | string
  endTime?: Prisma.DateTimeWithAggregatesFilter<"AvailableSlot"> | Date | string
  isHeld?: Prisma.BoolWithAggregatesFilter<"AvailableSlot"> | boolean
  heldBySessionId?: Prisma.StringNullableWithAggregatesFilter<"AvailableSlot"> | string | null
  heldAt?: Prisma.DateTimeNullableWithAggregatesFilter<"AvailableSlot"> | Date | string | null
  isBooked?: Prisma.BoolWithAggregatesFilter<"AvailableSlot"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AvailableSlot"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AvailableSlot"> | Date | string
}

export type AvailableSlotCreateInput = {
  id?: string
  startTime: Date | string
  endTime: Date | string
  isHeld?: boolean
  heldBySessionId?: string | null
  heldAt?: Date | string | null
  isBooked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  clinic: Prisma.ClinicCreateNestedOneWithoutAvailableSlotsInput
  service: Prisma.ServiceCreateNestedOneWithoutAvailableSlotsInput
  sessions?: Prisma.ConversationSessionCreateNestedManyWithoutSlotTimeInput
}

export type AvailableSlotUncheckedCreateInput = {
  id?: string
  clinicId: string
  serviceId: string
  startTime: Date | string
  endTime: Date | string
  isHeld?: boolean
  heldBySessionId?: string | null
  heldAt?: Date | string | null
  isBooked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  sessions?: Prisma.ConversationSessionUncheckedCreateNestedManyWithoutSlotTimeInput
}

export type AvailableSlotUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isHeld?: Prisma.BoolFieldUpdateOperationsInput | boolean
  heldBySessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  heldAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isBooked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  clinic?: Prisma.ClinicUpdateOneRequiredWithoutAvailableSlotsNestedInput
  service?: Prisma.ServiceUpdateOneRequiredWithoutAvailableSlotsNestedInput
  sessions?: Prisma.ConversationSessionUpdateManyWithoutSlotTimeNestedInput
}

export type AvailableSlotUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clinicId?: Prisma.StringFieldUpdateOperationsInput | string
  serviceId?: Prisma.StringFieldUpdateOperationsInput | string
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isHeld?: Prisma.BoolFieldUpdateOperationsInput | boolean
  heldBySessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  heldAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isBooked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sessions?: Prisma.ConversationSessionUncheckedUpdateManyWithoutSlotTimeNestedInput
}

export type AvailableSlotCreateManyInput = {
  id?: string
  clinicId: string
  serviceId: string
  startTime: Date | string
  endTime: Date | string
  isHeld?: boolean
  heldBySessionId?: string | null
  heldAt?: Date | string | null
  isBooked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AvailableSlotUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isHeld?: Prisma.BoolFieldUpdateOperationsInput | boolean
  heldBySessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  heldAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isBooked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AvailableSlotUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clinicId?: Prisma.StringFieldUpdateOperationsInput | string
  serviceId?: Prisma.StringFieldUpdateOperationsInput | string
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isHeld?: Prisma.BoolFieldUpdateOperationsInput | boolean
  heldBySessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  heldAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isBooked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AvailableSlotListRelationFilter = {
  every?: Prisma.AvailableSlotWhereInput
  some?: Prisma.AvailableSlotWhereInput
  none?: Prisma.AvailableSlotWhereInput
}

export type AvailableSlotOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AvailableSlotCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clinicId?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  isHeld?: Prisma.SortOrder
  heldBySessionId?: Prisma.SortOrder
  heldAt?: Prisma.SortOrder
  isBooked?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AvailableSlotMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clinicId?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  isHeld?: Prisma.SortOrder
  heldBySessionId?: Prisma.SortOrder
  heldAt?: Prisma.SortOrder
  isBooked?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AvailableSlotMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clinicId?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  isHeld?: Prisma.SortOrder
  heldBySessionId?: Prisma.SortOrder
  heldAt?: Prisma.SortOrder
  isBooked?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AvailableSlotNullableScalarRelationFilter = {
  is?: Prisma.AvailableSlotWhereInput | null
  isNot?: Prisma.AvailableSlotWhereInput | null
}

export type AvailableSlotCreateNestedManyWithoutClinicInput = {
  create?: Prisma.XOR<Prisma.AvailableSlotCreateWithoutClinicInput, Prisma.AvailableSlotUncheckedCreateWithoutClinicInput> | Prisma.AvailableSlotCreateWithoutClinicInput[] | Prisma.AvailableSlotUncheckedCreateWithoutClinicInput[]
  connectOrCreate?: Prisma.AvailableSlotCreateOrConnectWithoutClinicInput | Prisma.AvailableSlotCreateOrConnectWithoutClinicInput[]
  createMany?: Prisma.AvailableSlotCreateManyClinicInputEnvelope
  connect?: Prisma.AvailableSlotWhereUniqueInput | Prisma.AvailableSlotWhereUniqueInput[]
}

export type AvailableSlotUncheckedCreateNestedManyWithoutClinicInput = {
  create?: Prisma.XOR<Prisma.AvailableSlotCreateWithoutClinicInput, Prisma.AvailableSlotUncheckedCreateWithoutClinicInput> | Prisma.AvailableSlotCreateWithoutClinicInput[] | Prisma.AvailableSlotUncheckedCreateWithoutClinicInput[]
  connectOrCreate?: Prisma.AvailableSlotCreateOrConnectWithoutClinicInput | Prisma.AvailableSlotCreateOrConnectWithoutClinicInput[]
  createMany?: Prisma.AvailableSlotCreateManyClinicInputEnvelope
  connect?: Prisma.AvailableSlotWhereUniqueInput | Prisma.AvailableSlotWhereUniqueInput[]
}

export type AvailableSlotUpdateManyWithoutClinicNestedInput = {
  create?: Prisma.XOR<Prisma.AvailableSlotCreateWithoutClinicInput, Prisma.AvailableSlotUncheckedCreateWithoutClinicInput> | Prisma.AvailableSlotCreateWithoutClinicInput[] | Prisma.AvailableSlotUncheckedCreateWithoutClinicInput[]
  connectOrCreate?: Prisma.AvailableSlotCreateOrConnectWithoutClinicInput | Prisma.AvailableSlotCreateOrConnectWithoutClinicInput[]
  upsert?: Prisma.AvailableSlotUpsertWithWhereUniqueWithoutClinicInput | Prisma.AvailableSlotUpsertWithWhereUniqueWithoutClinicInput[]
  createMany?: Prisma.AvailableSlotCreateManyClinicInputEnvelope
  set?: Prisma.AvailableSlotWhereUniqueInput | Prisma.AvailableSlotWhereUniqueInput[]
  disconnect?: Prisma.AvailableSlotWhereUniqueInput | Prisma.AvailableSlotWhereUniqueInput[]
  delete?: Prisma.AvailableSlotWhereUniqueInput | Prisma.AvailableSlotWhereUniqueInput[]
  connect?: Prisma.AvailableSlotWhereUniqueInput | Prisma.AvailableSlotWhereUniqueInput[]
  update?: Prisma.AvailableSlotUpdateWithWhereUniqueWithoutClinicInput | Prisma.AvailableSlotUpdateWithWhereUniqueWithoutClinicInput[]
  updateMany?: Prisma.AvailableSlotUpdateManyWithWhereWithoutClinicInput | Prisma.AvailableSlotUpdateManyWithWhereWithoutClinicInput[]
  deleteMany?: Prisma.AvailableSlotScalarWhereInput | Prisma.AvailableSlotScalarWhereInput[]
}

export type AvailableSlotUncheckedUpdateManyWithoutClinicNestedInput = {
  create?: Prisma.XOR<Prisma.AvailableSlotCreateWithoutClinicInput, Prisma.AvailableSlotUncheckedCreateWithoutClinicInput> | Prisma.AvailableSlotCreateWithoutClinicInput[] | Prisma.AvailableSlotUncheckedCreateWithoutClinicInput[]
  connectOrCreate?: Prisma.AvailableSlotCreateOrConnectWithoutClinicInput | Prisma.AvailableSlotCreateOrConnectWithoutClinicInput[]
  upsert?: Prisma.AvailableSlotUpsertWithWhereUniqueWithoutClinicInput | Prisma.AvailableSlotUpsertWithWhereUniqueWithoutClinicInput[]
  createMany?: Prisma.AvailableSlotCreateManyClinicInputEnvelope
  set?: Prisma.AvailableSlotWhereUniqueInput | Prisma.AvailableSlotWhereUniqueInput[]
  disconnect?: Prisma.AvailableSlotWhereUniqueInput | Prisma.AvailableSlotWhereUniqueInput[]
  delete?: Prisma.AvailableSlotWhereUniqueInput | Prisma.AvailableSlotWhereUniqueInput[]
  connect?: Prisma.AvailableSlotWhereUniqueInput | Prisma.AvailableSlotWhereUniqueInput[]
  update?: Prisma.AvailableSlotUpdateWithWhereUniqueWithoutClinicInput | Prisma.AvailableSlotUpdateWithWhereUniqueWithoutClinicInput[]
  updateMany?: Prisma.AvailableSlotUpdateManyWithWhereWithoutClinicInput | Prisma.AvailableSlotUpdateManyWithWhereWithoutClinicInput[]
  deleteMany?: Prisma.AvailableSlotScalarWhereInput | Prisma.AvailableSlotScalarWhereInput[]
}

export type AvailableSlotCreateNestedManyWithoutServiceInput = {
  create?: Prisma.XOR<Prisma.AvailableSlotCreateWithoutServiceInput, Prisma.AvailableSlotUncheckedCreateWithoutServiceInput> | Prisma.AvailableSlotCreateWithoutServiceInput[] | Prisma.AvailableSlotUncheckedCreateWithoutServiceInput[]
  connectOrCreate?: Prisma.AvailableSlotCreateOrConnectWithoutServiceInput | Prisma.AvailableSlotCreateOrConnectWithoutServiceInput[]
  createMany?: Prisma.AvailableSlotCreateManyServiceInputEnvelope
  connect?: Prisma.AvailableSlotWhereUniqueInput | Prisma.AvailableSlotWhereUniqueInput[]
}

export type AvailableSlotUncheckedCreateNestedManyWithoutServiceInput = {
  create?: Prisma.XOR<Prisma.AvailableSlotCreateWithoutServiceInput, Prisma.AvailableSlotUncheckedCreateWithoutServiceInput> | Prisma.AvailableSlotCreateWithoutServiceInput[] | Prisma.AvailableSlotUncheckedCreateWithoutServiceInput[]
  connectOrCreate?: Prisma.AvailableSlotCreateOrConnectWithoutServiceInput | Prisma.AvailableSlotCreateOrConnectWithoutServiceInput[]
  createMany?: Prisma.AvailableSlotCreateManyServiceInputEnvelope
  connect?: Prisma.AvailableSlotWhereUniqueInput | Prisma.AvailableSlotWhereUniqueInput[]
}

export type AvailableSlotUpdateManyWithoutServiceNestedInput = {
  create?: Prisma.XOR<Prisma.AvailableSlotCreateWithoutServiceInput, Prisma.AvailableSlotUncheckedCreateWithoutServiceInput> | Prisma.AvailableSlotCreateWithoutServiceInput[] | Prisma.AvailableSlotUncheckedCreateWithoutServiceInput[]
  connectOrCreate?: Prisma.AvailableSlotCreateOrConnectWithoutServiceInput | Prisma.AvailableSlotCreateOrConnectWithoutServiceInput[]
  upsert?: Prisma.AvailableSlotUpsertWithWhereUniqueWithoutServiceInput | Prisma.AvailableSlotUpsertWithWhereUniqueWithoutServiceInput[]
  createMany?: Prisma.AvailableSlotCreateManyServiceInputEnvelope
  set?: Prisma.AvailableSlotWhereUniqueInput | Prisma.AvailableSlotWhereUniqueInput[]
  disconnect?: Prisma.AvailableSlotWhereUniqueInput | Prisma.AvailableSlotWhereUniqueInput[]
  delete?: Prisma.AvailableSlotWhereUniqueInput | Prisma.AvailableSlotWhereUniqueInput[]
  connect?: Prisma.AvailableSlotWhereUniqueInput | Prisma.AvailableSlotWhereUniqueInput[]
  update?: Prisma.AvailableSlotUpdateWithWhereUniqueWithoutServiceInput | Prisma.AvailableSlotUpdateWithWhereUniqueWithoutServiceInput[]
  updateMany?: Prisma.AvailableSlotUpdateManyWithWhereWithoutServiceInput | Prisma.AvailableSlotUpdateManyWithWhereWithoutServiceInput[]
  deleteMany?: Prisma.AvailableSlotScalarWhereInput | Prisma.AvailableSlotScalarWhereInput[]
}

export type AvailableSlotUncheckedUpdateManyWithoutServiceNestedInput = {
  create?: Prisma.XOR<Prisma.AvailableSlotCreateWithoutServiceInput, Prisma.AvailableSlotUncheckedCreateWithoutServiceInput> | Prisma.AvailableSlotCreateWithoutServiceInput[] | Prisma.AvailableSlotUncheckedCreateWithoutServiceInput[]
  connectOrCreate?: Prisma.AvailableSlotCreateOrConnectWithoutServiceInput | Prisma.AvailableSlotCreateOrConnectWithoutServiceInput[]
  upsert?: Prisma.AvailableSlotUpsertWithWhereUniqueWithoutServiceInput | Prisma.AvailableSlotUpsertWithWhereUniqueWithoutServiceInput[]
  createMany?: Prisma.AvailableSlotCreateManyServiceInputEnvelope
  set?: Prisma.AvailableSlotWhereUniqueInput | Prisma.AvailableSlotWhereUniqueInput[]
  disconnect?: Prisma.AvailableSlotWhereUniqueInput | Prisma.AvailableSlotWhereUniqueInput[]
  delete?: Prisma.AvailableSlotWhereUniqueInput | Prisma.AvailableSlotWhereUniqueInput[]
  connect?: Prisma.AvailableSlotWhereUniqueInput | Prisma.AvailableSlotWhereUniqueInput[]
  update?: Prisma.AvailableSlotUpdateWithWhereUniqueWithoutServiceInput | Prisma.AvailableSlotUpdateWithWhereUniqueWithoutServiceInput[]
  updateMany?: Prisma.AvailableSlotUpdateManyWithWhereWithoutServiceInput | Prisma.AvailableSlotUpdateManyWithWhereWithoutServiceInput[]
  deleteMany?: Prisma.AvailableSlotScalarWhereInput | Prisma.AvailableSlotScalarWhereInput[]
}

export type AvailableSlotCreateNestedOneWithoutSessionsInput = {
  create?: Prisma.XOR<Prisma.AvailableSlotCreateWithoutSessionsInput, Prisma.AvailableSlotUncheckedCreateWithoutSessionsInput>
  connectOrCreate?: Prisma.AvailableSlotCreateOrConnectWithoutSessionsInput
  connect?: Prisma.AvailableSlotWhereUniqueInput
}

export type AvailableSlotUpdateOneWithoutSessionsNestedInput = {
  create?: Prisma.XOR<Prisma.AvailableSlotCreateWithoutSessionsInput, Prisma.AvailableSlotUncheckedCreateWithoutSessionsInput>
  connectOrCreate?: Prisma.AvailableSlotCreateOrConnectWithoutSessionsInput
  upsert?: Prisma.AvailableSlotUpsertWithoutSessionsInput
  disconnect?: Prisma.AvailableSlotWhereInput | boolean
  delete?: Prisma.AvailableSlotWhereInput | boolean
  connect?: Prisma.AvailableSlotWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AvailableSlotUpdateToOneWithWhereWithoutSessionsInput, Prisma.AvailableSlotUpdateWithoutSessionsInput>, Prisma.AvailableSlotUncheckedUpdateWithoutSessionsInput>
}

export type AvailableSlotCreateWithoutClinicInput = {
  id?: string
  startTime: Date | string
  endTime: Date | string
  isHeld?: boolean
  heldBySessionId?: string | null
  heldAt?: Date | string | null
  isBooked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  service: Prisma.ServiceCreateNestedOneWithoutAvailableSlotsInput
  sessions?: Prisma.ConversationSessionCreateNestedManyWithoutSlotTimeInput
}

export type AvailableSlotUncheckedCreateWithoutClinicInput = {
  id?: string
  serviceId: string
  startTime: Date | string
  endTime: Date | string
  isHeld?: boolean
  heldBySessionId?: string | null
  heldAt?: Date | string | null
  isBooked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  sessions?: Prisma.ConversationSessionUncheckedCreateNestedManyWithoutSlotTimeInput
}

export type AvailableSlotCreateOrConnectWithoutClinicInput = {
  where: Prisma.AvailableSlotWhereUniqueInput
  create: Prisma.XOR<Prisma.AvailableSlotCreateWithoutClinicInput, Prisma.AvailableSlotUncheckedCreateWithoutClinicInput>
}

export type AvailableSlotCreateManyClinicInputEnvelope = {
  data: Prisma.AvailableSlotCreateManyClinicInput | Prisma.AvailableSlotCreateManyClinicInput[]
  skipDuplicates?: boolean
}

export type AvailableSlotUpsertWithWhereUniqueWithoutClinicInput = {
  where: Prisma.AvailableSlotWhereUniqueInput
  update: Prisma.XOR<Prisma.AvailableSlotUpdateWithoutClinicInput, Prisma.AvailableSlotUncheckedUpdateWithoutClinicInput>
  create: Prisma.XOR<Prisma.AvailableSlotCreateWithoutClinicInput, Prisma.AvailableSlotUncheckedCreateWithoutClinicInput>
}

export type AvailableSlotUpdateWithWhereUniqueWithoutClinicInput = {
  where: Prisma.AvailableSlotWhereUniqueInput
  data: Prisma.XOR<Prisma.AvailableSlotUpdateWithoutClinicInput, Prisma.AvailableSlotUncheckedUpdateWithoutClinicInput>
}

export type AvailableSlotUpdateManyWithWhereWithoutClinicInput = {
  where: Prisma.AvailableSlotScalarWhereInput
  data: Prisma.XOR<Prisma.AvailableSlotUpdateManyMutationInput, Prisma.AvailableSlotUncheckedUpdateManyWithoutClinicInput>
}

export type AvailableSlotScalarWhereInput = {
  AND?: Prisma.AvailableSlotScalarWhereInput | Prisma.AvailableSlotScalarWhereInput[]
  OR?: Prisma.AvailableSlotScalarWhereInput[]
  NOT?: Prisma.AvailableSlotScalarWhereInput | Prisma.AvailableSlotScalarWhereInput[]
  id?: Prisma.StringFilter<"AvailableSlot"> | string
  clinicId?: Prisma.StringFilter<"AvailableSlot"> | string
  serviceId?: Prisma.StringFilter<"AvailableSlot"> | string
  startTime?: Prisma.DateTimeFilter<"AvailableSlot"> | Date | string
  endTime?: Prisma.DateTimeFilter<"AvailableSlot"> | Date | string
  isHeld?: Prisma.BoolFilter<"AvailableSlot"> | boolean
  heldBySessionId?: Prisma.StringNullableFilter<"AvailableSlot"> | string | null
  heldAt?: Prisma.DateTimeNullableFilter<"AvailableSlot"> | Date | string | null
  isBooked?: Prisma.BoolFilter<"AvailableSlot"> | boolean
  createdAt?: Prisma.DateTimeFilter<"AvailableSlot"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AvailableSlot"> | Date | string
}

export type AvailableSlotCreateWithoutServiceInput = {
  id?: string
  startTime: Date | string
  endTime: Date | string
  isHeld?: boolean
  heldBySessionId?: string | null
  heldAt?: Date | string | null
  isBooked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  clinic: Prisma.ClinicCreateNestedOneWithoutAvailableSlotsInput
  sessions?: Prisma.ConversationSessionCreateNestedManyWithoutSlotTimeInput
}

export type AvailableSlotUncheckedCreateWithoutServiceInput = {
  id?: string
  clinicId: string
  startTime: Date | string
  endTime: Date | string
  isHeld?: boolean
  heldBySessionId?: string | null
  heldAt?: Date | string | null
  isBooked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  sessions?: Prisma.ConversationSessionUncheckedCreateNestedManyWithoutSlotTimeInput
}

export type AvailableSlotCreateOrConnectWithoutServiceInput = {
  where: Prisma.AvailableSlotWhereUniqueInput
  create: Prisma.XOR<Prisma.AvailableSlotCreateWithoutServiceInput, Prisma.AvailableSlotUncheckedCreateWithoutServiceInput>
}

export type AvailableSlotCreateManyServiceInputEnvelope = {
  data: Prisma.AvailableSlotCreateManyServiceInput | Prisma.AvailableSlotCreateManyServiceInput[]
  skipDuplicates?: boolean
}

export type AvailableSlotUpsertWithWhereUniqueWithoutServiceInput = {
  where: Prisma.AvailableSlotWhereUniqueInput
  update: Prisma.XOR<Prisma.AvailableSlotUpdateWithoutServiceInput, Prisma.AvailableSlotUncheckedUpdateWithoutServiceInput>
  create: Prisma.XOR<Prisma.AvailableSlotCreateWithoutServiceInput, Prisma.AvailableSlotUncheckedCreateWithoutServiceInput>
}

export type AvailableSlotUpdateWithWhereUniqueWithoutServiceInput = {
  where: Prisma.AvailableSlotWhereUniqueInput
  data: Prisma.XOR<Prisma.AvailableSlotUpdateWithoutServiceInput, Prisma.AvailableSlotUncheckedUpdateWithoutServiceInput>
}

export type AvailableSlotUpdateManyWithWhereWithoutServiceInput = {
  where: Prisma.AvailableSlotScalarWhereInput
  data: Prisma.XOR<Prisma.AvailableSlotUpdateManyMutationInput, Prisma.AvailableSlotUncheckedUpdateManyWithoutServiceInput>
}

export type AvailableSlotCreateWithoutSessionsInput = {
  id?: string
  startTime: Date | string
  endTime: Date | string
  isHeld?: boolean
  heldBySessionId?: string | null
  heldAt?: Date | string | null
  isBooked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  clinic: Prisma.ClinicCreateNestedOneWithoutAvailableSlotsInput
  service: Prisma.ServiceCreateNestedOneWithoutAvailableSlotsInput
}

export type AvailableSlotUncheckedCreateWithoutSessionsInput = {
  id?: string
  clinicId: string
  serviceId: string
  startTime: Date | string
  endTime: Date | string
  isHeld?: boolean
  heldBySessionId?: string | null
  heldAt?: Date | string | null
  isBooked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AvailableSlotCreateOrConnectWithoutSessionsInput = {
  where: Prisma.AvailableSlotWhereUniqueInput
  create: Prisma.XOR<Prisma.AvailableSlotCreateWithoutSessionsInput, Prisma.AvailableSlotUncheckedCreateWithoutSessionsInput>
}

export type AvailableSlotUpsertWithoutSessionsInput = {
  update: Prisma.XOR<Prisma.AvailableSlotUpdateWithoutSessionsInput, Prisma.AvailableSlotUncheckedUpdateWithoutSessionsInput>
  create: Prisma.XOR<Prisma.AvailableSlotCreateWithoutSessionsInput, Prisma.AvailableSlotUncheckedCreateWithoutSessionsInput>
  where?: Prisma.AvailableSlotWhereInput
}

export type AvailableSlotUpdateToOneWithWhereWithoutSessionsInput = {
  where?: Prisma.AvailableSlotWhereInput
  data: Prisma.XOR<Prisma.AvailableSlotUpdateWithoutSessionsInput, Prisma.AvailableSlotUncheckedUpdateWithoutSessionsInput>
}

export type AvailableSlotUpdateWithoutSessionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isHeld?: Prisma.BoolFieldUpdateOperationsInput | boolean
  heldBySessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  heldAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isBooked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  clinic?: Prisma.ClinicUpdateOneRequiredWithoutAvailableSlotsNestedInput
  service?: Prisma.ServiceUpdateOneRequiredWithoutAvailableSlotsNestedInput
}

export type AvailableSlotUncheckedUpdateWithoutSessionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clinicId?: Prisma.StringFieldUpdateOperationsInput | string
  serviceId?: Prisma.StringFieldUpdateOperationsInput | string
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isHeld?: Prisma.BoolFieldUpdateOperationsInput | boolean
  heldBySessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  heldAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isBooked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AvailableSlotCreateManyClinicInput = {
  id?: string
  serviceId: string
  startTime: Date | string
  endTime: Date | string
  isHeld?: boolean
  heldBySessionId?: string | null
  heldAt?: Date | string | null
  isBooked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AvailableSlotUpdateWithoutClinicInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isHeld?: Prisma.BoolFieldUpdateOperationsInput | boolean
  heldBySessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  heldAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isBooked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  service?: Prisma.ServiceUpdateOneRequiredWithoutAvailableSlotsNestedInput
  sessions?: Prisma.ConversationSessionUpdateManyWithoutSlotTimeNestedInput
}

export type AvailableSlotUncheckedUpdateWithoutClinicInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  serviceId?: Prisma.StringFieldUpdateOperationsInput | string
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isHeld?: Prisma.BoolFieldUpdateOperationsInput | boolean
  heldBySessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  heldAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isBooked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sessions?: Prisma.ConversationSessionUncheckedUpdateManyWithoutSlotTimeNestedInput
}

export type AvailableSlotUncheckedUpdateManyWithoutClinicInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  serviceId?: Prisma.StringFieldUpdateOperationsInput | string
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isHeld?: Prisma.BoolFieldUpdateOperationsInput | boolean
  heldBySessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  heldAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isBooked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AvailableSlotCreateManyServiceInput = {
  id?: string
  clinicId: string
  startTime: Date | string
  endTime: Date | string
  isHeld?: boolean
  heldBySessionId?: string | null
  heldAt?: Date | string | null
  isBooked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AvailableSlotUpdateWithoutServiceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isHeld?: Prisma.BoolFieldUpdateOperationsInput | boolean
  heldBySessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  heldAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isBooked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  clinic?: Prisma.ClinicUpdateOneRequiredWithoutAvailableSlotsNestedInput
  sessions?: Prisma.ConversationSessionUpdateManyWithoutSlotTimeNestedInput
}

export type AvailableSlotUncheckedUpdateWithoutServiceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clinicId?: Prisma.StringFieldUpdateOperationsInput | string
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isHeld?: Prisma.BoolFieldUpdateOperationsInput | boolean
  heldBySessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  heldAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isBooked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sessions?: Prisma.ConversationSessionUncheckedUpdateManyWithoutSlotTimeNestedInput
}

export type AvailableSlotUncheckedUpdateManyWithoutServiceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clinicId?: Prisma.StringFieldUpdateOperationsInput | string
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isHeld?: Prisma.BoolFieldUpdateOperationsInput | boolean
  heldBySessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  heldAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isBooked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type AvailableSlotCountOutputType
 */

export type AvailableSlotCountOutputType = {
  sessions: number
}

export type AvailableSlotCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sessions?: boolean | AvailableSlotCountOutputTypeCountSessionsArgs
}

/**
 * AvailableSlotCountOutputType without action
 */
export type AvailableSlotCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailableSlotCountOutputType
   */
  select?: Prisma.AvailableSlotCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AvailableSlotCountOutputType without action
 */
export type AvailableSlotCountOutputTypeCountSessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ConversationSessionWhereInput
}


export type AvailableSlotSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clinicId?: boolean
  serviceId?: boolean
  startTime?: boolean
  endTime?: boolean
  isHeld?: boolean
  heldBySessionId?: boolean
  heldAt?: boolean
  isBooked?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  clinic?: boolean | Prisma.ClinicDefaultArgs<ExtArgs>
  service?: boolean | Prisma.ServiceDefaultArgs<ExtArgs>
  sessions?: boolean | Prisma.AvailableSlot$sessionsArgs<ExtArgs>
  _count?: boolean | Prisma.AvailableSlotCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["availableSlot"]>

export type AvailableSlotSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clinicId?: boolean
  serviceId?: boolean
  startTime?: boolean
  endTime?: boolean
  isHeld?: boolean
  heldBySessionId?: boolean
  heldAt?: boolean
  isBooked?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  clinic?: boolean | Prisma.ClinicDefaultArgs<ExtArgs>
  service?: boolean | Prisma.ServiceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["availableSlot"]>

export type AvailableSlotSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clinicId?: boolean
  serviceId?: boolean
  startTime?: boolean
  endTime?: boolean
  isHeld?: boolean
  heldBySessionId?: boolean
  heldAt?: boolean
  isBooked?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  clinic?: boolean | Prisma.ClinicDefaultArgs<ExtArgs>
  service?: boolean | Prisma.ServiceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["availableSlot"]>

export type AvailableSlotSelectScalar = {
  id?: boolean
  clinicId?: boolean
  serviceId?: boolean
  startTime?: boolean
  endTime?: boolean
  isHeld?: boolean
  heldBySessionId?: boolean
  heldAt?: boolean
  isBooked?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AvailableSlotOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "clinicId" | "serviceId" | "startTime" | "endTime" | "isHeld" | "heldBySessionId" | "heldAt" | "isBooked" | "createdAt" | "updatedAt", ExtArgs["result"]["availableSlot"]>
export type AvailableSlotInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  clinic?: boolean | Prisma.ClinicDefaultArgs<ExtArgs>
  service?: boolean | Prisma.ServiceDefaultArgs<ExtArgs>
  sessions?: boolean | Prisma.AvailableSlot$sessionsArgs<ExtArgs>
  _count?: boolean | Prisma.AvailableSlotCountOutputTypeDefaultArgs<ExtArgs>
}
export type AvailableSlotIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  clinic?: boolean | Prisma.ClinicDefaultArgs<ExtArgs>
  service?: boolean | Prisma.ServiceDefaultArgs<ExtArgs>
}
export type AvailableSlotIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  clinic?: boolean | Prisma.ClinicDefaultArgs<ExtArgs>
  service?: boolean | Prisma.ServiceDefaultArgs<ExtArgs>
}

export type $AvailableSlotPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AvailableSlot"
  objects: {
    clinic: Prisma.$ClinicPayload<ExtArgs>
    service: Prisma.$ServicePayload<ExtArgs>
    sessions: Prisma.$ConversationSessionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    clinicId: string
    serviceId: string
    startTime: Date
    endTime: Date
    isHeld: boolean
    heldBySessionId: string | null
    heldAt: Date | null
    isBooked: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["availableSlot"]>
  composites: {}
}

export type AvailableSlotGetPayload<S extends boolean | null | undefined | AvailableSlotDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AvailableSlotPayload, S>

export type AvailableSlotCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AvailableSlotFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AvailableSlotCountAggregateInputType | true
  }

export interface AvailableSlotDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AvailableSlot'], meta: { name: 'AvailableSlot' } }
  /**
   * Find zero or one AvailableSlot that matches the filter.
   * @param {AvailableSlotFindUniqueArgs} args - Arguments to find a AvailableSlot
   * @example
   * // Get one AvailableSlot
   * const availableSlot = await prisma.availableSlot.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AvailableSlotFindUniqueArgs>(args: Prisma.SelectSubset<T, AvailableSlotFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AvailableSlotClient<runtime.Types.Result.GetResult<Prisma.$AvailableSlotPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AvailableSlot that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AvailableSlotFindUniqueOrThrowArgs} args - Arguments to find a AvailableSlot
   * @example
   * // Get one AvailableSlot
   * const availableSlot = await prisma.availableSlot.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AvailableSlotFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AvailableSlotFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AvailableSlotClient<runtime.Types.Result.GetResult<Prisma.$AvailableSlotPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AvailableSlot that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AvailableSlotFindFirstArgs} args - Arguments to find a AvailableSlot
   * @example
   * // Get one AvailableSlot
   * const availableSlot = await prisma.availableSlot.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AvailableSlotFindFirstArgs>(args?: Prisma.SelectSubset<T, AvailableSlotFindFirstArgs<ExtArgs>>): Prisma.Prisma__AvailableSlotClient<runtime.Types.Result.GetResult<Prisma.$AvailableSlotPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AvailableSlot that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AvailableSlotFindFirstOrThrowArgs} args - Arguments to find a AvailableSlot
   * @example
   * // Get one AvailableSlot
   * const availableSlot = await prisma.availableSlot.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AvailableSlotFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AvailableSlotFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AvailableSlotClient<runtime.Types.Result.GetResult<Prisma.$AvailableSlotPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AvailableSlots that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AvailableSlotFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AvailableSlots
   * const availableSlots = await prisma.availableSlot.findMany()
   * 
   * // Get first 10 AvailableSlots
   * const availableSlots = await prisma.availableSlot.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const availableSlotWithIdOnly = await prisma.availableSlot.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AvailableSlotFindManyArgs>(args?: Prisma.SelectSubset<T, AvailableSlotFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AvailableSlotPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AvailableSlot.
   * @param {AvailableSlotCreateArgs} args - Arguments to create a AvailableSlot.
   * @example
   * // Create one AvailableSlot
   * const AvailableSlot = await prisma.availableSlot.create({
   *   data: {
   *     // ... data to create a AvailableSlot
   *   }
   * })
   * 
   */
  create<T extends AvailableSlotCreateArgs>(args: Prisma.SelectSubset<T, AvailableSlotCreateArgs<ExtArgs>>): Prisma.Prisma__AvailableSlotClient<runtime.Types.Result.GetResult<Prisma.$AvailableSlotPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AvailableSlots.
   * @param {AvailableSlotCreateManyArgs} args - Arguments to create many AvailableSlots.
   * @example
   * // Create many AvailableSlots
   * const availableSlot = await prisma.availableSlot.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AvailableSlotCreateManyArgs>(args?: Prisma.SelectSubset<T, AvailableSlotCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AvailableSlots and returns the data saved in the database.
   * @param {AvailableSlotCreateManyAndReturnArgs} args - Arguments to create many AvailableSlots.
   * @example
   * // Create many AvailableSlots
   * const availableSlot = await prisma.availableSlot.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AvailableSlots and only return the `id`
   * const availableSlotWithIdOnly = await prisma.availableSlot.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AvailableSlotCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AvailableSlotCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AvailableSlotPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AvailableSlot.
   * @param {AvailableSlotDeleteArgs} args - Arguments to delete one AvailableSlot.
   * @example
   * // Delete one AvailableSlot
   * const AvailableSlot = await prisma.availableSlot.delete({
   *   where: {
   *     // ... filter to delete one AvailableSlot
   *   }
   * })
   * 
   */
  delete<T extends AvailableSlotDeleteArgs>(args: Prisma.SelectSubset<T, AvailableSlotDeleteArgs<ExtArgs>>): Prisma.Prisma__AvailableSlotClient<runtime.Types.Result.GetResult<Prisma.$AvailableSlotPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AvailableSlot.
   * @param {AvailableSlotUpdateArgs} args - Arguments to update one AvailableSlot.
   * @example
   * // Update one AvailableSlot
   * const availableSlot = await prisma.availableSlot.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AvailableSlotUpdateArgs>(args: Prisma.SelectSubset<T, AvailableSlotUpdateArgs<ExtArgs>>): Prisma.Prisma__AvailableSlotClient<runtime.Types.Result.GetResult<Prisma.$AvailableSlotPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AvailableSlots.
   * @param {AvailableSlotDeleteManyArgs} args - Arguments to filter AvailableSlots to delete.
   * @example
   * // Delete a few AvailableSlots
   * const { count } = await prisma.availableSlot.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AvailableSlotDeleteManyArgs>(args?: Prisma.SelectSubset<T, AvailableSlotDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AvailableSlots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AvailableSlotUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AvailableSlots
   * const availableSlot = await prisma.availableSlot.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AvailableSlotUpdateManyArgs>(args: Prisma.SelectSubset<T, AvailableSlotUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AvailableSlots and returns the data updated in the database.
   * @param {AvailableSlotUpdateManyAndReturnArgs} args - Arguments to update many AvailableSlots.
   * @example
   * // Update many AvailableSlots
   * const availableSlot = await prisma.availableSlot.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AvailableSlots and only return the `id`
   * const availableSlotWithIdOnly = await prisma.availableSlot.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AvailableSlotUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AvailableSlotUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AvailableSlotPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AvailableSlot.
   * @param {AvailableSlotUpsertArgs} args - Arguments to update or create a AvailableSlot.
   * @example
   * // Update or create a AvailableSlot
   * const availableSlot = await prisma.availableSlot.upsert({
   *   create: {
   *     // ... data to create a AvailableSlot
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AvailableSlot we want to update
   *   }
   * })
   */
  upsert<T extends AvailableSlotUpsertArgs>(args: Prisma.SelectSubset<T, AvailableSlotUpsertArgs<ExtArgs>>): Prisma.Prisma__AvailableSlotClient<runtime.Types.Result.GetResult<Prisma.$AvailableSlotPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AvailableSlots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AvailableSlotCountArgs} args - Arguments to filter AvailableSlots to count.
   * @example
   * // Count the number of AvailableSlots
   * const count = await prisma.availableSlot.count({
   *   where: {
   *     // ... the filter for the AvailableSlots we want to count
   *   }
   * })
  **/
  count<T extends AvailableSlotCountArgs>(
    args?: Prisma.Subset<T, AvailableSlotCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AvailableSlotCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AvailableSlot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AvailableSlotAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AvailableSlotAggregateArgs>(args: Prisma.Subset<T, AvailableSlotAggregateArgs>): Prisma.PrismaPromise<GetAvailableSlotAggregateType<T>>

  /**
   * Group by AvailableSlot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AvailableSlotGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AvailableSlotGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AvailableSlotGroupByArgs['orderBy'] }
      : { orderBy?: AvailableSlotGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AvailableSlotGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAvailableSlotGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AvailableSlot model
 */
readonly fields: AvailableSlotFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AvailableSlot.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AvailableSlotClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  clinic<T extends Prisma.ClinicDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ClinicDefaultArgs<ExtArgs>>): Prisma.Prisma__ClinicClient<runtime.Types.Result.GetResult<Prisma.$ClinicPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  service<T extends Prisma.ServiceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ServiceDefaultArgs<ExtArgs>>): Prisma.Prisma__ServiceClient<runtime.Types.Result.GetResult<Prisma.$ServicePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  sessions<T extends Prisma.AvailableSlot$sessionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AvailableSlot$sessionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConversationSessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AvailableSlot model
 */
export interface AvailableSlotFieldRefs {
  readonly id: Prisma.FieldRef<"AvailableSlot", 'String'>
  readonly clinicId: Prisma.FieldRef<"AvailableSlot", 'String'>
  readonly serviceId: Prisma.FieldRef<"AvailableSlot", 'String'>
  readonly startTime: Prisma.FieldRef<"AvailableSlot", 'DateTime'>
  readonly endTime: Prisma.FieldRef<"AvailableSlot", 'DateTime'>
  readonly isHeld: Prisma.FieldRef<"AvailableSlot", 'Boolean'>
  readonly heldBySessionId: Prisma.FieldRef<"AvailableSlot", 'String'>
  readonly heldAt: Prisma.FieldRef<"AvailableSlot", 'DateTime'>
  readonly isBooked: Prisma.FieldRef<"AvailableSlot", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"AvailableSlot", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AvailableSlot", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AvailableSlot findUnique
 */
export type AvailableSlotFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailableSlot
   */
  select?: Prisma.AvailableSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvailableSlot
   */
  omit?: Prisma.AvailableSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvailableSlotInclude<ExtArgs> | null
  /**
   * Filter, which AvailableSlot to fetch.
   */
  where: Prisma.AvailableSlotWhereUniqueInput
}

/**
 * AvailableSlot findUniqueOrThrow
 */
export type AvailableSlotFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailableSlot
   */
  select?: Prisma.AvailableSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvailableSlot
   */
  omit?: Prisma.AvailableSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvailableSlotInclude<ExtArgs> | null
  /**
   * Filter, which AvailableSlot to fetch.
   */
  where: Prisma.AvailableSlotWhereUniqueInput
}

/**
 * AvailableSlot findFirst
 */
export type AvailableSlotFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailableSlot
   */
  select?: Prisma.AvailableSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvailableSlot
   */
  omit?: Prisma.AvailableSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvailableSlotInclude<ExtArgs> | null
  /**
   * Filter, which AvailableSlot to fetch.
   */
  where?: Prisma.AvailableSlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AvailableSlots to fetch.
   */
  orderBy?: Prisma.AvailableSlotOrderByWithRelationInput | Prisma.AvailableSlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AvailableSlots.
   */
  cursor?: Prisma.AvailableSlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AvailableSlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AvailableSlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AvailableSlots.
   */
  distinct?: Prisma.AvailableSlotScalarFieldEnum | Prisma.AvailableSlotScalarFieldEnum[]
}

/**
 * AvailableSlot findFirstOrThrow
 */
export type AvailableSlotFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailableSlot
   */
  select?: Prisma.AvailableSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvailableSlot
   */
  omit?: Prisma.AvailableSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvailableSlotInclude<ExtArgs> | null
  /**
   * Filter, which AvailableSlot to fetch.
   */
  where?: Prisma.AvailableSlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AvailableSlots to fetch.
   */
  orderBy?: Prisma.AvailableSlotOrderByWithRelationInput | Prisma.AvailableSlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AvailableSlots.
   */
  cursor?: Prisma.AvailableSlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AvailableSlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AvailableSlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AvailableSlots.
   */
  distinct?: Prisma.AvailableSlotScalarFieldEnum | Prisma.AvailableSlotScalarFieldEnum[]
}

/**
 * AvailableSlot findMany
 */
export type AvailableSlotFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailableSlot
   */
  select?: Prisma.AvailableSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvailableSlot
   */
  omit?: Prisma.AvailableSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvailableSlotInclude<ExtArgs> | null
  /**
   * Filter, which AvailableSlots to fetch.
   */
  where?: Prisma.AvailableSlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AvailableSlots to fetch.
   */
  orderBy?: Prisma.AvailableSlotOrderByWithRelationInput | Prisma.AvailableSlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AvailableSlots.
   */
  cursor?: Prisma.AvailableSlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AvailableSlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AvailableSlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AvailableSlots.
   */
  distinct?: Prisma.AvailableSlotScalarFieldEnum | Prisma.AvailableSlotScalarFieldEnum[]
}

/**
 * AvailableSlot create
 */
export type AvailableSlotCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailableSlot
   */
  select?: Prisma.AvailableSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvailableSlot
   */
  omit?: Prisma.AvailableSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvailableSlotInclude<ExtArgs> | null
  /**
   * The data needed to create a AvailableSlot.
   */
  data: Prisma.XOR<Prisma.AvailableSlotCreateInput, Prisma.AvailableSlotUncheckedCreateInput>
}

/**
 * AvailableSlot createMany
 */
export type AvailableSlotCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AvailableSlots.
   */
  data: Prisma.AvailableSlotCreateManyInput | Prisma.AvailableSlotCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AvailableSlot createManyAndReturn
 */
export type AvailableSlotCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailableSlot
   */
  select?: Prisma.AvailableSlotSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AvailableSlot
   */
  omit?: Prisma.AvailableSlotOmit<ExtArgs> | null
  /**
   * The data used to create many AvailableSlots.
   */
  data: Prisma.AvailableSlotCreateManyInput | Prisma.AvailableSlotCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvailableSlotIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AvailableSlot update
 */
export type AvailableSlotUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailableSlot
   */
  select?: Prisma.AvailableSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvailableSlot
   */
  omit?: Prisma.AvailableSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvailableSlotInclude<ExtArgs> | null
  /**
   * The data needed to update a AvailableSlot.
   */
  data: Prisma.XOR<Prisma.AvailableSlotUpdateInput, Prisma.AvailableSlotUncheckedUpdateInput>
  /**
   * Choose, which AvailableSlot to update.
   */
  where: Prisma.AvailableSlotWhereUniqueInput
}

/**
 * AvailableSlot updateMany
 */
export type AvailableSlotUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AvailableSlots.
   */
  data: Prisma.XOR<Prisma.AvailableSlotUpdateManyMutationInput, Prisma.AvailableSlotUncheckedUpdateManyInput>
  /**
   * Filter which AvailableSlots to update
   */
  where?: Prisma.AvailableSlotWhereInput
  /**
   * Limit how many AvailableSlots to update.
   */
  limit?: number
}

/**
 * AvailableSlot updateManyAndReturn
 */
export type AvailableSlotUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailableSlot
   */
  select?: Prisma.AvailableSlotSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AvailableSlot
   */
  omit?: Prisma.AvailableSlotOmit<ExtArgs> | null
  /**
   * The data used to update AvailableSlots.
   */
  data: Prisma.XOR<Prisma.AvailableSlotUpdateManyMutationInput, Prisma.AvailableSlotUncheckedUpdateManyInput>
  /**
   * Filter which AvailableSlots to update
   */
  where?: Prisma.AvailableSlotWhereInput
  /**
   * Limit how many AvailableSlots to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvailableSlotIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AvailableSlot upsert
 */
export type AvailableSlotUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailableSlot
   */
  select?: Prisma.AvailableSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvailableSlot
   */
  omit?: Prisma.AvailableSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvailableSlotInclude<ExtArgs> | null
  /**
   * The filter to search for the AvailableSlot to update in case it exists.
   */
  where: Prisma.AvailableSlotWhereUniqueInput
  /**
   * In case the AvailableSlot found by the `where` argument doesn't exist, create a new AvailableSlot with this data.
   */
  create: Prisma.XOR<Prisma.AvailableSlotCreateInput, Prisma.AvailableSlotUncheckedCreateInput>
  /**
   * In case the AvailableSlot was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AvailableSlotUpdateInput, Prisma.AvailableSlotUncheckedUpdateInput>
}

/**
 * AvailableSlot delete
 */
export type AvailableSlotDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailableSlot
   */
  select?: Prisma.AvailableSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvailableSlot
   */
  omit?: Prisma.AvailableSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvailableSlotInclude<ExtArgs> | null
  /**
   * Filter which AvailableSlot to delete.
   */
  where: Prisma.AvailableSlotWhereUniqueInput
}

/**
 * AvailableSlot deleteMany
 */
export type AvailableSlotDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AvailableSlots to delete
   */
  where?: Prisma.AvailableSlotWhereInput
  /**
   * Limit how many AvailableSlots to delete.
   */
  limit?: number
}

/**
 * AvailableSlot.sessions
 */
export type AvailableSlot$sessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConversationSession
   */
  select?: Prisma.ConversationSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConversationSession
   */
  omit?: Prisma.ConversationSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConversationSessionInclude<ExtArgs> | null
  where?: Prisma.ConversationSessionWhereInput
  orderBy?: Prisma.ConversationSessionOrderByWithRelationInput | Prisma.ConversationSessionOrderByWithRelationInput[]
  cursor?: Prisma.ConversationSessionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ConversationSessionScalarFieldEnum | Prisma.ConversationSessionScalarFieldEnum[]
}

/**
 * AvailableSlot without action
 */
export type AvailableSlotDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailableSlot
   */
  select?: Prisma.AvailableSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvailableSlot
   */
  omit?: Prisma.AvailableSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvailableSlotInclude<ExtArgs> | null
}
