
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ClinicSettings` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ClinicSettings
 * 
 */
export type ClinicSettingsModel = runtime.Types.Result.DefaultSelection<Prisma.$ClinicSettingsPayload>

export type AggregateClinicSettings = {
  _count: ClinicSettingsCountAggregateOutputType | null
  _avg: ClinicSettingsAvgAggregateOutputType | null
  _sum: ClinicSettingsSumAggregateOutputType | null
  _min: ClinicSettingsMinAggregateOutputType | null
  _max: ClinicSettingsMaxAggregateOutputType | null
}

export type ClinicSettingsAvgAggregateOutputType = {
  appointmentBufferMinutes: number | null
  maxAdvanceBookingDays: number | null
}

export type ClinicSettingsSumAggregateOutputType = {
  appointmentBufferMinutes: number | null
  maxAdvanceBookingDays: number | null
}

export type ClinicSettingsMinAggregateOutputType = {
  id: string | null
  clinicId: string | null
  appointmentBufferMinutes: number | null
  maxAdvanceBookingDays: number | null
  timezone: string | null
  currency: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ClinicSettingsMaxAggregateOutputType = {
  id: string | null
  clinicId: string | null
  appointmentBufferMinutes: number | null
  maxAdvanceBookingDays: number | null
  timezone: string | null
  currency: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ClinicSettingsCountAggregateOutputType = {
  id: number
  clinicId: number
  appointmentBufferMinutes: number
  maxAdvanceBookingDays: number
  timezone: number
  currency: number
  workingHours: number
  reminderSettings: number
  notificationSettings: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ClinicSettingsAvgAggregateInputType = {
  appointmentBufferMinutes?: true
  maxAdvanceBookingDays?: true
}

export type ClinicSettingsSumAggregateInputType = {
  appointmentBufferMinutes?: true
  maxAdvanceBookingDays?: true
}

export type ClinicSettingsMinAggregateInputType = {
  id?: true
  clinicId?: true
  appointmentBufferMinutes?: true
  maxAdvanceBookingDays?: true
  timezone?: true
  currency?: true
  createdAt?: true
  updatedAt?: true
}

export type ClinicSettingsMaxAggregateInputType = {
  id?: true
  clinicId?: true
  appointmentBufferMinutes?: true
  maxAdvanceBookingDays?: true
  timezone?: true
  currency?: true
  createdAt?: true
  updatedAt?: true
}

export type ClinicSettingsCountAggregateInputType = {
  id?: true
  clinicId?: true
  appointmentBufferMinutes?: true
  maxAdvanceBookingDays?: true
  timezone?: true
  currency?: true
  workingHours?: true
  reminderSettings?: true
  notificationSettings?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ClinicSettingsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ClinicSettings to aggregate.
   */
  where?: Prisma.ClinicSettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClinicSettings to fetch.
   */
  orderBy?: Prisma.ClinicSettingsOrderByWithRelationInput | Prisma.ClinicSettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ClinicSettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClinicSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClinicSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ClinicSettings
  **/
  _count?: true | ClinicSettingsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ClinicSettingsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ClinicSettingsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ClinicSettingsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ClinicSettingsMaxAggregateInputType
}

export type GetClinicSettingsAggregateType<T extends ClinicSettingsAggregateArgs> = {
      [P in keyof T & keyof AggregateClinicSettings]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateClinicSettings[P]>
    : Prisma.GetScalarType<T[P], AggregateClinicSettings[P]>
}




export type ClinicSettingsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ClinicSettingsWhereInput
  orderBy?: Prisma.ClinicSettingsOrderByWithAggregationInput | Prisma.ClinicSettingsOrderByWithAggregationInput[]
  by: Prisma.ClinicSettingsScalarFieldEnum[] | Prisma.ClinicSettingsScalarFieldEnum
  having?: Prisma.ClinicSettingsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ClinicSettingsCountAggregateInputType | true
  _avg?: ClinicSettingsAvgAggregateInputType
  _sum?: ClinicSettingsSumAggregateInputType
  _min?: ClinicSettingsMinAggregateInputType
  _max?: ClinicSettingsMaxAggregateInputType
}

export type ClinicSettingsGroupByOutputType = {
  id: string
  clinicId: string
  appointmentBufferMinutes: number
  maxAdvanceBookingDays: number
  timezone: string | null
  currency: string
  workingHours: runtime.JsonValue | null
  reminderSettings: runtime.JsonValue | null
  notificationSettings: runtime.JsonValue | null
  createdAt: Date
  updatedAt: Date
  _count: ClinicSettingsCountAggregateOutputType | null
  _avg: ClinicSettingsAvgAggregateOutputType | null
  _sum: ClinicSettingsSumAggregateOutputType | null
  _min: ClinicSettingsMinAggregateOutputType | null
  _max: ClinicSettingsMaxAggregateOutputType | null
}

export type GetClinicSettingsGroupByPayload<T extends ClinicSettingsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ClinicSettingsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ClinicSettingsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ClinicSettingsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ClinicSettingsGroupByOutputType[P]>
      }
    >
  >



export type ClinicSettingsWhereInput = {
  AND?: Prisma.ClinicSettingsWhereInput | Prisma.ClinicSettingsWhereInput[]
  OR?: Prisma.ClinicSettingsWhereInput[]
  NOT?: Prisma.ClinicSettingsWhereInput | Prisma.ClinicSettingsWhereInput[]
  id?: Prisma.StringFilter<"ClinicSettings"> | string
  clinicId?: Prisma.StringFilter<"ClinicSettings"> | string
  appointmentBufferMinutes?: Prisma.IntFilter<"ClinicSettings"> | number
  maxAdvanceBookingDays?: Prisma.IntFilter<"ClinicSettings"> | number
  timezone?: Prisma.StringNullableFilter<"ClinicSettings"> | string | null
  currency?: Prisma.StringFilter<"ClinicSettings"> | string
  workingHours?: Prisma.JsonNullableFilter<"ClinicSettings">
  reminderSettings?: Prisma.JsonNullableFilter<"ClinicSettings">
  notificationSettings?: Prisma.JsonNullableFilter<"ClinicSettings">
  createdAt?: Prisma.DateTimeFilter<"ClinicSettings"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ClinicSettings"> | Date | string
  clinic?: Prisma.XOR<Prisma.ClinicScalarRelationFilter, Prisma.ClinicWhereInput>
}

export type ClinicSettingsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  clinicId?: Prisma.SortOrder
  appointmentBufferMinutes?: Prisma.SortOrder
  maxAdvanceBookingDays?: Prisma.SortOrder
  timezone?: Prisma.SortOrderInput | Prisma.SortOrder
  currency?: Prisma.SortOrder
  workingHours?: Prisma.SortOrderInput | Prisma.SortOrder
  reminderSettings?: Prisma.SortOrderInput | Prisma.SortOrder
  notificationSettings?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  clinic?: Prisma.ClinicOrderByWithRelationInput
}

export type ClinicSettingsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  clinicId?: string
  AND?: Prisma.ClinicSettingsWhereInput | Prisma.ClinicSettingsWhereInput[]
  OR?: Prisma.ClinicSettingsWhereInput[]
  NOT?: Prisma.ClinicSettingsWhereInput | Prisma.ClinicSettingsWhereInput[]
  appointmentBufferMinutes?: Prisma.IntFilter<"ClinicSettings"> | number
  maxAdvanceBookingDays?: Prisma.IntFilter<"ClinicSettings"> | number
  timezone?: Prisma.StringNullableFilter<"ClinicSettings"> | string | null
  currency?: Prisma.StringFilter<"ClinicSettings"> | string
  workingHours?: Prisma.JsonNullableFilter<"ClinicSettings">
  reminderSettings?: Prisma.JsonNullableFilter<"ClinicSettings">
  notificationSettings?: Prisma.JsonNullableFilter<"ClinicSettings">
  createdAt?: Prisma.DateTimeFilter<"ClinicSettings"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ClinicSettings"> | Date | string
  clinic?: Prisma.XOR<Prisma.ClinicScalarRelationFilter, Prisma.ClinicWhereInput>
}, "id" | "clinicId">

export type ClinicSettingsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  clinicId?: Prisma.SortOrder
  appointmentBufferMinutes?: Prisma.SortOrder
  maxAdvanceBookingDays?: Prisma.SortOrder
  timezone?: Prisma.SortOrderInput | Prisma.SortOrder
  currency?: Prisma.SortOrder
  workingHours?: Prisma.SortOrderInput | Prisma.SortOrder
  reminderSettings?: Prisma.SortOrderInput | Prisma.SortOrder
  notificationSettings?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ClinicSettingsCountOrderByAggregateInput
  _avg?: Prisma.ClinicSettingsAvgOrderByAggregateInput
  _max?: Prisma.ClinicSettingsMaxOrderByAggregateInput
  _min?: Prisma.ClinicSettingsMinOrderByAggregateInput
  _sum?: Prisma.ClinicSettingsSumOrderByAggregateInput
}

export type ClinicSettingsScalarWhereWithAggregatesInput = {
  AND?: Prisma.ClinicSettingsScalarWhereWithAggregatesInput | Prisma.ClinicSettingsScalarWhereWithAggregatesInput[]
  OR?: Prisma.ClinicSettingsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ClinicSettingsScalarWhereWithAggregatesInput | Prisma.ClinicSettingsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ClinicSettings"> | string
  clinicId?: Prisma.StringWithAggregatesFilter<"ClinicSettings"> | string
  appointmentBufferMinutes?: Prisma.IntWithAggregatesFilter<"ClinicSettings"> | number
  maxAdvanceBookingDays?: Prisma.IntWithAggregatesFilter<"ClinicSettings"> | number
  timezone?: Prisma.StringNullableWithAggregatesFilter<"ClinicSettings"> | string | null
  currency?: Prisma.StringWithAggregatesFilter<"ClinicSettings"> | string
  workingHours?: Prisma.JsonNullableWithAggregatesFilter<"ClinicSettings">
  reminderSettings?: Prisma.JsonNullableWithAggregatesFilter<"ClinicSettings">
  notificationSettings?: Prisma.JsonNullableWithAggregatesFilter<"ClinicSettings">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ClinicSettings"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ClinicSettings"> | Date | string
}

export type ClinicSettingsCreateInput = {
  id?: string
  appointmentBufferMinutes?: number
  maxAdvanceBookingDays?: number
  timezone?: string | null
  currency?: string
  workingHours?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  reminderSettings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  notificationSettings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  clinic: Prisma.ClinicCreateNestedOneWithoutClinicSettingsInput
}

export type ClinicSettingsUncheckedCreateInput = {
  id?: string
  clinicId: string
  appointmentBufferMinutes?: number
  maxAdvanceBookingDays?: number
  timezone?: string | null
  currency?: string
  workingHours?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  reminderSettings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  notificationSettings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ClinicSettingsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appointmentBufferMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  maxAdvanceBookingDays?: Prisma.IntFieldUpdateOperationsInput | number
  timezone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  workingHours?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  reminderSettings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  notificationSettings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  clinic?: Prisma.ClinicUpdateOneRequiredWithoutClinicSettingsNestedInput
}

export type ClinicSettingsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clinicId?: Prisma.StringFieldUpdateOperationsInput | string
  appointmentBufferMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  maxAdvanceBookingDays?: Prisma.IntFieldUpdateOperationsInput | number
  timezone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  workingHours?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  reminderSettings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  notificationSettings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ClinicSettingsCreateManyInput = {
  id?: string
  clinicId: string
  appointmentBufferMinutes?: number
  maxAdvanceBookingDays?: number
  timezone?: string | null
  currency?: string
  workingHours?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  reminderSettings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  notificationSettings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ClinicSettingsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appointmentBufferMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  maxAdvanceBookingDays?: Prisma.IntFieldUpdateOperationsInput | number
  timezone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  workingHours?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  reminderSettings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  notificationSettings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ClinicSettingsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clinicId?: Prisma.StringFieldUpdateOperationsInput | string
  appointmentBufferMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  maxAdvanceBookingDays?: Prisma.IntFieldUpdateOperationsInput | number
  timezone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  workingHours?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  reminderSettings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  notificationSettings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ClinicSettingsNullableScalarRelationFilter = {
  is?: Prisma.ClinicSettingsWhereInput | null
  isNot?: Prisma.ClinicSettingsWhereInput | null
}

export type ClinicSettingsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clinicId?: Prisma.SortOrder
  appointmentBufferMinutes?: Prisma.SortOrder
  maxAdvanceBookingDays?: Prisma.SortOrder
  timezone?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  workingHours?: Prisma.SortOrder
  reminderSettings?: Prisma.SortOrder
  notificationSettings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ClinicSettingsAvgOrderByAggregateInput = {
  appointmentBufferMinutes?: Prisma.SortOrder
  maxAdvanceBookingDays?: Prisma.SortOrder
}

export type ClinicSettingsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clinicId?: Prisma.SortOrder
  appointmentBufferMinutes?: Prisma.SortOrder
  maxAdvanceBookingDays?: Prisma.SortOrder
  timezone?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ClinicSettingsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clinicId?: Prisma.SortOrder
  appointmentBufferMinutes?: Prisma.SortOrder
  maxAdvanceBookingDays?: Prisma.SortOrder
  timezone?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ClinicSettingsSumOrderByAggregateInput = {
  appointmentBufferMinutes?: Prisma.SortOrder
  maxAdvanceBookingDays?: Prisma.SortOrder
}

export type ClinicSettingsCreateNestedOneWithoutClinicInput = {
  create?: Prisma.XOR<Prisma.ClinicSettingsCreateWithoutClinicInput, Prisma.ClinicSettingsUncheckedCreateWithoutClinicInput>
  connectOrCreate?: Prisma.ClinicSettingsCreateOrConnectWithoutClinicInput
  connect?: Prisma.ClinicSettingsWhereUniqueInput
}

export type ClinicSettingsUncheckedCreateNestedOneWithoutClinicInput = {
  create?: Prisma.XOR<Prisma.ClinicSettingsCreateWithoutClinicInput, Prisma.ClinicSettingsUncheckedCreateWithoutClinicInput>
  connectOrCreate?: Prisma.ClinicSettingsCreateOrConnectWithoutClinicInput
  connect?: Prisma.ClinicSettingsWhereUniqueInput
}

export type ClinicSettingsUpdateOneWithoutClinicNestedInput = {
  create?: Prisma.XOR<Prisma.ClinicSettingsCreateWithoutClinicInput, Prisma.ClinicSettingsUncheckedCreateWithoutClinicInput>
  connectOrCreate?: Prisma.ClinicSettingsCreateOrConnectWithoutClinicInput
  upsert?: Prisma.ClinicSettingsUpsertWithoutClinicInput
  disconnect?: Prisma.ClinicSettingsWhereInput | boolean
  delete?: Prisma.ClinicSettingsWhereInput | boolean
  connect?: Prisma.ClinicSettingsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ClinicSettingsUpdateToOneWithWhereWithoutClinicInput, Prisma.ClinicSettingsUpdateWithoutClinicInput>, Prisma.ClinicSettingsUncheckedUpdateWithoutClinicInput>
}

export type ClinicSettingsUncheckedUpdateOneWithoutClinicNestedInput = {
  create?: Prisma.XOR<Prisma.ClinicSettingsCreateWithoutClinicInput, Prisma.ClinicSettingsUncheckedCreateWithoutClinicInput>
  connectOrCreate?: Prisma.ClinicSettingsCreateOrConnectWithoutClinicInput
  upsert?: Prisma.ClinicSettingsUpsertWithoutClinicInput
  disconnect?: Prisma.ClinicSettingsWhereInput | boolean
  delete?: Prisma.ClinicSettingsWhereInput | boolean
  connect?: Prisma.ClinicSettingsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ClinicSettingsUpdateToOneWithWhereWithoutClinicInput, Prisma.ClinicSettingsUpdateWithoutClinicInput>, Prisma.ClinicSettingsUncheckedUpdateWithoutClinicInput>
}

export type ClinicSettingsCreateWithoutClinicInput = {
  id?: string
  appointmentBufferMinutes?: number
  maxAdvanceBookingDays?: number
  timezone?: string | null
  currency?: string
  workingHours?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  reminderSettings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  notificationSettings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ClinicSettingsUncheckedCreateWithoutClinicInput = {
  id?: string
  appointmentBufferMinutes?: number
  maxAdvanceBookingDays?: number
  timezone?: string | null
  currency?: string
  workingHours?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  reminderSettings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  notificationSettings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ClinicSettingsCreateOrConnectWithoutClinicInput = {
  where: Prisma.ClinicSettingsWhereUniqueInput
  create: Prisma.XOR<Prisma.ClinicSettingsCreateWithoutClinicInput, Prisma.ClinicSettingsUncheckedCreateWithoutClinicInput>
}

export type ClinicSettingsUpsertWithoutClinicInput = {
  update: Prisma.XOR<Prisma.ClinicSettingsUpdateWithoutClinicInput, Prisma.ClinicSettingsUncheckedUpdateWithoutClinicInput>
  create: Prisma.XOR<Prisma.ClinicSettingsCreateWithoutClinicInput, Prisma.ClinicSettingsUncheckedCreateWithoutClinicInput>
  where?: Prisma.ClinicSettingsWhereInput
}

export type ClinicSettingsUpdateToOneWithWhereWithoutClinicInput = {
  where?: Prisma.ClinicSettingsWhereInput
  data: Prisma.XOR<Prisma.ClinicSettingsUpdateWithoutClinicInput, Prisma.ClinicSettingsUncheckedUpdateWithoutClinicInput>
}

export type ClinicSettingsUpdateWithoutClinicInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appointmentBufferMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  maxAdvanceBookingDays?: Prisma.IntFieldUpdateOperationsInput | number
  timezone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  workingHours?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  reminderSettings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  notificationSettings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ClinicSettingsUncheckedUpdateWithoutClinicInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appointmentBufferMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  maxAdvanceBookingDays?: Prisma.IntFieldUpdateOperationsInput | number
  timezone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  workingHours?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  reminderSettings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  notificationSettings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ClinicSettingsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clinicId?: boolean
  appointmentBufferMinutes?: boolean
  maxAdvanceBookingDays?: boolean
  timezone?: boolean
  currency?: boolean
  workingHours?: boolean
  reminderSettings?: boolean
  notificationSettings?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  clinic?: boolean | Prisma.ClinicDefaultArgs<ExtArgs>
}, ExtArgs["result"]["clinicSettings"]>

export type ClinicSettingsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clinicId?: boolean
  appointmentBufferMinutes?: boolean
  maxAdvanceBookingDays?: boolean
  timezone?: boolean
  currency?: boolean
  workingHours?: boolean
  reminderSettings?: boolean
  notificationSettings?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  clinic?: boolean | Prisma.ClinicDefaultArgs<ExtArgs>
}, ExtArgs["result"]["clinicSettings"]>

export type ClinicSettingsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clinicId?: boolean
  appointmentBufferMinutes?: boolean
  maxAdvanceBookingDays?: boolean
  timezone?: boolean
  currency?: boolean
  workingHours?: boolean
  reminderSettings?: boolean
  notificationSettings?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  clinic?: boolean | Prisma.ClinicDefaultArgs<ExtArgs>
}, ExtArgs["result"]["clinicSettings"]>

export type ClinicSettingsSelectScalar = {
  id?: boolean
  clinicId?: boolean
  appointmentBufferMinutes?: boolean
  maxAdvanceBookingDays?: boolean
  timezone?: boolean
  currency?: boolean
  workingHours?: boolean
  reminderSettings?: boolean
  notificationSettings?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ClinicSettingsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "clinicId" | "appointmentBufferMinutes" | "maxAdvanceBookingDays" | "timezone" | "currency" | "workingHours" | "reminderSettings" | "notificationSettings" | "createdAt" | "updatedAt", ExtArgs["result"]["clinicSettings"]>
export type ClinicSettingsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  clinic?: boolean | Prisma.ClinicDefaultArgs<ExtArgs>
}
export type ClinicSettingsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  clinic?: boolean | Prisma.ClinicDefaultArgs<ExtArgs>
}
export type ClinicSettingsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  clinic?: boolean | Prisma.ClinicDefaultArgs<ExtArgs>
}

export type $ClinicSettingsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ClinicSettings"
  objects: {
    clinic: Prisma.$ClinicPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    clinicId: string
    appointmentBufferMinutes: number
    maxAdvanceBookingDays: number
    timezone: string | null
    currency: string
    workingHours: runtime.JsonValue | null
    reminderSettings: runtime.JsonValue | null
    notificationSettings: runtime.JsonValue | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["clinicSettings"]>
  composites: {}
}

export type ClinicSettingsGetPayload<S extends boolean | null | undefined | ClinicSettingsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ClinicSettingsPayload, S>

export type ClinicSettingsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ClinicSettingsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ClinicSettingsCountAggregateInputType | true
  }

export interface ClinicSettingsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ClinicSettings'], meta: { name: 'ClinicSettings' } }
  /**
   * Find zero or one ClinicSettings that matches the filter.
   * @param {ClinicSettingsFindUniqueArgs} args - Arguments to find a ClinicSettings
   * @example
   * // Get one ClinicSettings
   * const clinicSettings = await prisma.clinicSettings.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ClinicSettingsFindUniqueArgs>(args: Prisma.SelectSubset<T, ClinicSettingsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ClinicSettingsClient<runtime.Types.Result.GetResult<Prisma.$ClinicSettingsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ClinicSettings that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ClinicSettingsFindUniqueOrThrowArgs} args - Arguments to find a ClinicSettings
   * @example
   * // Get one ClinicSettings
   * const clinicSettings = await prisma.clinicSettings.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ClinicSettingsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ClinicSettingsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClinicSettingsClient<runtime.Types.Result.GetResult<Prisma.$ClinicSettingsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ClinicSettings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClinicSettingsFindFirstArgs} args - Arguments to find a ClinicSettings
   * @example
   * // Get one ClinicSettings
   * const clinicSettings = await prisma.clinicSettings.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ClinicSettingsFindFirstArgs>(args?: Prisma.SelectSubset<T, ClinicSettingsFindFirstArgs<ExtArgs>>): Prisma.Prisma__ClinicSettingsClient<runtime.Types.Result.GetResult<Prisma.$ClinicSettingsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ClinicSettings that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClinicSettingsFindFirstOrThrowArgs} args - Arguments to find a ClinicSettings
   * @example
   * // Get one ClinicSettings
   * const clinicSettings = await prisma.clinicSettings.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ClinicSettingsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ClinicSettingsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClinicSettingsClient<runtime.Types.Result.GetResult<Prisma.$ClinicSettingsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ClinicSettings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClinicSettingsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ClinicSettings
   * const clinicSettings = await prisma.clinicSettings.findMany()
   * 
   * // Get first 10 ClinicSettings
   * const clinicSettings = await prisma.clinicSettings.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const clinicSettingsWithIdOnly = await prisma.clinicSettings.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ClinicSettingsFindManyArgs>(args?: Prisma.SelectSubset<T, ClinicSettingsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClinicSettingsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ClinicSettings.
   * @param {ClinicSettingsCreateArgs} args - Arguments to create a ClinicSettings.
   * @example
   * // Create one ClinicSettings
   * const ClinicSettings = await prisma.clinicSettings.create({
   *   data: {
   *     // ... data to create a ClinicSettings
   *   }
   * })
   * 
   */
  create<T extends ClinicSettingsCreateArgs>(args: Prisma.SelectSubset<T, ClinicSettingsCreateArgs<ExtArgs>>): Prisma.Prisma__ClinicSettingsClient<runtime.Types.Result.GetResult<Prisma.$ClinicSettingsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ClinicSettings.
   * @param {ClinicSettingsCreateManyArgs} args - Arguments to create many ClinicSettings.
   * @example
   * // Create many ClinicSettings
   * const clinicSettings = await prisma.clinicSettings.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ClinicSettingsCreateManyArgs>(args?: Prisma.SelectSubset<T, ClinicSettingsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ClinicSettings and returns the data saved in the database.
   * @param {ClinicSettingsCreateManyAndReturnArgs} args - Arguments to create many ClinicSettings.
   * @example
   * // Create many ClinicSettings
   * const clinicSettings = await prisma.clinicSettings.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ClinicSettings and only return the `id`
   * const clinicSettingsWithIdOnly = await prisma.clinicSettings.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ClinicSettingsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ClinicSettingsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClinicSettingsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ClinicSettings.
   * @param {ClinicSettingsDeleteArgs} args - Arguments to delete one ClinicSettings.
   * @example
   * // Delete one ClinicSettings
   * const ClinicSettings = await prisma.clinicSettings.delete({
   *   where: {
   *     // ... filter to delete one ClinicSettings
   *   }
   * })
   * 
   */
  delete<T extends ClinicSettingsDeleteArgs>(args: Prisma.SelectSubset<T, ClinicSettingsDeleteArgs<ExtArgs>>): Prisma.Prisma__ClinicSettingsClient<runtime.Types.Result.GetResult<Prisma.$ClinicSettingsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ClinicSettings.
   * @param {ClinicSettingsUpdateArgs} args - Arguments to update one ClinicSettings.
   * @example
   * // Update one ClinicSettings
   * const clinicSettings = await prisma.clinicSettings.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ClinicSettingsUpdateArgs>(args: Prisma.SelectSubset<T, ClinicSettingsUpdateArgs<ExtArgs>>): Prisma.Prisma__ClinicSettingsClient<runtime.Types.Result.GetResult<Prisma.$ClinicSettingsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ClinicSettings.
   * @param {ClinicSettingsDeleteManyArgs} args - Arguments to filter ClinicSettings to delete.
   * @example
   * // Delete a few ClinicSettings
   * const { count } = await prisma.clinicSettings.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ClinicSettingsDeleteManyArgs>(args?: Prisma.SelectSubset<T, ClinicSettingsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ClinicSettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClinicSettingsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ClinicSettings
   * const clinicSettings = await prisma.clinicSettings.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ClinicSettingsUpdateManyArgs>(args: Prisma.SelectSubset<T, ClinicSettingsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ClinicSettings and returns the data updated in the database.
   * @param {ClinicSettingsUpdateManyAndReturnArgs} args - Arguments to update many ClinicSettings.
   * @example
   * // Update many ClinicSettings
   * const clinicSettings = await prisma.clinicSettings.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ClinicSettings and only return the `id`
   * const clinicSettingsWithIdOnly = await prisma.clinicSettings.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ClinicSettingsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ClinicSettingsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClinicSettingsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ClinicSettings.
   * @param {ClinicSettingsUpsertArgs} args - Arguments to update or create a ClinicSettings.
   * @example
   * // Update or create a ClinicSettings
   * const clinicSettings = await prisma.clinicSettings.upsert({
   *   create: {
   *     // ... data to create a ClinicSettings
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ClinicSettings we want to update
   *   }
   * })
   */
  upsert<T extends ClinicSettingsUpsertArgs>(args: Prisma.SelectSubset<T, ClinicSettingsUpsertArgs<ExtArgs>>): Prisma.Prisma__ClinicSettingsClient<runtime.Types.Result.GetResult<Prisma.$ClinicSettingsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ClinicSettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClinicSettingsCountArgs} args - Arguments to filter ClinicSettings to count.
   * @example
   * // Count the number of ClinicSettings
   * const count = await prisma.clinicSettings.count({
   *   where: {
   *     // ... the filter for the ClinicSettings we want to count
   *   }
   * })
  **/
  count<T extends ClinicSettingsCountArgs>(
    args?: Prisma.Subset<T, ClinicSettingsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ClinicSettingsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ClinicSettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClinicSettingsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ClinicSettingsAggregateArgs>(args: Prisma.Subset<T, ClinicSettingsAggregateArgs>): Prisma.PrismaPromise<GetClinicSettingsAggregateType<T>>

  /**
   * Group by ClinicSettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClinicSettingsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ClinicSettingsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ClinicSettingsGroupByArgs['orderBy'] }
      : { orderBy?: ClinicSettingsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ClinicSettingsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetClinicSettingsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ClinicSettings model
 */
readonly fields: ClinicSettingsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ClinicSettings.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ClinicSettingsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  clinic<T extends Prisma.ClinicDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ClinicDefaultArgs<ExtArgs>>): Prisma.Prisma__ClinicClient<runtime.Types.Result.GetResult<Prisma.$ClinicPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ClinicSettings model
 */
export interface ClinicSettingsFieldRefs {
  readonly id: Prisma.FieldRef<"ClinicSettings", 'String'>
  readonly clinicId: Prisma.FieldRef<"ClinicSettings", 'String'>
  readonly appointmentBufferMinutes: Prisma.FieldRef<"ClinicSettings", 'Int'>
  readonly maxAdvanceBookingDays: Prisma.FieldRef<"ClinicSettings", 'Int'>
  readonly timezone: Prisma.FieldRef<"ClinicSettings", 'String'>
  readonly currency: Prisma.FieldRef<"ClinicSettings", 'String'>
  readonly workingHours: Prisma.FieldRef<"ClinicSettings", 'Json'>
  readonly reminderSettings: Prisma.FieldRef<"ClinicSettings", 'Json'>
  readonly notificationSettings: Prisma.FieldRef<"ClinicSettings", 'Json'>
  readonly createdAt: Prisma.FieldRef<"ClinicSettings", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ClinicSettings", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ClinicSettings findUnique
 */
export type ClinicSettingsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClinicSettings
   */
  select?: Prisma.ClinicSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClinicSettings
   */
  omit?: Prisma.ClinicSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClinicSettingsInclude<ExtArgs> | null
  /**
   * Filter, which ClinicSettings to fetch.
   */
  where: Prisma.ClinicSettingsWhereUniqueInput
}

/**
 * ClinicSettings findUniqueOrThrow
 */
export type ClinicSettingsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClinicSettings
   */
  select?: Prisma.ClinicSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClinicSettings
   */
  omit?: Prisma.ClinicSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClinicSettingsInclude<ExtArgs> | null
  /**
   * Filter, which ClinicSettings to fetch.
   */
  where: Prisma.ClinicSettingsWhereUniqueInput
}

/**
 * ClinicSettings findFirst
 */
export type ClinicSettingsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClinicSettings
   */
  select?: Prisma.ClinicSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClinicSettings
   */
  omit?: Prisma.ClinicSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClinicSettingsInclude<ExtArgs> | null
  /**
   * Filter, which ClinicSettings to fetch.
   */
  where?: Prisma.ClinicSettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClinicSettings to fetch.
   */
  orderBy?: Prisma.ClinicSettingsOrderByWithRelationInput | Prisma.ClinicSettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ClinicSettings.
   */
  cursor?: Prisma.ClinicSettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClinicSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClinicSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ClinicSettings.
   */
  distinct?: Prisma.ClinicSettingsScalarFieldEnum | Prisma.ClinicSettingsScalarFieldEnum[]
}

/**
 * ClinicSettings findFirstOrThrow
 */
export type ClinicSettingsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClinicSettings
   */
  select?: Prisma.ClinicSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClinicSettings
   */
  omit?: Prisma.ClinicSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClinicSettingsInclude<ExtArgs> | null
  /**
   * Filter, which ClinicSettings to fetch.
   */
  where?: Prisma.ClinicSettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClinicSettings to fetch.
   */
  orderBy?: Prisma.ClinicSettingsOrderByWithRelationInput | Prisma.ClinicSettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ClinicSettings.
   */
  cursor?: Prisma.ClinicSettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClinicSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClinicSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ClinicSettings.
   */
  distinct?: Prisma.ClinicSettingsScalarFieldEnum | Prisma.ClinicSettingsScalarFieldEnum[]
}

/**
 * ClinicSettings findMany
 */
export type ClinicSettingsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClinicSettings
   */
  select?: Prisma.ClinicSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClinicSettings
   */
  omit?: Prisma.ClinicSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClinicSettingsInclude<ExtArgs> | null
  /**
   * Filter, which ClinicSettings to fetch.
   */
  where?: Prisma.ClinicSettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClinicSettings to fetch.
   */
  orderBy?: Prisma.ClinicSettingsOrderByWithRelationInput | Prisma.ClinicSettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ClinicSettings.
   */
  cursor?: Prisma.ClinicSettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClinicSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClinicSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ClinicSettings.
   */
  distinct?: Prisma.ClinicSettingsScalarFieldEnum | Prisma.ClinicSettingsScalarFieldEnum[]
}

/**
 * ClinicSettings create
 */
export type ClinicSettingsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClinicSettings
   */
  select?: Prisma.ClinicSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClinicSettings
   */
  omit?: Prisma.ClinicSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClinicSettingsInclude<ExtArgs> | null
  /**
   * The data needed to create a ClinicSettings.
   */
  data: Prisma.XOR<Prisma.ClinicSettingsCreateInput, Prisma.ClinicSettingsUncheckedCreateInput>
}

/**
 * ClinicSettings createMany
 */
export type ClinicSettingsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ClinicSettings.
   */
  data: Prisma.ClinicSettingsCreateManyInput | Prisma.ClinicSettingsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ClinicSettings createManyAndReturn
 */
export type ClinicSettingsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClinicSettings
   */
  select?: Prisma.ClinicSettingsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ClinicSettings
   */
  omit?: Prisma.ClinicSettingsOmit<ExtArgs> | null
  /**
   * The data used to create many ClinicSettings.
   */
  data: Prisma.ClinicSettingsCreateManyInput | Prisma.ClinicSettingsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClinicSettingsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ClinicSettings update
 */
export type ClinicSettingsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClinicSettings
   */
  select?: Prisma.ClinicSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClinicSettings
   */
  omit?: Prisma.ClinicSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClinicSettingsInclude<ExtArgs> | null
  /**
   * The data needed to update a ClinicSettings.
   */
  data: Prisma.XOR<Prisma.ClinicSettingsUpdateInput, Prisma.ClinicSettingsUncheckedUpdateInput>
  /**
   * Choose, which ClinicSettings to update.
   */
  where: Prisma.ClinicSettingsWhereUniqueInput
}

/**
 * ClinicSettings updateMany
 */
export type ClinicSettingsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ClinicSettings.
   */
  data: Prisma.XOR<Prisma.ClinicSettingsUpdateManyMutationInput, Prisma.ClinicSettingsUncheckedUpdateManyInput>
  /**
   * Filter which ClinicSettings to update
   */
  where?: Prisma.ClinicSettingsWhereInput
  /**
   * Limit how many ClinicSettings to update.
   */
  limit?: number
}

/**
 * ClinicSettings updateManyAndReturn
 */
export type ClinicSettingsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClinicSettings
   */
  select?: Prisma.ClinicSettingsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ClinicSettings
   */
  omit?: Prisma.ClinicSettingsOmit<ExtArgs> | null
  /**
   * The data used to update ClinicSettings.
   */
  data: Prisma.XOR<Prisma.ClinicSettingsUpdateManyMutationInput, Prisma.ClinicSettingsUncheckedUpdateManyInput>
  /**
   * Filter which ClinicSettings to update
   */
  where?: Prisma.ClinicSettingsWhereInput
  /**
   * Limit how many ClinicSettings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClinicSettingsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ClinicSettings upsert
 */
export type ClinicSettingsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClinicSettings
   */
  select?: Prisma.ClinicSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClinicSettings
   */
  omit?: Prisma.ClinicSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClinicSettingsInclude<ExtArgs> | null
  /**
   * The filter to search for the ClinicSettings to update in case it exists.
   */
  where: Prisma.ClinicSettingsWhereUniqueInput
  /**
   * In case the ClinicSettings found by the `where` argument doesn't exist, create a new ClinicSettings with this data.
   */
  create: Prisma.XOR<Prisma.ClinicSettingsCreateInput, Prisma.ClinicSettingsUncheckedCreateInput>
  /**
   * In case the ClinicSettings was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ClinicSettingsUpdateInput, Prisma.ClinicSettingsUncheckedUpdateInput>
}

/**
 * ClinicSettings delete
 */
export type ClinicSettingsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClinicSettings
   */
  select?: Prisma.ClinicSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClinicSettings
   */
  omit?: Prisma.ClinicSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClinicSettingsInclude<ExtArgs> | null
  /**
   * Filter which ClinicSettings to delete.
   */
  where: Prisma.ClinicSettingsWhereUniqueInput
}

/**
 * ClinicSettings deleteMany
 */
export type ClinicSettingsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ClinicSettings to delete
   */
  where?: Prisma.ClinicSettingsWhereInput
  /**
   * Limit how many ClinicSettings to delete.
   */
  limit?: number
}

/**
 * ClinicSettings without action
 */
export type ClinicSettingsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClinicSettings
   */
  select?: Prisma.ClinicSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClinicSettings
   */
  omit?: Prisma.ClinicSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClinicSettingsInclude<ExtArgs> | null
}
