
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `EscalationLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model EscalationLog
 * 
 */
export type EscalationLogModel = runtime.Types.Result.DefaultSelection<Prisma.$EscalationLogPayload>

export type AggregateEscalationLog = {
  _count: EscalationLogCountAggregateOutputType | null
  _min: EscalationLogMinAggregateOutputType | null
  _max: EscalationLogMaxAggregateOutputType | null
}

export type EscalationLogMinAggregateOutputType = {
  id: string | null
  clinicId: string | null
  entityType: $Enums.EntityType | null
  entityId: string | null
  eventType: string | null
  severity: $Enums.Severity | null
  message: string | null
  userId: string | null
  createdAt: Date | null
}

export type EscalationLogMaxAggregateOutputType = {
  id: string | null
  clinicId: string | null
  entityType: $Enums.EntityType | null
  entityId: string | null
  eventType: string | null
  severity: $Enums.Severity | null
  message: string | null
  userId: string | null
  createdAt: Date | null
}

export type EscalationLogCountAggregateOutputType = {
  id: number
  clinicId: number
  entityType: number
  entityId: number
  eventType: number
  severity: number
  message: number
  metadata: number
  userId: number
  createdAt: number
  _all: number
}


export type EscalationLogMinAggregateInputType = {
  id?: true
  clinicId?: true
  entityType?: true
  entityId?: true
  eventType?: true
  severity?: true
  message?: true
  userId?: true
  createdAt?: true
}

export type EscalationLogMaxAggregateInputType = {
  id?: true
  clinicId?: true
  entityType?: true
  entityId?: true
  eventType?: true
  severity?: true
  message?: true
  userId?: true
  createdAt?: true
}

export type EscalationLogCountAggregateInputType = {
  id?: true
  clinicId?: true
  entityType?: true
  entityId?: true
  eventType?: true
  severity?: true
  message?: true
  metadata?: true
  userId?: true
  createdAt?: true
  _all?: true
}

export type EscalationLogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EscalationLog to aggregate.
   */
  where?: Prisma.EscalationLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EscalationLogs to fetch.
   */
  orderBy?: Prisma.EscalationLogOrderByWithRelationInput | Prisma.EscalationLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EscalationLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EscalationLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EscalationLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EscalationLogs
  **/
  _count?: true | EscalationLogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EscalationLogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EscalationLogMaxAggregateInputType
}

export type GetEscalationLogAggregateType<T extends EscalationLogAggregateArgs> = {
      [P in keyof T & keyof AggregateEscalationLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEscalationLog[P]>
    : Prisma.GetScalarType<T[P], AggregateEscalationLog[P]>
}




export type EscalationLogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EscalationLogWhereInput
  orderBy?: Prisma.EscalationLogOrderByWithAggregationInput | Prisma.EscalationLogOrderByWithAggregationInput[]
  by: Prisma.EscalationLogScalarFieldEnum[] | Prisma.EscalationLogScalarFieldEnum
  having?: Prisma.EscalationLogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EscalationLogCountAggregateInputType | true
  _min?: EscalationLogMinAggregateInputType
  _max?: EscalationLogMaxAggregateInputType
}

export type EscalationLogGroupByOutputType = {
  id: string
  clinicId: string
  entityType: $Enums.EntityType
  entityId: string
  eventType: string
  severity: $Enums.Severity
  message: string
  metadata: runtime.JsonValue | null
  userId: string | null
  createdAt: Date
  _count: EscalationLogCountAggregateOutputType | null
  _min: EscalationLogMinAggregateOutputType | null
  _max: EscalationLogMaxAggregateOutputType | null
}

export type GetEscalationLogGroupByPayload<T extends EscalationLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EscalationLogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EscalationLogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EscalationLogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EscalationLogGroupByOutputType[P]>
      }
    >
  >



export type EscalationLogWhereInput = {
  AND?: Prisma.EscalationLogWhereInput | Prisma.EscalationLogWhereInput[]
  OR?: Prisma.EscalationLogWhereInput[]
  NOT?: Prisma.EscalationLogWhereInput | Prisma.EscalationLogWhereInput[]
  id?: Prisma.StringFilter<"EscalationLog"> | string
  clinicId?: Prisma.StringFilter<"EscalationLog"> | string
  entityType?: Prisma.EnumEntityTypeFilter<"EscalationLog"> | $Enums.EntityType
  entityId?: Prisma.StringFilter<"EscalationLog"> | string
  eventType?: Prisma.StringFilter<"EscalationLog"> | string
  severity?: Prisma.EnumSeverityFilter<"EscalationLog"> | $Enums.Severity
  message?: Prisma.StringFilter<"EscalationLog"> | string
  metadata?: Prisma.JsonNullableFilter<"EscalationLog">
  userId?: Prisma.StringNullableFilter<"EscalationLog"> | string | null
  createdAt?: Prisma.DateTimeFilter<"EscalationLog"> | Date | string
  clinic?: Prisma.XOR<Prisma.ClinicScalarRelationFilter, Prisma.ClinicWhereInput>
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type EscalationLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  clinicId?: Prisma.SortOrder
  entityType?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  eventType?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  message?: Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  clinic?: Prisma.ClinicOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type EscalationLogWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.EscalationLogWhereInput | Prisma.EscalationLogWhereInput[]
  OR?: Prisma.EscalationLogWhereInput[]
  NOT?: Prisma.EscalationLogWhereInput | Prisma.EscalationLogWhereInput[]
  clinicId?: Prisma.StringFilter<"EscalationLog"> | string
  entityType?: Prisma.EnumEntityTypeFilter<"EscalationLog"> | $Enums.EntityType
  entityId?: Prisma.StringFilter<"EscalationLog"> | string
  eventType?: Prisma.StringFilter<"EscalationLog"> | string
  severity?: Prisma.EnumSeverityFilter<"EscalationLog"> | $Enums.Severity
  message?: Prisma.StringFilter<"EscalationLog"> | string
  metadata?: Prisma.JsonNullableFilter<"EscalationLog">
  userId?: Prisma.StringNullableFilter<"EscalationLog"> | string | null
  createdAt?: Prisma.DateTimeFilter<"EscalationLog"> | Date | string
  clinic?: Prisma.XOR<Prisma.ClinicScalarRelationFilter, Prisma.ClinicWhereInput>
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id">

export type EscalationLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  clinicId?: Prisma.SortOrder
  entityType?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  eventType?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  message?: Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.EscalationLogCountOrderByAggregateInput
  _max?: Prisma.EscalationLogMaxOrderByAggregateInput
  _min?: Prisma.EscalationLogMinOrderByAggregateInput
}

export type EscalationLogScalarWhereWithAggregatesInput = {
  AND?: Prisma.EscalationLogScalarWhereWithAggregatesInput | Prisma.EscalationLogScalarWhereWithAggregatesInput[]
  OR?: Prisma.EscalationLogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EscalationLogScalarWhereWithAggregatesInput | Prisma.EscalationLogScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"EscalationLog"> | string
  clinicId?: Prisma.StringWithAggregatesFilter<"EscalationLog"> | string
  entityType?: Prisma.EnumEntityTypeWithAggregatesFilter<"EscalationLog"> | $Enums.EntityType
  entityId?: Prisma.StringWithAggregatesFilter<"EscalationLog"> | string
  eventType?: Prisma.StringWithAggregatesFilter<"EscalationLog"> | string
  severity?: Prisma.EnumSeverityWithAggregatesFilter<"EscalationLog"> | $Enums.Severity
  message?: Prisma.StringWithAggregatesFilter<"EscalationLog"> | string
  metadata?: Prisma.JsonNullableWithAggregatesFilter<"EscalationLog">
  userId?: Prisma.StringNullableWithAggregatesFilter<"EscalationLog"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"EscalationLog"> | Date | string
}

export type EscalationLogCreateInput = {
  id?: string
  entityType: $Enums.EntityType
  entityId: string
  eventType: string
  severity: $Enums.Severity
  message: string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  clinic: Prisma.ClinicCreateNestedOneWithoutEscalationLogsInput
  user?: Prisma.UserCreateNestedOneWithoutEscalationLogsInput
}

export type EscalationLogUncheckedCreateInput = {
  id?: string
  clinicId: string
  entityType: $Enums.EntityType
  entityId: string
  eventType: string
  severity: $Enums.Severity
  message: string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  userId?: string | null
  createdAt?: Date | string
}

export type EscalationLogUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.EnumEntityTypeFieldUpdateOperationsInput | $Enums.EntityType
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  eventType?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.EnumSeverityFieldUpdateOperationsInput | $Enums.Severity
  message?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  clinic?: Prisma.ClinicUpdateOneRequiredWithoutEscalationLogsNestedInput
  user?: Prisma.UserUpdateOneWithoutEscalationLogsNestedInput
}

export type EscalationLogUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clinicId?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.EnumEntityTypeFieldUpdateOperationsInput | $Enums.EntityType
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  eventType?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.EnumSeverityFieldUpdateOperationsInput | $Enums.Severity
  message?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EscalationLogCreateManyInput = {
  id?: string
  clinicId: string
  entityType: $Enums.EntityType
  entityId: string
  eventType: string
  severity: $Enums.Severity
  message: string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  userId?: string | null
  createdAt?: Date | string
}

export type EscalationLogUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.EnumEntityTypeFieldUpdateOperationsInput | $Enums.EntityType
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  eventType?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.EnumSeverityFieldUpdateOperationsInput | $Enums.Severity
  message?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EscalationLogUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clinicId?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.EnumEntityTypeFieldUpdateOperationsInput | $Enums.EntityType
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  eventType?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.EnumSeverityFieldUpdateOperationsInput | $Enums.Severity
  message?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EscalationLogListRelationFilter = {
  every?: Prisma.EscalationLogWhereInput
  some?: Prisma.EscalationLogWhereInput
  none?: Prisma.EscalationLogWhereInput
}

export type EscalationLogOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EscalationLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clinicId?: Prisma.SortOrder
  entityType?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  eventType?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  message?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type EscalationLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clinicId?: Prisma.SortOrder
  entityType?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  eventType?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  message?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type EscalationLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clinicId?: Prisma.SortOrder
  entityType?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  eventType?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  message?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type EscalationLogCreateNestedManyWithoutClinicInput = {
  create?: Prisma.XOR<Prisma.EscalationLogCreateWithoutClinicInput, Prisma.EscalationLogUncheckedCreateWithoutClinicInput> | Prisma.EscalationLogCreateWithoutClinicInput[] | Prisma.EscalationLogUncheckedCreateWithoutClinicInput[]
  connectOrCreate?: Prisma.EscalationLogCreateOrConnectWithoutClinicInput | Prisma.EscalationLogCreateOrConnectWithoutClinicInput[]
  createMany?: Prisma.EscalationLogCreateManyClinicInputEnvelope
  connect?: Prisma.EscalationLogWhereUniqueInput | Prisma.EscalationLogWhereUniqueInput[]
}

export type EscalationLogUncheckedCreateNestedManyWithoutClinicInput = {
  create?: Prisma.XOR<Prisma.EscalationLogCreateWithoutClinicInput, Prisma.EscalationLogUncheckedCreateWithoutClinicInput> | Prisma.EscalationLogCreateWithoutClinicInput[] | Prisma.EscalationLogUncheckedCreateWithoutClinicInput[]
  connectOrCreate?: Prisma.EscalationLogCreateOrConnectWithoutClinicInput | Prisma.EscalationLogCreateOrConnectWithoutClinicInput[]
  createMany?: Prisma.EscalationLogCreateManyClinicInputEnvelope
  connect?: Prisma.EscalationLogWhereUniqueInput | Prisma.EscalationLogWhereUniqueInput[]
}

export type EscalationLogUpdateManyWithoutClinicNestedInput = {
  create?: Prisma.XOR<Prisma.EscalationLogCreateWithoutClinicInput, Prisma.EscalationLogUncheckedCreateWithoutClinicInput> | Prisma.EscalationLogCreateWithoutClinicInput[] | Prisma.EscalationLogUncheckedCreateWithoutClinicInput[]
  connectOrCreate?: Prisma.EscalationLogCreateOrConnectWithoutClinicInput | Prisma.EscalationLogCreateOrConnectWithoutClinicInput[]
  upsert?: Prisma.EscalationLogUpsertWithWhereUniqueWithoutClinicInput | Prisma.EscalationLogUpsertWithWhereUniqueWithoutClinicInput[]
  createMany?: Prisma.EscalationLogCreateManyClinicInputEnvelope
  set?: Prisma.EscalationLogWhereUniqueInput | Prisma.EscalationLogWhereUniqueInput[]
  disconnect?: Prisma.EscalationLogWhereUniqueInput | Prisma.EscalationLogWhereUniqueInput[]
  delete?: Prisma.EscalationLogWhereUniqueInput | Prisma.EscalationLogWhereUniqueInput[]
  connect?: Prisma.EscalationLogWhereUniqueInput | Prisma.EscalationLogWhereUniqueInput[]
  update?: Prisma.EscalationLogUpdateWithWhereUniqueWithoutClinicInput | Prisma.EscalationLogUpdateWithWhereUniqueWithoutClinicInput[]
  updateMany?: Prisma.EscalationLogUpdateManyWithWhereWithoutClinicInput | Prisma.EscalationLogUpdateManyWithWhereWithoutClinicInput[]
  deleteMany?: Prisma.EscalationLogScalarWhereInput | Prisma.EscalationLogScalarWhereInput[]
}

export type EscalationLogUncheckedUpdateManyWithoutClinicNestedInput = {
  create?: Prisma.XOR<Prisma.EscalationLogCreateWithoutClinicInput, Prisma.EscalationLogUncheckedCreateWithoutClinicInput> | Prisma.EscalationLogCreateWithoutClinicInput[] | Prisma.EscalationLogUncheckedCreateWithoutClinicInput[]
  connectOrCreate?: Prisma.EscalationLogCreateOrConnectWithoutClinicInput | Prisma.EscalationLogCreateOrConnectWithoutClinicInput[]
  upsert?: Prisma.EscalationLogUpsertWithWhereUniqueWithoutClinicInput | Prisma.EscalationLogUpsertWithWhereUniqueWithoutClinicInput[]
  createMany?: Prisma.EscalationLogCreateManyClinicInputEnvelope
  set?: Prisma.EscalationLogWhereUniqueInput | Prisma.EscalationLogWhereUniqueInput[]
  disconnect?: Prisma.EscalationLogWhereUniqueInput | Prisma.EscalationLogWhereUniqueInput[]
  delete?: Prisma.EscalationLogWhereUniqueInput | Prisma.EscalationLogWhereUniqueInput[]
  connect?: Prisma.EscalationLogWhereUniqueInput | Prisma.EscalationLogWhereUniqueInput[]
  update?: Prisma.EscalationLogUpdateWithWhereUniqueWithoutClinicInput | Prisma.EscalationLogUpdateWithWhereUniqueWithoutClinicInput[]
  updateMany?: Prisma.EscalationLogUpdateManyWithWhereWithoutClinicInput | Prisma.EscalationLogUpdateManyWithWhereWithoutClinicInput[]
  deleteMany?: Prisma.EscalationLogScalarWhereInput | Prisma.EscalationLogScalarWhereInput[]
}

export type EscalationLogCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.EscalationLogCreateWithoutUserInput, Prisma.EscalationLogUncheckedCreateWithoutUserInput> | Prisma.EscalationLogCreateWithoutUserInput[] | Prisma.EscalationLogUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.EscalationLogCreateOrConnectWithoutUserInput | Prisma.EscalationLogCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.EscalationLogCreateManyUserInputEnvelope
  connect?: Prisma.EscalationLogWhereUniqueInput | Prisma.EscalationLogWhereUniqueInput[]
}

export type EscalationLogUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.EscalationLogCreateWithoutUserInput, Prisma.EscalationLogUncheckedCreateWithoutUserInput> | Prisma.EscalationLogCreateWithoutUserInput[] | Prisma.EscalationLogUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.EscalationLogCreateOrConnectWithoutUserInput | Prisma.EscalationLogCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.EscalationLogCreateManyUserInputEnvelope
  connect?: Prisma.EscalationLogWhereUniqueInput | Prisma.EscalationLogWhereUniqueInput[]
}

export type EscalationLogUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.EscalationLogCreateWithoutUserInput, Prisma.EscalationLogUncheckedCreateWithoutUserInput> | Prisma.EscalationLogCreateWithoutUserInput[] | Prisma.EscalationLogUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.EscalationLogCreateOrConnectWithoutUserInput | Prisma.EscalationLogCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.EscalationLogUpsertWithWhereUniqueWithoutUserInput | Prisma.EscalationLogUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.EscalationLogCreateManyUserInputEnvelope
  set?: Prisma.EscalationLogWhereUniqueInput | Prisma.EscalationLogWhereUniqueInput[]
  disconnect?: Prisma.EscalationLogWhereUniqueInput | Prisma.EscalationLogWhereUniqueInput[]
  delete?: Prisma.EscalationLogWhereUniqueInput | Prisma.EscalationLogWhereUniqueInput[]
  connect?: Prisma.EscalationLogWhereUniqueInput | Prisma.EscalationLogWhereUniqueInput[]
  update?: Prisma.EscalationLogUpdateWithWhereUniqueWithoutUserInput | Prisma.EscalationLogUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.EscalationLogUpdateManyWithWhereWithoutUserInput | Prisma.EscalationLogUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.EscalationLogScalarWhereInput | Prisma.EscalationLogScalarWhereInput[]
}

export type EscalationLogUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.EscalationLogCreateWithoutUserInput, Prisma.EscalationLogUncheckedCreateWithoutUserInput> | Prisma.EscalationLogCreateWithoutUserInput[] | Prisma.EscalationLogUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.EscalationLogCreateOrConnectWithoutUserInput | Prisma.EscalationLogCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.EscalationLogUpsertWithWhereUniqueWithoutUserInput | Prisma.EscalationLogUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.EscalationLogCreateManyUserInputEnvelope
  set?: Prisma.EscalationLogWhereUniqueInput | Prisma.EscalationLogWhereUniqueInput[]
  disconnect?: Prisma.EscalationLogWhereUniqueInput | Prisma.EscalationLogWhereUniqueInput[]
  delete?: Prisma.EscalationLogWhereUniqueInput | Prisma.EscalationLogWhereUniqueInput[]
  connect?: Prisma.EscalationLogWhereUniqueInput | Prisma.EscalationLogWhereUniqueInput[]
  update?: Prisma.EscalationLogUpdateWithWhereUniqueWithoutUserInput | Prisma.EscalationLogUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.EscalationLogUpdateManyWithWhereWithoutUserInput | Prisma.EscalationLogUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.EscalationLogScalarWhereInput | Prisma.EscalationLogScalarWhereInput[]
}

export type EnumEntityTypeFieldUpdateOperationsInput = {
  set?: $Enums.EntityType
}

export type EnumSeverityFieldUpdateOperationsInput = {
  set?: $Enums.Severity
}

export type EscalationLogCreateWithoutClinicInput = {
  id?: string
  entityType: $Enums.EntityType
  entityId: string
  eventType: string
  severity: $Enums.Severity
  message: string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutEscalationLogsInput
}

export type EscalationLogUncheckedCreateWithoutClinicInput = {
  id?: string
  entityType: $Enums.EntityType
  entityId: string
  eventType: string
  severity: $Enums.Severity
  message: string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  userId?: string | null
  createdAt?: Date | string
}

export type EscalationLogCreateOrConnectWithoutClinicInput = {
  where: Prisma.EscalationLogWhereUniqueInput
  create: Prisma.XOR<Prisma.EscalationLogCreateWithoutClinicInput, Prisma.EscalationLogUncheckedCreateWithoutClinicInput>
}

export type EscalationLogCreateManyClinicInputEnvelope = {
  data: Prisma.EscalationLogCreateManyClinicInput | Prisma.EscalationLogCreateManyClinicInput[]
  skipDuplicates?: boolean
}

export type EscalationLogUpsertWithWhereUniqueWithoutClinicInput = {
  where: Prisma.EscalationLogWhereUniqueInput
  update: Prisma.XOR<Prisma.EscalationLogUpdateWithoutClinicInput, Prisma.EscalationLogUncheckedUpdateWithoutClinicInput>
  create: Prisma.XOR<Prisma.EscalationLogCreateWithoutClinicInput, Prisma.EscalationLogUncheckedCreateWithoutClinicInput>
}

export type EscalationLogUpdateWithWhereUniqueWithoutClinicInput = {
  where: Prisma.EscalationLogWhereUniqueInput
  data: Prisma.XOR<Prisma.EscalationLogUpdateWithoutClinicInput, Prisma.EscalationLogUncheckedUpdateWithoutClinicInput>
}

export type EscalationLogUpdateManyWithWhereWithoutClinicInput = {
  where: Prisma.EscalationLogScalarWhereInput
  data: Prisma.XOR<Prisma.EscalationLogUpdateManyMutationInput, Prisma.EscalationLogUncheckedUpdateManyWithoutClinicInput>
}

export type EscalationLogScalarWhereInput = {
  AND?: Prisma.EscalationLogScalarWhereInput | Prisma.EscalationLogScalarWhereInput[]
  OR?: Prisma.EscalationLogScalarWhereInput[]
  NOT?: Prisma.EscalationLogScalarWhereInput | Prisma.EscalationLogScalarWhereInput[]
  id?: Prisma.StringFilter<"EscalationLog"> | string
  clinicId?: Prisma.StringFilter<"EscalationLog"> | string
  entityType?: Prisma.EnumEntityTypeFilter<"EscalationLog"> | $Enums.EntityType
  entityId?: Prisma.StringFilter<"EscalationLog"> | string
  eventType?: Prisma.StringFilter<"EscalationLog"> | string
  severity?: Prisma.EnumSeverityFilter<"EscalationLog"> | $Enums.Severity
  message?: Prisma.StringFilter<"EscalationLog"> | string
  metadata?: Prisma.JsonNullableFilter<"EscalationLog">
  userId?: Prisma.StringNullableFilter<"EscalationLog"> | string | null
  createdAt?: Prisma.DateTimeFilter<"EscalationLog"> | Date | string
}

export type EscalationLogCreateWithoutUserInput = {
  id?: string
  entityType: $Enums.EntityType
  entityId: string
  eventType: string
  severity: $Enums.Severity
  message: string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  clinic: Prisma.ClinicCreateNestedOneWithoutEscalationLogsInput
}

export type EscalationLogUncheckedCreateWithoutUserInput = {
  id?: string
  clinicId: string
  entityType: $Enums.EntityType
  entityId: string
  eventType: string
  severity: $Enums.Severity
  message: string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type EscalationLogCreateOrConnectWithoutUserInput = {
  where: Prisma.EscalationLogWhereUniqueInput
  create: Prisma.XOR<Prisma.EscalationLogCreateWithoutUserInput, Prisma.EscalationLogUncheckedCreateWithoutUserInput>
}

export type EscalationLogCreateManyUserInputEnvelope = {
  data: Prisma.EscalationLogCreateManyUserInput | Prisma.EscalationLogCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type EscalationLogUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.EscalationLogWhereUniqueInput
  update: Prisma.XOR<Prisma.EscalationLogUpdateWithoutUserInput, Prisma.EscalationLogUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.EscalationLogCreateWithoutUserInput, Prisma.EscalationLogUncheckedCreateWithoutUserInput>
}

export type EscalationLogUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.EscalationLogWhereUniqueInput
  data: Prisma.XOR<Prisma.EscalationLogUpdateWithoutUserInput, Prisma.EscalationLogUncheckedUpdateWithoutUserInput>
}

export type EscalationLogUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.EscalationLogScalarWhereInput
  data: Prisma.XOR<Prisma.EscalationLogUpdateManyMutationInput, Prisma.EscalationLogUncheckedUpdateManyWithoutUserInput>
}

export type EscalationLogCreateManyClinicInput = {
  id?: string
  entityType: $Enums.EntityType
  entityId: string
  eventType: string
  severity: $Enums.Severity
  message: string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  userId?: string | null
  createdAt?: Date | string
}

export type EscalationLogUpdateWithoutClinicInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.EnumEntityTypeFieldUpdateOperationsInput | $Enums.EntityType
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  eventType?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.EnumSeverityFieldUpdateOperationsInput | $Enums.Severity
  message?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutEscalationLogsNestedInput
}

export type EscalationLogUncheckedUpdateWithoutClinicInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.EnumEntityTypeFieldUpdateOperationsInput | $Enums.EntityType
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  eventType?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.EnumSeverityFieldUpdateOperationsInput | $Enums.Severity
  message?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EscalationLogUncheckedUpdateManyWithoutClinicInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.EnumEntityTypeFieldUpdateOperationsInput | $Enums.EntityType
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  eventType?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.EnumSeverityFieldUpdateOperationsInput | $Enums.Severity
  message?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EscalationLogCreateManyUserInput = {
  id?: string
  clinicId: string
  entityType: $Enums.EntityType
  entityId: string
  eventType: string
  severity: $Enums.Severity
  message: string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type EscalationLogUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.EnumEntityTypeFieldUpdateOperationsInput | $Enums.EntityType
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  eventType?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.EnumSeverityFieldUpdateOperationsInput | $Enums.Severity
  message?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  clinic?: Prisma.ClinicUpdateOneRequiredWithoutEscalationLogsNestedInput
}

export type EscalationLogUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clinicId?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.EnumEntityTypeFieldUpdateOperationsInput | $Enums.EntityType
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  eventType?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.EnumSeverityFieldUpdateOperationsInput | $Enums.Severity
  message?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EscalationLogUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clinicId?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.EnumEntityTypeFieldUpdateOperationsInput | $Enums.EntityType
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  eventType?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.EnumSeverityFieldUpdateOperationsInput | $Enums.Severity
  message?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type EscalationLogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clinicId?: boolean
  entityType?: boolean
  entityId?: boolean
  eventType?: boolean
  severity?: boolean
  message?: boolean
  metadata?: boolean
  userId?: boolean
  createdAt?: boolean
  clinic?: boolean | Prisma.ClinicDefaultArgs<ExtArgs>
  user?: boolean | Prisma.EscalationLog$userArgs<ExtArgs>
}, ExtArgs["result"]["escalationLog"]>

export type EscalationLogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clinicId?: boolean
  entityType?: boolean
  entityId?: boolean
  eventType?: boolean
  severity?: boolean
  message?: boolean
  metadata?: boolean
  userId?: boolean
  createdAt?: boolean
  clinic?: boolean | Prisma.ClinicDefaultArgs<ExtArgs>
  user?: boolean | Prisma.EscalationLog$userArgs<ExtArgs>
}, ExtArgs["result"]["escalationLog"]>

export type EscalationLogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clinicId?: boolean
  entityType?: boolean
  entityId?: boolean
  eventType?: boolean
  severity?: boolean
  message?: boolean
  metadata?: boolean
  userId?: boolean
  createdAt?: boolean
  clinic?: boolean | Prisma.ClinicDefaultArgs<ExtArgs>
  user?: boolean | Prisma.EscalationLog$userArgs<ExtArgs>
}, ExtArgs["result"]["escalationLog"]>

export type EscalationLogSelectScalar = {
  id?: boolean
  clinicId?: boolean
  entityType?: boolean
  entityId?: boolean
  eventType?: boolean
  severity?: boolean
  message?: boolean
  metadata?: boolean
  userId?: boolean
  createdAt?: boolean
}

export type EscalationLogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "clinicId" | "entityType" | "entityId" | "eventType" | "severity" | "message" | "metadata" | "userId" | "createdAt", ExtArgs["result"]["escalationLog"]>
export type EscalationLogInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  clinic?: boolean | Prisma.ClinicDefaultArgs<ExtArgs>
  user?: boolean | Prisma.EscalationLog$userArgs<ExtArgs>
}
export type EscalationLogIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  clinic?: boolean | Prisma.ClinicDefaultArgs<ExtArgs>
  user?: boolean | Prisma.EscalationLog$userArgs<ExtArgs>
}
export type EscalationLogIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  clinic?: boolean | Prisma.ClinicDefaultArgs<ExtArgs>
  user?: boolean | Prisma.EscalationLog$userArgs<ExtArgs>
}

export type $EscalationLogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EscalationLog"
  objects: {
    clinic: Prisma.$ClinicPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    clinicId: string
    entityType: $Enums.EntityType
    entityId: string
    eventType: string
    severity: $Enums.Severity
    message: string
    metadata: runtime.JsonValue | null
    userId: string | null
    createdAt: Date
  }, ExtArgs["result"]["escalationLog"]>
  composites: {}
}

export type EscalationLogGetPayload<S extends boolean | null | undefined | EscalationLogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EscalationLogPayload, S>

export type EscalationLogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EscalationLogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EscalationLogCountAggregateInputType | true
  }

export interface EscalationLogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EscalationLog'], meta: { name: 'EscalationLog' } }
  /**
   * Find zero or one EscalationLog that matches the filter.
   * @param {EscalationLogFindUniqueArgs} args - Arguments to find a EscalationLog
   * @example
   * // Get one EscalationLog
   * const escalationLog = await prisma.escalationLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EscalationLogFindUniqueArgs>(args: Prisma.SelectSubset<T, EscalationLogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EscalationLogClient<runtime.Types.Result.GetResult<Prisma.$EscalationLogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EscalationLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EscalationLogFindUniqueOrThrowArgs} args - Arguments to find a EscalationLog
   * @example
   * // Get one EscalationLog
   * const escalationLog = await prisma.escalationLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EscalationLogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EscalationLogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EscalationLogClient<runtime.Types.Result.GetResult<Prisma.$EscalationLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EscalationLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EscalationLogFindFirstArgs} args - Arguments to find a EscalationLog
   * @example
   * // Get one EscalationLog
   * const escalationLog = await prisma.escalationLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EscalationLogFindFirstArgs>(args?: Prisma.SelectSubset<T, EscalationLogFindFirstArgs<ExtArgs>>): Prisma.Prisma__EscalationLogClient<runtime.Types.Result.GetResult<Prisma.$EscalationLogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EscalationLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EscalationLogFindFirstOrThrowArgs} args - Arguments to find a EscalationLog
   * @example
   * // Get one EscalationLog
   * const escalationLog = await prisma.escalationLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EscalationLogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EscalationLogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EscalationLogClient<runtime.Types.Result.GetResult<Prisma.$EscalationLogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EscalationLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EscalationLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EscalationLogs
   * const escalationLogs = await prisma.escalationLog.findMany()
   * 
   * // Get first 10 EscalationLogs
   * const escalationLogs = await prisma.escalationLog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const escalationLogWithIdOnly = await prisma.escalationLog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EscalationLogFindManyArgs>(args?: Prisma.SelectSubset<T, EscalationLogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EscalationLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EscalationLog.
   * @param {EscalationLogCreateArgs} args - Arguments to create a EscalationLog.
   * @example
   * // Create one EscalationLog
   * const EscalationLog = await prisma.escalationLog.create({
   *   data: {
   *     // ... data to create a EscalationLog
   *   }
   * })
   * 
   */
  create<T extends EscalationLogCreateArgs>(args: Prisma.SelectSubset<T, EscalationLogCreateArgs<ExtArgs>>): Prisma.Prisma__EscalationLogClient<runtime.Types.Result.GetResult<Prisma.$EscalationLogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EscalationLogs.
   * @param {EscalationLogCreateManyArgs} args - Arguments to create many EscalationLogs.
   * @example
   * // Create many EscalationLogs
   * const escalationLog = await prisma.escalationLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EscalationLogCreateManyArgs>(args?: Prisma.SelectSubset<T, EscalationLogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EscalationLogs and returns the data saved in the database.
   * @param {EscalationLogCreateManyAndReturnArgs} args - Arguments to create many EscalationLogs.
   * @example
   * // Create many EscalationLogs
   * const escalationLog = await prisma.escalationLog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EscalationLogs and only return the `id`
   * const escalationLogWithIdOnly = await prisma.escalationLog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EscalationLogCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EscalationLogCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EscalationLogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EscalationLog.
   * @param {EscalationLogDeleteArgs} args - Arguments to delete one EscalationLog.
   * @example
   * // Delete one EscalationLog
   * const EscalationLog = await prisma.escalationLog.delete({
   *   where: {
   *     // ... filter to delete one EscalationLog
   *   }
   * })
   * 
   */
  delete<T extends EscalationLogDeleteArgs>(args: Prisma.SelectSubset<T, EscalationLogDeleteArgs<ExtArgs>>): Prisma.Prisma__EscalationLogClient<runtime.Types.Result.GetResult<Prisma.$EscalationLogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EscalationLog.
   * @param {EscalationLogUpdateArgs} args - Arguments to update one EscalationLog.
   * @example
   * // Update one EscalationLog
   * const escalationLog = await prisma.escalationLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EscalationLogUpdateArgs>(args: Prisma.SelectSubset<T, EscalationLogUpdateArgs<ExtArgs>>): Prisma.Prisma__EscalationLogClient<runtime.Types.Result.GetResult<Prisma.$EscalationLogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EscalationLogs.
   * @param {EscalationLogDeleteManyArgs} args - Arguments to filter EscalationLogs to delete.
   * @example
   * // Delete a few EscalationLogs
   * const { count } = await prisma.escalationLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EscalationLogDeleteManyArgs>(args?: Prisma.SelectSubset<T, EscalationLogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EscalationLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EscalationLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EscalationLogs
   * const escalationLog = await prisma.escalationLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EscalationLogUpdateManyArgs>(args: Prisma.SelectSubset<T, EscalationLogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EscalationLogs and returns the data updated in the database.
   * @param {EscalationLogUpdateManyAndReturnArgs} args - Arguments to update many EscalationLogs.
   * @example
   * // Update many EscalationLogs
   * const escalationLog = await prisma.escalationLog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EscalationLogs and only return the `id`
   * const escalationLogWithIdOnly = await prisma.escalationLog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EscalationLogUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EscalationLogUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EscalationLogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EscalationLog.
   * @param {EscalationLogUpsertArgs} args - Arguments to update or create a EscalationLog.
   * @example
   * // Update or create a EscalationLog
   * const escalationLog = await prisma.escalationLog.upsert({
   *   create: {
   *     // ... data to create a EscalationLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EscalationLog we want to update
   *   }
   * })
   */
  upsert<T extends EscalationLogUpsertArgs>(args: Prisma.SelectSubset<T, EscalationLogUpsertArgs<ExtArgs>>): Prisma.Prisma__EscalationLogClient<runtime.Types.Result.GetResult<Prisma.$EscalationLogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EscalationLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EscalationLogCountArgs} args - Arguments to filter EscalationLogs to count.
   * @example
   * // Count the number of EscalationLogs
   * const count = await prisma.escalationLog.count({
   *   where: {
   *     // ... the filter for the EscalationLogs we want to count
   *   }
   * })
  **/
  count<T extends EscalationLogCountArgs>(
    args?: Prisma.Subset<T, EscalationLogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EscalationLogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EscalationLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EscalationLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EscalationLogAggregateArgs>(args: Prisma.Subset<T, EscalationLogAggregateArgs>): Prisma.PrismaPromise<GetEscalationLogAggregateType<T>>

  /**
   * Group by EscalationLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EscalationLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EscalationLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EscalationLogGroupByArgs['orderBy'] }
      : { orderBy?: EscalationLogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EscalationLogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEscalationLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EscalationLog model
 */
readonly fields: EscalationLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EscalationLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EscalationLogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  clinic<T extends Prisma.ClinicDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ClinicDefaultArgs<ExtArgs>>): Prisma.Prisma__ClinicClient<runtime.Types.Result.GetResult<Prisma.$ClinicPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.EscalationLog$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EscalationLog$userArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EscalationLog model
 */
export interface EscalationLogFieldRefs {
  readonly id: Prisma.FieldRef<"EscalationLog", 'String'>
  readonly clinicId: Prisma.FieldRef<"EscalationLog", 'String'>
  readonly entityType: Prisma.FieldRef<"EscalationLog", 'EntityType'>
  readonly entityId: Prisma.FieldRef<"EscalationLog", 'String'>
  readonly eventType: Prisma.FieldRef<"EscalationLog", 'String'>
  readonly severity: Prisma.FieldRef<"EscalationLog", 'Severity'>
  readonly message: Prisma.FieldRef<"EscalationLog", 'String'>
  readonly metadata: Prisma.FieldRef<"EscalationLog", 'Json'>
  readonly userId: Prisma.FieldRef<"EscalationLog", 'String'>
  readonly createdAt: Prisma.FieldRef<"EscalationLog", 'DateTime'>
}
    

// Custom InputTypes
/**
 * EscalationLog findUnique
 */
export type EscalationLogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EscalationLog
   */
  select?: Prisma.EscalationLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EscalationLog
   */
  omit?: Prisma.EscalationLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EscalationLogInclude<ExtArgs> | null
  /**
   * Filter, which EscalationLog to fetch.
   */
  where: Prisma.EscalationLogWhereUniqueInput
}

/**
 * EscalationLog findUniqueOrThrow
 */
export type EscalationLogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EscalationLog
   */
  select?: Prisma.EscalationLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EscalationLog
   */
  omit?: Prisma.EscalationLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EscalationLogInclude<ExtArgs> | null
  /**
   * Filter, which EscalationLog to fetch.
   */
  where: Prisma.EscalationLogWhereUniqueInput
}

/**
 * EscalationLog findFirst
 */
export type EscalationLogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EscalationLog
   */
  select?: Prisma.EscalationLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EscalationLog
   */
  omit?: Prisma.EscalationLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EscalationLogInclude<ExtArgs> | null
  /**
   * Filter, which EscalationLog to fetch.
   */
  where?: Prisma.EscalationLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EscalationLogs to fetch.
   */
  orderBy?: Prisma.EscalationLogOrderByWithRelationInput | Prisma.EscalationLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EscalationLogs.
   */
  cursor?: Prisma.EscalationLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EscalationLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EscalationLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EscalationLogs.
   */
  distinct?: Prisma.EscalationLogScalarFieldEnum | Prisma.EscalationLogScalarFieldEnum[]
}

/**
 * EscalationLog findFirstOrThrow
 */
export type EscalationLogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EscalationLog
   */
  select?: Prisma.EscalationLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EscalationLog
   */
  omit?: Prisma.EscalationLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EscalationLogInclude<ExtArgs> | null
  /**
   * Filter, which EscalationLog to fetch.
   */
  where?: Prisma.EscalationLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EscalationLogs to fetch.
   */
  orderBy?: Prisma.EscalationLogOrderByWithRelationInput | Prisma.EscalationLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EscalationLogs.
   */
  cursor?: Prisma.EscalationLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EscalationLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EscalationLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EscalationLogs.
   */
  distinct?: Prisma.EscalationLogScalarFieldEnum | Prisma.EscalationLogScalarFieldEnum[]
}

/**
 * EscalationLog findMany
 */
export type EscalationLogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EscalationLog
   */
  select?: Prisma.EscalationLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EscalationLog
   */
  omit?: Prisma.EscalationLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EscalationLogInclude<ExtArgs> | null
  /**
   * Filter, which EscalationLogs to fetch.
   */
  where?: Prisma.EscalationLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EscalationLogs to fetch.
   */
  orderBy?: Prisma.EscalationLogOrderByWithRelationInput | Prisma.EscalationLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EscalationLogs.
   */
  cursor?: Prisma.EscalationLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EscalationLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EscalationLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EscalationLogs.
   */
  distinct?: Prisma.EscalationLogScalarFieldEnum | Prisma.EscalationLogScalarFieldEnum[]
}

/**
 * EscalationLog create
 */
export type EscalationLogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EscalationLog
   */
  select?: Prisma.EscalationLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EscalationLog
   */
  omit?: Prisma.EscalationLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EscalationLogInclude<ExtArgs> | null
  /**
   * The data needed to create a EscalationLog.
   */
  data: Prisma.XOR<Prisma.EscalationLogCreateInput, Prisma.EscalationLogUncheckedCreateInput>
}

/**
 * EscalationLog createMany
 */
export type EscalationLogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EscalationLogs.
   */
  data: Prisma.EscalationLogCreateManyInput | Prisma.EscalationLogCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * EscalationLog createManyAndReturn
 */
export type EscalationLogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EscalationLog
   */
  select?: Prisma.EscalationLogSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EscalationLog
   */
  omit?: Prisma.EscalationLogOmit<ExtArgs> | null
  /**
   * The data used to create many EscalationLogs.
   */
  data: Prisma.EscalationLogCreateManyInput | Prisma.EscalationLogCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EscalationLogIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * EscalationLog update
 */
export type EscalationLogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EscalationLog
   */
  select?: Prisma.EscalationLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EscalationLog
   */
  omit?: Prisma.EscalationLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EscalationLogInclude<ExtArgs> | null
  /**
   * The data needed to update a EscalationLog.
   */
  data: Prisma.XOR<Prisma.EscalationLogUpdateInput, Prisma.EscalationLogUncheckedUpdateInput>
  /**
   * Choose, which EscalationLog to update.
   */
  where: Prisma.EscalationLogWhereUniqueInput
}

/**
 * EscalationLog updateMany
 */
export type EscalationLogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EscalationLogs.
   */
  data: Prisma.XOR<Prisma.EscalationLogUpdateManyMutationInput, Prisma.EscalationLogUncheckedUpdateManyInput>
  /**
   * Filter which EscalationLogs to update
   */
  where?: Prisma.EscalationLogWhereInput
  /**
   * Limit how many EscalationLogs to update.
   */
  limit?: number
}

/**
 * EscalationLog updateManyAndReturn
 */
export type EscalationLogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EscalationLog
   */
  select?: Prisma.EscalationLogSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EscalationLog
   */
  omit?: Prisma.EscalationLogOmit<ExtArgs> | null
  /**
   * The data used to update EscalationLogs.
   */
  data: Prisma.XOR<Prisma.EscalationLogUpdateManyMutationInput, Prisma.EscalationLogUncheckedUpdateManyInput>
  /**
   * Filter which EscalationLogs to update
   */
  where?: Prisma.EscalationLogWhereInput
  /**
   * Limit how many EscalationLogs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EscalationLogIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * EscalationLog upsert
 */
export type EscalationLogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EscalationLog
   */
  select?: Prisma.EscalationLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EscalationLog
   */
  omit?: Prisma.EscalationLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EscalationLogInclude<ExtArgs> | null
  /**
   * The filter to search for the EscalationLog to update in case it exists.
   */
  where: Prisma.EscalationLogWhereUniqueInput
  /**
   * In case the EscalationLog found by the `where` argument doesn't exist, create a new EscalationLog with this data.
   */
  create: Prisma.XOR<Prisma.EscalationLogCreateInput, Prisma.EscalationLogUncheckedCreateInput>
  /**
   * In case the EscalationLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EscalationLogUpdateInput, Prisma.EscalationLogUncheckedUpdateInput>
}

/**
 * EscalationLog delete
 */
export type EscalationLogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EscalationLog
   */
  select?: Prisma.EscalationLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EscalationLog
   */
  omit?: Prisma.EscalationLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EscalationLogInclude<ExtArgs> | null
  /**
   * Filter which EscalationLog to delete.
   */
  where: Prisma.EscalationLogWhereUniqueInput
}

/**
 * EscalationLog deleteMany
 */
export type EscalationLogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EscalationLogs to delete
   */
  where?: Prisma.EscalationLogWhereInput
  /**
   * Limit how many EscalationLogs to delete.
   */
  limit?: number
}

/**
 * EscalationLog.user
 */
export type EscalationLog$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * EscalationLog without action
 */
export type EscalationLogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EscalationLog
   */
  select?: Prisma.EscalationLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EscalationLog
   */
  omit?: Prisma.EscalationLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EscalationLogInclude<ExtArgs> | null
}
