
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `StateTransitionLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model StateTransitionLog
 * 
 */
export type StateTransitionLogModel = runtime.Types.Result.DefaultSelection<Prisma.$StateTransitionLogPayload>

export type AggregateStateTransitionLog = {
  _count: StateTransitionLogCountAggregateOutputType | null
  _min: StateTransitionLogMinAggregateOutputType | null
  _max: StateTransitionLogMaxAggregateOutputType | null
}

export type StateTransitionLogMinAggregateOutputType = {
  id: string | null
  sessionId: string | null
  clinicId: string | null
  fromState: $Enums.ConversationState | null
  toState: $Enums.ConversationState | null
  triggerType: string | null
  triggeredBy: string | null
  createdAt: Date | null
}

export type StateTransitionLogMaxAggregateOutputType = {
  id: string | null
  sessionId: string | null
  clinicId: string | null
  fromState: $Enums.ConversationState | null
  toState: $Enums.ConversationState | null
  triggerType: string | null
  triggeredBy: string | null
  createdAt: Date | null
}

export type StateTransitionLogCountAggregateOutputType = {
  id: number
  sessionId: number
  clinicId: number
  fromState: number
  toState: number
  triggerType: number
  triggerPayload: number
  triggeredBy: number
  createdAt: number
  _all: number
}


export type StateTransitionLogMinAggregateInputType = {
  id?: true
  sessionId?: true
  clinicId?: true
  fromState?: true
  toState?: true
  triggerType?: true
  triggeredBy?: true
  createdAt?: true
}

export type StateTransitionLogMaxAggregateInputType = {
  id?: true
  sessionId?: true
  clinicId?: true
  fromState?: true
  toState?: true
  triggerType?: true
  triggeredBy?: true
  createdAt?: true
}

export type StateTransitionLogCountAggregateInputType = {
  id?: true
  sessionId?: true
  clinicId?: true
  fromState?: true
  toState?: true
  triggerType?: true
  triggerPayload?: true
  triggeredBy?: true
  createdAt?: true
  _all?: true
}

export type StateTransitionLogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StateTransitionLog to aggregate.
   */
  where?: Prisma.StateTransitionLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StateTransitionLogs to fetch.
   */
  orderBy?: Prisma.StateTransitionLogOrderByWithRelationInput | Prisma.StateTransitionLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StateTransitionLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StateTransitionLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StateTransitionLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned StateTransitionLogs
  **/
  _count?: true | StateTransitionLogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StateTransitionLogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StateTransitionLogMaxAggregateInputType
}

export type GetStateTransitionLogAggregateType<T extends StateTransitionLogAggregateArgs> = {
      [P in keyof T & keyof AggregateStateTransitionLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStateTransitionLog[P]>
    : Prisma.GetScalarType<T[P], AggregateStateTransitionLog[P]>
}




export type StateTransitionLogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StateTransitionLogWhereInput
  orderBy?: Prisma.StateTransitionLogOrderByWithAggregationInput | Prisma.StateTransitionLogOrderByWithAggregationInput[]
  by: Prisma.StateTransitionLogScalarFieldEnum[] | Prisma.StateTransitionLogScalarFieldEnum
  having?: Prisma.StateTransitionLogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StateTransitionLogCountAggregateInputType | true
  _min?: StateTransitionLogMinAggregateInputType
  _max?: StateTransitionLogMaxAggregateInputType
}

export type StateTransitionLogGroupByOutputType = {
  id: string
  sessionId: string
  clinicId: string
  fromState: $Enums.ConversationState
  toState: $Enums.ConversationState
  triggerType: string
  triggerPayload: runtime.JsonValue | null
  triggeredBy: string | null
  createdAt: Date
  _count: StateTransitionLogCountAggregateOutputType | null
  _min: StateTransitionLogMinAggregateOutputType | null
  _max: StateTransitionLogMaxAggregateOutputType | null
}

export type GetStateTransitionLogGroupByPayload<T extends StateTransitionLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StateTransitionLogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StateTransitionLogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StateTransitionLogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StateTransitionLogGroupByOutputType[P]>
      }
    >
  >



export type StateTransitionLogWhereInput = {
  AND?: Prisma.StateTransitionLogWhereInput | Prisma.StateTransitionLogWhereInput[]
  OR?: Prisma.StateTransitionLogWhereInput[]
  NOT?: Prisma.StateTransitionLogWhereInput | Prisma.StateTransitionLogWhereInput[]
  id?: Prisma.StringFilter<"StateTransitionLog"> | string
  sessionId?: Prisma.StringFilter<"StateTransitionLog"> | string
  clinicId?: Prisma.StringFilter<"StateTransitionLog"> | string
  fromState?: Prisma.EnumConversationStateFilter<"StateTransitionLog"> | $Enums.ConversationState
  toState?: Prisma.EnumConversationStateFilter<"StateTransitionLog"> | $Enums.ConversationState
  triggerType?: Prisma.StringFilter<"StateTransitionLog"> | string
  triggerPayload?: Prisma.JsonNullableFilter<"StateTransitionLog">
  triggeredBy?: Prisma.StringNullableFilter<"StateTransitionLog"> | string | null
  createdAt?: Prisma.DateTimeFilter<"StateTransitionLog"> | Date | string
  session?: Prisma.XOR<Prisma.ConversationSessionScalarRelationFilter, Prisma.ConversationSessionWhereInput>
}

export type StateTransitionLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  clinicId?: Prisma.SortOrder
  fromState?: Prisma.SortOrder
  toState?: Prisma.SortOrder
  triggerType?: Prisma.SortOrder
  triggerPayload?: Prisma.SortOrderInput | Prisma.SortOrder
  triggeredBy?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  session?: Prisma.ConversationSessionOrderByWithRelationInput
}

export type StateTransitionLogWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.StateTransitionLogWhereInput | Prisma.StateTransitionLogWhereInput[]
  OR?: Prisma.StateTransitionLogWhereInput[]
  NOT?: Prisma.StateTransitionLogWhereInput | Prisma.StateTransitionLogWhereInput[]
  sessionId?: Prisma.StringFilter<"StateTransitionLog"> | string
  clinicId?: Prisma.StringFilter<"StateTransitionLog"> | string
  fromState?: Prisma.EnumConversationStateFilter<"StateTransitionLog"> | $Enums.ConversationState
  toState?: Prisma.EnumConversationStateFilter<"StateTransitionLog"> | $Enums.ConversationState
  triggerType?: Prisma.StringFilter<"StateTransitionLog"> | string
  triggerPayload?: Prisma.JsonNullableFilter<"StateTransitionLog">
  triggeredBy?: Prisma.StringNullableFilter<"StateTransitionLog"> | string | null
  createdAt?: Prisma.DateTimeFilter<"StateTransitionLog"> | Date | string
  session?: Prisma.XOR<Prisma.ConversationSessionScalarRelationFilter, Prisma.ConversationSessionWhereInput>
}, "id">

export type StateTransitionLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  clinicId?: Prisma.SortOrder
  fromState?: Prisma.SortOrder
  toState?: Prisma.SortOrder
  triggerType?: Prisma.SortOrder
  triggerPayload?: Prisma.SortOrderInput | Prisma.SortOrder
  triggeredBy?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.StateTransitionLogCountOrderByAggregateInput
  _max?: Prisma.StateTransitionLogMaxOrderByAggregateInput
  _min?: Prisma.StateTransitionLogMinOrderByAggregateInput
}

export type StateTransitionLogScalarWhereWithAggregatesInput = {
  AND?: Prisma.StateTransitionLogScalarWhereWithAggregatesInput | Prisma.StateTransitionLogScalarWhereWithAggregatesInput[]
  OR?: Prisma.StateTransitionLogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StateTransitionLogScalarWhereWithAggregatesInput | Prisma.StateTransitionLogScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"StateTransitionLog"> | string
  sessionId?: Prisma.StringWithAggregatesFilter<"StateTransitionLog"> | string
  clinicId?: Prisma.StringWithAggregatesFilter<"StateTransitionLog"> | string
  fromState?: Prisma.EnumConversationStateWithAggregatesFilter<"StateTransitionLog"> | $Enums.ConversationState
  toState?: Prisma.EnumConversationStateWithAggregatesFilter<"StateTransitionLog"> | $Enums.ConversationState
  triggerType?: Prisma.StringWithAggregatesFilter<"StateTransitionLog"> | string
  triggerPayload?: Prisma.JsonNullableWithAggregatesFilter<"StateTransitionLog">
  triggeredBy?: Prisma.StringNullableWithAggregatesFilter<"StateTransitionLog"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"StateTransitionLog"> | Date | string
}

export type StateTransitionLogCreateInput = {
  id?: string
  clinicId: string
  fromState: $Enums.ConversationState
  toState: $Enums.ConversationState
  triggerType: string
  triggerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  triggeredBy?: string | null
  createdAt?: Date | string
  session: Prisma.ConversationSessionCreateNestedOneWithoutStateTransitionsInput
}

export type StateTransitionLogUncheckedCreateInput = {
  id?: string
  sessionId: string
  clinicId: string
  fromState: $Enums.ConversationState
  toState: $Enums.ConversationState
  triggerType: string
  triggerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  triggeredBy?: string | null
  createdAt?: Date | string
}

export type StateTransitionLogUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clinicId?: Prisma.StringFieldUpdateOperationsInput | string
  fromState?: Prisma.EnumConversationStateFieldUpdateOperationsInput | $Enums.ConversationState
  toState?: Prisma.EnumConversationStateFieldUpdateOperationsInput | $Enums.ConversationState
  triggerType?: Prisma.StringFieldUpdateOperationsInput | string
  triggerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  triggeredBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  session?: Prisma.ConversationSessionUpdateOneRequiredWithoutStateTransitionsNestedInput
}

export type StateTransitionLogUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  clinicId?: Prisma.StringFieldUpdateOperationsInput | string
  fromState?: Prisma.EnumConversationStateFieldUpdateOperationsInput | $Enums.ConversationState
  toState?: Prisma.EnumConversationStateFieldUpdateOperationsInput | $Enums.ConversationState
  triggerType?: Prisma.StringFieldUpdateOperationsInput | string
  triggerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  triggeredBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StateTransitionLogCreateManyInput = {
  id?: string
  sessionId: string
  clinicId: string
  fromState: $Enums.ConversationState
  toState: $Enums.ConversationState
  triggerType: string
  triggerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  triggeredBy?: string | null
  createdAt?: Date | string
}

export type StateTransitionLogUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clinicId?: Prisma.StringFieldUpdateOperationsInput | string
  fromState?: Prisma.EnumConversationStateFieldUpdateOperationsInput | $Enums.ConversationState
  toState?: Prisma.EnumConversationStateFieldUpdateOperationsInput | $Enums.ConversationState
  triggerType?: Prisma.StringFieldUpdateOperationsInput | string
  triggerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  triggeredBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StateTransitionLogUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  clinicId?: Prisma.StringFieldUpdateOperationsInput | string
  fromState?: Prisma.EnumConversationStateFieldUpdateOperationsInput | $Enums.ConversationState
  toState?: Prisma.EnumConversationStateFieldUpdateOperationsInput | $Enums.ConversationState
  triggerType?: Prisma.StringFieldUpdateOperationsInput | string
  triggerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  triggeredBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StateTransitionLogListRelationFilter = {
  every?: Prisma.StateTransitionLogWhereInput
  some?: Prisma.StateTransitionLogWhereInput
  none?: Prisma.StateTransitionLogWhereInput
}

export type StateTransitionLogOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StateTransitionLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  clinicId?: Prisma.SortOrder
  fromState?: Prisma.SortOrder
  toState?: Prisma.SortOrder
  triggerType?: Prisma.SortOrder
  triggerPayload?: Prisma.SortOrder
  triggeredBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type StateTransitionLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  clinicId?: Prisma.SortOrder
  fromState?: Prisma.SortOrder
  toState?: Prisma.SortOrder
  triggerType?: Prisma.SortOrder
  triggeredBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type StateTransitionLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  clinicId?: Prisma.SortOrder
  fromState?: Prisma.SortOrder
  toState?: Prisma.SortOrder
  triggerType?: Prisma.SortOrder
  triggeredBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type StateTransitionLogCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.StateTransitionLogCreateWithoutSessionInput, Prisma.StateTransitionLogUncheckedCreateWithoutSessionInput> | Prisma.StateTransitionLogCreateWithoutSessionInput[] | Prisma.StateTransitionLogUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.StateTransitionLogCreateOrConnectWithoutSessionInput | Prisma.StateTransitionLogCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.StateTransitionLogCreateManySessionInputEnvelope
  connect?: Prisma.StateTransitionLogWhereUniqueInput | Prisma.StateTransitionLogWhereUniqueInput[]
}

export type StateTransitionLogUncheckedCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.StateTransitionLogCreateWithoutSessionInput, Prisma.StateTransitionLogUncheckedCreateWithoutSessionInput> | Prisma.StateTransitionLogCreateWithoutSessionInput[] | Prisma.StateTransitionLogUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.StateTransitionLogCreateOrConnectWithoutSessionInput | Prisma.StateTransitionLogCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.StateTransitionLogCreateManySessionInputEnvelope
  connect?: Prisma.StateTransitionLogWhereUniqueInput | Prisma.StateTransitionLogWhereUniqueInput[]
}

export type StateTransitionLogUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.StateTransitionLogCreateWithoutSessionInput, Prisma.StateTransitionLogUncheckedCreateWithoutSessionInput> | Prisma.StateTransitionLogCreateWithoutSessionInput[] | Prisma.StateTransitionLogUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.StateTransitionLogCreateOrConnectWithoutSessionInput | Prisma.StateTransitionLogCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.StateTransitionLogUpsertWithWhereUniqueWithoutSessionInput | Prisma.StateTransitionLogUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.StateTransitionLogCreateManySessionInputEnvelope
  set?: Prisma.StateTransitionLogWhereUniqueInput | Prisma.StateTransitionLogWhereUniqueInput[]
  disconnect?: Prisma.StateTransitionLogWhereUniqueInput | Prisma.StateTransitionLogWhereUniqueInput[]
  delete?: Prisma.StateTransitionLogWhereUniqueInput | Prisma.StateTransitionLogWhereUniqueInput[]
  connect?: Prisma.StateTransitionLogWhereUniqueInput | Prisma.StateTransitionLogWhereUniqueInput[]
  update?: Prisma.StateTransitionLogUpdateWithWhereUniqueWithoutSessionInput | Prisma.StateTransitionLogUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.StateTransitionLogUpdateManyWithWhereWithoutSessionInput | Prisma.StateTransitionLogUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.StateTransitionLogScalarWhereInput | Prisma.StateTransitionLogScalarWhereInput[]
}

export type StateTransitionLogUncheckedUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.StateTransitionLogCreateWithoutSessionInput, Prisma.StateTransitionLogUncheckedCreateWithoutSessionInput> | Prisma.StateTransitionLogCreateWithoutSessionInput[] | Prisma.StateTransitionLogUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.StateTransitionLogCreateOrConnectWithoutSessionInput | Prisma.StateTransitionLogCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.StateTransitionLogUpsertWithWhereUniqueWithoutSessionInput | Prisma.StateTransitionLogUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.StateTransitionLogCreateManySessionInputEnvelope
  set?: Prisma.StateTransitionLogWhereUniqueInput | Prisma.StateTransitionLogWhereUniqueInput[]
  disconnect?: Prisma.StateTransitionLogWhereUniqueInput | Prisma.StateTransitionLogWhereUniqueInput[]
  delete?: Prisma.StateTransitionLogWhereUniqueInput | Prisma.StateTransitionLogWhereUniqueInput[]
  connect?: Prisma.StateTransitionLogWhereUniqueInput | Prisma.StateTransitionLogWhereUniqueInput[]
  update?: Prisma.StateTransitionLogUpdateWithWhereUniqueWithoutSessionInput | Prisma.StateTransitionLogUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.StateTransitionLogUpdateManyWithWhereWithoutSessionInput | Prisma.StateTransitionLogUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.StateTransitionLogScalarWhereInput | Prisma.StateTransitionLogScalarWhereInput[]
}

export type StateTransitionLogCreateWithoutSessionInput = {
  id?: string
  clinicId: string
  fromState: $Enums.ConversationState
  toState: $Enums.ConversationState
  triggerType: string
  triggerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  triggeredBy?: string | null
  createdAt?: Date | string
}

export type StateTransitionLogUncheckedCreateWithoutSessionInput = {
  id?: string
  clinicId: string
  fromState: $Enums.ConversationState
  toState: $Enums.ConversationState
  triggerType: string
  triggerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  triggeredBy?: string | null
  createdAt?: Date | string
}

export type StateTransitionLogCreateOrConnectWithoutSessionInput = {
  where: Prisma.StateTransitionLogWhereUniqueInput
  create: Prisma.XOR<Prisma.StateTransitionLogCreateWithoutSessionInput, Prisma.StateTransitionLogUncheckedCreateWithoutSessionInput>
}

export type StateTransitionLogCreateManySessionInputEnvelope = {
  data: Prisma.StateTransitionLogCreateManySessionInput | Prisma.StateTransitionLogCreateManySessionInput[]
  skipDuplicates?: boolean
}

export type StateTransitionLogUpsertWithWhereUniqueWithoutSessionInput = {
  where: Prisma.StateTransitionLogWhereUniqueInput
  update: Prisma.XOR<Prisma.StateTransitionLogUpdateWithoutSessionInput, Prisma.StateTransitionLogUncheckedUpdateWithoutSessionInput>
  create: Prisma.XOR<Prisma.StateTransitionLogCreateWithoutSessionInput, Prisma.StateTransitionLogUncheckedCreateWithoutSessionInput>
}

export type StateTransitionLogUpdateWithWhereUniqueWithoutSessionInput = {
  where: Prisma.StateTransitionLogWhereUniqueInput
  data: Prisma.XOR<Prisma.StateTransitionLogUpdateWithoutSessionInput, Prisma.StateTransitionLogUncheckedUpdateWithoutSessionInput>
}

export type StateTransitionLogUpdateManyWithWhereWithoutSessionInput = {
  where: Prisma.StateTransitionLogScalarWhereInput
  data: Prisma.XOR<Prisma.StateTransitionLogUpdateManyMutationInput, Prisma.StateTransitionLogUncheckedUpdateManyWithoutSessionInput>
}

export type StateTransitionLogScalarWhereInput = {
  AND?: Prisma.StateTransitionLogScalarWhereInput | Prisma.StateTransitionLogScalarWhereInput[]
  OR?: Prisma.StateTransitionLogScalarWhereInput[]
  NOT?: Prisma.StateTransitionLogScalarWhereInput | Prisma.StateTransitionLogScalarWhereInput[]
  id?: Prisma.StringFilter<"StateTransitionLog"> | string
  sessionId?: Prisma.StringFilter<"StateTransitionLog"> | string
  clinicId?: Prisma.StringFilter<"StateTransitionLog"> | string
  fromState?: Prisma.EnumConversationStateFilter<"StateTransitionLog"> | $Enums.ConversationState
  toState?: Prisma.EnumConversationStateFilter<"StateTransitionLog"> | $Enums.ConversationState
  triggerType?: Prisma.StringFilter<"StateTransitionLog"> | string
  triggerPayload?: Prisma.JsonNullableFilter<"StateTransitionLog">
  triggeredBy?: Prisma.StringNullableFilter<"StateTransitionLog"> | string | null
  createdAt?: Prisma.DateTimeFilter<"StateTransitionLog"> | Date | string
}

export type StateTransitionLogCreateManySessionInput = {
  id?: string
  clinicId: string
  fromState: $Enums.ConversationState
  toState: $Enums.ConversationState
  triggerType: string
  triggerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  triggeredBy?: string | null
  createdAt?: Date | string
}

export type StateTransitionLogUpdateWithoutSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clinicId?: Prisma.StringFieldUpdateOperationsInput | string
  fromState?: Prisma.EnumConversationStateFieldUpdateOperationsInput | $Enums.ConversationState
  toState?: Prisma.EnumConversationStateFieldUpdateOperationsInput | $Enums.ConversationState
  triggerType?: Prisma.StringFieldUpdateOperationsInput | string
  triggerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  triggeredBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StateTransitionLogUncheckedUpdateWithoutSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clinicId?: Prisma.StringFieldUpdateOperationsInput | string
  fromState?: Prisma.EnumConversationStateFieldUpdateOperationsInput | $Enums.ConversationState
  toState?: Prisma.EnumConversationStateFieldUpdateOperationsInput | $Enums.ConversationState
  triggerType?: Prisma.StringFieldUpdateOperationsInput | string
  triggerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  triggeredBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StateTransitionLogUncheckedUpdateManyWithoutSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clinicId?: Prisma.StringFieldUpdateOperationsInput | string
  fromState?: Prisma.EnumConversationStateFieldUpdateOperationsInput | $Enums.ConversationState
  toState?: Prisma.EnumConversationStateFieldUpdateOperationsInput | $Enums.ConversationState
  triggerType?: Prisma.StringFieldUpdateOperationsInput | string
  triggerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  triggeredBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type StateTransitionLogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  clinicId?: boolean
  fromState?: boolean
  toState?: boolean
  triggerType?: boolean
  triggerPayload?: boolean
  triggeredBy?: boolean
  createdAt?: boolean
  session?: boolean | Prisma.ConversationSessionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["stateTransitionLog"]>

export type StateTransitionLogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  clinicId?: boolean
  fromState?: boolean
  toState?: boolean
  triggerType?: boolean
  triggerPayload?: boolean
  triggeredBy?: boolean
  createdAt?: boolean
  session?: boolean | Prisma.ConversationSessionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["stateTransitionLog"]>

export type StateTransitionLogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  clinicId?: boolean
  fromState?: boolean
  toState?: boolean
  triggerType?: boolean
  triggerPayload?: boolean
  triggeredBy?: boolean
  createdAt?: boolean
  session?: boolean | Prisma.ConversationSessionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["stateTransitionLog"]>

export type StateTransitionLogSelectScalar = {
  id?: boolean
  sessionId?: boolean
  clinicId?: boolean
  fromState?: boolean
  toState?: boolean
  triggerType?: boolean
  triggerPayload?: boolean
  triggeredBy?: boolean
  createdAt?: boolean
}

export type StateTransitionLogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "sessionId" | "clinicId" | "fromState" | "toState" | "triggerType" | "triggerPayload" | "triggeredBy" | "createdAt", ExtArgs["result"]["stateTransitionLog"]>
export type StateTransitionLogInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.ConversationSessionDefaultArgs<ExtArgs>
}
export type StateTransitionLogIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.ConversationSessionDefaultArgs<ExtArgs>
}
export type StateTransitionLogIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.ConversationSessionDefaultArgs<ExtArgs>
}

export type $StateTransitionLogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "StateTransitionLog"
  objects: {
    session: Prisma.$ConversationSessionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    sessionId: string
    clinicId: string
    fromState: $Enums.ConversationState
    toState: $Enums.ConversationState
    triggerType: string
    triggerPayload: runtime.JsonValue | null
    triggeredBy: string | null
    createdAt: Date
  }, ExtArgs["result"]["stateTransitionLog"]>
  composites: {}
}

export type StateTransitionLogGetPayload<S extends boolean | null | undefined | StateTransitionLogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StateTransitionLogPayload, S>

export type StateTransitionLogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StateTransitionLogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StateTransitionLogCountAggregateInputType | true
  }

export interface StateTransitionLogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['StateTransitionLog'], meta: { name: 'StateTransitionLog' } }
  /**
   * Find zero or one StateTransitionLog that matches the filter.
   * @param {StateTransitionLogFindUniqueArgs} args - Arguments to find a StateTransitionLog
   * @example
   * // Get one StateTransitionLog
   * const stateTransitionLog = await prisma.stateTransitionLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StateTransitionLogFindUniqueArgs>(args: Prisma.SelectSubset<T, StateTransitionLogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StateTransitionLogClient<runtime.Types.Result.GetResult<Prisma.$StateTransitionLogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one StateTransitionLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StateTransitionLogFindUniqueOrThrowArgs} args - Arguments to find a StateTransitionLog
   * @example
   * // Get one StateTransitionLog
   * const stateTransitionLog = await prisma.stateTransitionLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StateTransitionLogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StateTransitionLogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StateTransitionLogClient<runtime.Types.Result.GetResult<Prisma.$StateTransitionLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StateTransitionLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StateTransitionLogFindFirstArgs} args - Arguments to find a StateTransitionLog
   * @example
   * // Get one StateTransitionLog
   * const stateTransitionLog = await prisma.stateTransitionLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StateTransitionLogFindFirstArgs>(args?: Prisma.SelectSubset<T, StateTransitionLogFindFirstArgs<ExtArgs>>): Prisma.Prisma__StateTransitionLogClient<runtime.Types.Result.GetResult<Prisma.$StateTransitionLogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StateTransitionLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StateTransitionLogFindFirstOrThrowArgs} args - Arguments to find a StateTransitionLog
   * @example
   * // Get one StateTransitionLog
   * const stateTransitionLog = await prisma.stateTransitionLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StateTransitionLogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StateTransitionLogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StateTransitionLogClient<runtime.Types.Result.GetResult<Prisma.$StateTransitionLogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more StateTransitionLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StateTransitionLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all StateTransitionLogs
   * const stateTransitionLogs = await prisma.stateTransitionLog.findMany()
   * 
   * // Get first 10 StateTransitionLogs
   * const stateTransitionLogs = await prisma.stateTransitionLog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const stateTransitionLogWithIdOnly = await prisma.stateTransitionLog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StateTransitionLogFindManyArgs>(args?: Prisma.SelectSubset<T, StateTransitionLogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StateTransitionLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a StateTransitionLog.
   * @param {StateTransitionLogCreateArgs} args - Arguments to create a StateTransitionLog.
   * @example
   * // Create one StateTransitionLog
   * const StateTransitionLog = await prisma.stateTransitionLog.create({
   *   data: {
   *     // ... data to create a StateTransitionLog
   *   }
   * })
   * 
   */
  create<T extends StateTransitionLogCreateArgs>(args: Prisma.SelectSubset<T, StateTransitionLogCreateArgs<ExtArgs>>): Prisma.Prisma__StateTransitionLogClient<runtime.Types.Result.GetResult<Prisma.$StateTransitionLogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many StateTransitionLogs.
   * @param {StateTransitionLogCreateManyArgs} args - Arguments to create many StateTransitionLogs.
   * @example
   * // Create many StateTransitionLogs
   * const stateTransitionLog = await prisma.stateTransitionLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StateTransitionLogCreateManyArgs>(args?: Prisma.SelectSubset<T, StateTransitionLogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many StateTransitionLogs and returns the data saved in the database.
   * @param {StateTransitionLogCreateManyAndReturnArgs} args - Arguments to create many StateTransitionLogs.
   * @example
   * // Create many StateTransitionLogs
   * const stateTransitionLog = await prisma.stateTransitionLog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many StateTransitionLogs and only return the `id`
   * const stateTransitionLogWithIdOnly = await prisma.stateTransitionLog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StateTransitionLogCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StateTransitionLogCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StateTransitionLogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a StateTransitionLog.
   * @param {StateTransitionLogDeleteArgs} args - Arguments to delete one StateTransitionLog.
   * @example
   * // Delete one StateTransitionLog
   * const StateTransitionLog = await prisma.stateTransitionLog.delete({
   *   where: {
   *     // ... filter to delete one StateTransitionLog
   *   }
   * })
   * 
   */
  delete<T extends StateTransitionLogDeleteArgs>(args: Prisma.SelectSubset<T, StateTransitionLogDeleteArgs<ExtArgs>>): Prisma.Prisma__StateTransitionLogClient<runtime.Types.Result.GetResult<Prisma.$StateTransitionLogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one StateTransitionLog.
   * @param {StateTransitionLogUpdateArgs} args - Arguments to update one StateTransitionLog.
   * @example
   * // Update one StateTransitionLog
   * const stateTransitionLog = await prisma.stateTransitionLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StateTransitionLogUpdateArgs>(args: Prisma.SelectSubset<T, StateTransitionLogUpdateArgs<ExtArgs>>): Prisma.Prisma__StateTransitionLogClient<runtime.Types.Result.GetResult<Prisma.$StateTransitionLogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more StateTransitionLogs.
   * @param {StateTransitionLogDeleteManyArgs} args - Arguments to filter StateTransitionLogs to delete.
   * @example
   * // Delete a few StateTransitionLogs
   * const { count } = await prisma.stateTransitionLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StateTransitionLogDeleteManyArgs>(args?: Prisma.SelectSubset<T, StateTransitionLogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StateTransitionLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StateTransitionLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many StateTransitionLogs
   * const stateTransitionLog = await prisma.stateTransitionLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StateTransitionLogUpdateManyArgs>(args: Prisma.SelectSubset<T, StateTransitionLogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StateTransitionLogs and returns the data updated in the database.
   * @param {StateTransitionLogUpdateManyAndReturnArgs} args - Arguments to update many StateTransitionLogs.
   * @example
   * // Update many StateTransitionLogs
   * const stateTransitionLog = await prisma.stateTransitionLog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more StateTransitionLogs and only return the `id`
   * const stateTransitionLogWithIdOnly = await prisma.stateTransitionLog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StateTransitionLogUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StateTransitionLogUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StateTransitionLogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one StateTransitionLog.
   * @param {StateTransitionLogUpsertArgs} args - Arguments to update or create a StateTransitionLog.
   * @example
   * // Update or create a StateTransitionLog
   * const stateTransitionLog = await prisma.stateTransitionLog.upsert({
   *   create: {
   *     // ... data to create a StateTransitionLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the StateTransitionLog we want to update
   *   }
   * })
   */
  upsert<T extends StateTransitionLogUpsertArgs>(args: Prisma.SelectSubset<T, StateTransitionLogUpsertArgs<ExtArgs>>): Prisma.Prisma__StateTransitionLogClient<runtime.Types.Result.GetResult<Prisma.$StateTransitionLogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of StateTransitionLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StateTransitionLogCountArgs} args - Arguments to filter StateTransitionLogs to count.
   * @example
   * // Count the number of StateTransitionLogs
   * const count = await prisma.stateTransitionLog.count({
   *   where: {
   *     // ... the filter for the StateTransitionLogs we want to count
   *   }
   * })
  **/
  count<T extends StateTransitionLogCountArgs>(
    args?: Prisma.Subset<T, StateTransitionLogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StateTransitionLogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a StateTransitionLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StateTransitionLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StateTransitionLogAggregateArgs>(args: Prisma.Subset<T, StateTransitionLogAggregateArgs>): Prisma.PrismaPromise<GetStateTransitionLogAggregateType<T>>

  /**
   * Group by StateTransitionLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StateTransitionLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StateTransitionLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StateTransitionLogGroupByArgs['orderBy'] }
      : { orderBy?: StateTransitionLogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StateTransitionLogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStateTransitionLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the StateTransitionLog model
 */
readonly fields: StateTransitionLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for StateTransitionLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StateTransitionLogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  session<T extends Prisma.ConversationSessionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ConversationSessionDefaultArgs<ExtArgs>>): Prisma.Prisma__ConversationSessionClient<runtime.Types.Result.GetResult<Prisma.$ConversationSessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the StateTransitionLog model
 */
export interface StateTransitionLogFieldRefs {
  readonly id: Prisma.FieldRef<"StateTransitionLog", 'String'>
  readonly sessionId: Prisma.FieldRef<"StateTransitionLog", 'String'>
  readonly clinicId: Prisma.FieldRef<"StateTransitionLog", 'String'>
  readonly fromState: Prisma.FieldRef<"StateTransitionLog", 'ConversationState'>
  readonly toState: Prisma.FieldRef<"StateTransitionLog", 'ConversationState'>
  readonly triggerType: Prisma.FieldRef<"StateTransitionLog", 'String'>
  readonly triggerPayload: Prisma.FieldRef<"StateTransitionLog", 'Json'>
  readonly triggeredBy: Prisma.FieldRef<"StateTransitionLog", 'String'>
  readonly createdAt: Prisma.FieldRef<"StateTransitionLog", 'DateTime'>
}
    

// Custom InputTypes
/**
 * StateTransitionLog findUnique
 */
export type StateTransitionLogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StateTransitionLog
   */
  select?: Prisma.StateTransitionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StateTransitionLog
   */
  omit?: Prisma.StateTransitionLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StateTransitionLogInclude<ExtArgs> | null
  /**
   * Filter, which StateTransitionLog to fetch.
   */
  where: Prisma.StateTransitionLogWhereUniqueInput
}

/**
 * StateTransitionLog findUniqueOrThrow
 */
export type StateTransitionLogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StateTransitionLog
   */
  select?: Prisma.StateTransitionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StateTransitionLog
   */
  omit?: Prisma.StateTransitionLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StateTransitionLogInclude<ExtArgs> | null
  /**
   * Filter, which StateTransitionLog to fetch.
   */
  where: Prisma.StateTransitionLogWhereUniqueInput
}

/**
 * StateTransitionLog findFirst
 */
export type StateTransitionLogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StateTransitionLog
   */
  select?: Prisma.StateTransitionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StateTransitionLog
   */
  omit?: Prisma.StateTransitionLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StateTransitionLogInclude<ExtArgs> | null
  /**
   * Filter, which StateTransitionLog to fetch.
   */
  where?: Prisma.StateTransitionLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StateTransitionLogs to fetch.
   */
  orderBy?: Prisma.StateTransitionLogOrderByWithRelationInput | Prisma.StateTransitionLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StateTransitionLogs.
   */
  cursor?: Prisma.StateTransitionLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StateTransitionLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StateTransitionLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StateTransitionLogs.
   */
  distinct?: Prisma.StateTransitionLogScalarFieldEnum | Prisma.StateTransitionLogScalarFieldEnum[]
}

/**
 * StateTransitionLog findFirstOrThrow
 */
export type StateTransitionLogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StateTransitionLog
   */
  select?: Prisma.StateTransitionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StateTransitionLog
   */
  omit?: Prisma.StateTransitionLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StateTransitionLogInclude<ExtArgs> | null
  /**
   * Filter, which StateTransitionLog to fetch.
   */
  where?: Prisma.StateTransitionLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StateTransitionLogs to fetch.
   */
  orderBy?: Prisma.StateTransitionLogOrderByWithRelationInput | Prisma.StateTransitionLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StateTransitionLogs.
   */
  cursor?: Prisma.StateTransitionLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StateTransitionLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StateTransitionLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StateTransitionLogs.
   */
  distinct?: Prisma.StateTransitionLogScalarFieldEnum | Prisma.StateTransitionLogScalarFieldEnum[]
}

/**
 * StateTransitionLog findMany
 */
export type StateTransitionLogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StateTransitionLog
   */
  select?: Prisma.StateTransitionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StateTransitionLog
   */
  omit?: Prisma.StateTransitionLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StateTransitionLogInclude<ExtArgs> | null
  /**
   * Filter, which StateTransitionLogs to fetch.
   */
  where?: Prisma.StateTransitionLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StateTransitionLogs to fetch.
   */
  orderBy?: Prisma.StateTransitionLogOrderByWithRelationInput | Prisma.StateTransitionLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing StateTransitionLogs.
   */
  cursor?: Prisma.StateTransitionLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StateTransitionLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StateTransitionLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StateTransitionLogs.
   */
  distinct?: Prisma.StateTransitionLogScalarFieldEnum | Prisma.StateTransitionLogScalarFieldEnum[]
}

/**
 * StateTransitionLog create
 */
export type StateTransitionLogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StateTransitionLog
   */
  select?: Prisma.StateTransitionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StateTransitionLog
   */
  omit?: Prisma.StateTransitionLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StateTransitionLogInclude<ExtArgs> | null
  /**
   * The data needed to create a StateTransitionLog.
   */
  data: Prisma.XOR<Prisma.StateTransitionLogCreateInput, Prisma.StateTransitionLogUncheckedCreateInput>
}

/**
 * StateTransitionLog createMany
 */
export type StateTransitionLogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many StateTransitionLogs.
   */
  data: Prisma.StateTransitionLogCreateManyInput | Prisma.StateTransitionLogCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * StateTransitionLog createManyAndReturn
 */
export type StateTransitionLogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StateTransitionLog
   */
  select?: Prisma.StateTransitionLogSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StateTransitionLog
   */
  omit?: Prisma.StateTransitionLogOmit<ExtArgs> | null
  /**
   * The data used to create many StateTransitionLogs.
   */
  data: Prisma.StateTransitionLogCreateManyInput | Prisma.StateTransitionLogCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StateTransitionLogIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * StateTransitionLog update
 */
export type StateTransitionLogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StateTransitionLog
   */
  select?: Prisma.StateTransitionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StateTransitionLog
   */
  omit?: Prisma.StateTransitionLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StateTransitionLogInclude<ExtArgs> | null
  /**
   * The data needed to update a StateTransitionLog.
   */
  data: Prisma.XOR<Prisma.StateTransitionLogUpdateInput, Prisma.StateTransitionLogUncheckedUpdateInput>
  /**
   * Choose, which StateTransitionLog to update.
   */
  where: Prisma.StateTransitionLogWhereUniqueInput
}

/**
 * StateTransitionLog updateMany
 */
export type StateTransitionLogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update StateTransitionLogs.
   */
  data: Prisma.XOR<Prisma.StateTransitionLogUpdateManyMutationInput, Prisma.StateTransitionLogUncheckedUpdateManyInput>
  /**
   * Filter which StateTransitionLogs to update
   */
  where?: Prisma.StateTransitionLogWhereInput
  /**
   * Limit how many StateTransitionLogs to update.
   */
  limit?: number
}

/**
 * StateTransitionLog updateManyAndReturn
 */
export type StateTransitionLogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StateTransitionLog
   */
  select?: Prisma.StateTransitionLogSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StateTransitionLog
   */
  omit?: Prisma.StateTransitionLogOmit<ExtArgs> | null
  /**
   * The data used to update StateTransitionLogs.
   */
  data: Prisma.XOR<Prisma.StateTransitionLogUpdateManyMutationInput, Prisma.StateTransitionLogUncheckedUpdateManyInput>
  /**
   * Filter which StateTransitionLogs to update
   */
  where?: Prisma.StateTransitionLogWhereInput
  /**
   * Limit how many StateTransitionLogs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StateTransitionLogIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * StateTransitionLog upsert
 */
export type StateTransitionLogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StateTransitionLog
   */
  select?: Prisma.StateTransitionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StateTransitionLog
   */
  omit?: Prisma.StateTransitionLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StateTransitionLogInclude<ExtArgs> | null
  /**
   * The filter to search for the StateTransitionLog to update in case it exists.
   */
  where: Prisma.StateTransitionLogWhereUniqueInput
  /**
   * In case the StateTransitionLog found by the `where` argument doesn't exist, create a new StateTransitionLog with this data.
   */
  create: Prisma.XOR<Prisma.StateTransitionLogCreateInput, Prisma.StateTransitionLogUncheckedCreateInput>
  /**
   * In case the StateTransitionLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StateTransitionLogUpdateInput, Prisma.StateTransitionLogUncheckedUpdateInput>
}

/**
 * StateTransitionLog delete
 */
export type StateTransitionLogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StateTransitionLog
   */
  select?: Prisma.StateTransitionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StateTransitionLog
   */
  omit?: Prisma.StateTransitionLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StateTransitionLogInclude<ExtArgs> | null
  /**
   * Filter which StateTransitionLog to delete.
   */
  where: Prisma.StateTransitionLogWhereUniqueInput
}

/**
 * StateTransitionLog deleteMany
 */
export type StateTransitionLogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StateTransitionLogs to delete
   */
  where?: Prisma.StateTransitionLogWhereInput
  /**
   * Limit how many StateTransitionLogs to delete.
   */
  limit?: number
}

/**
 * StateTransitionLog without action
 */
export type StateTransitionLogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StateTransitionLog
   */
  select?: Prisma.StateTransitionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StateTransitionLog
   */
  omit?: Prisma.StateTransitionLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StateTransitionLogInclude<ExtArgs> | null
}
