
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Clinic
 * 
 */
export type Clinic = Prisma.ClinicModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Membership
 * 
 */
export type Membership = Prisma.MembershipModel
/**
 * Model Doctor
 * 
 */
export type Doctor = Prisma.DoctorModel
/**
 * Model Service
 * 
 */
export type Service = Prisma.ServiceModel
/**
 * Model AvailableSlot
 * 
 */
export type AvailableSlot = Prisma.AvailableSlotModel
/**
 * Model ConversationSession
 * 
 */
export type ConversationSession = Prisma.ConversationSessionModel
/**
 * Model ConversationMessage
 * 
 */
export type ConversationMessage = Prisma.ConversationMessageModel
/**
 * Model StateTransitionLog
 * 
 */
export type StateTransitionLog = Prisma.StateTransitionLogModel
/**
 * Model Patient
 * 
 */
export type Patient = Prisma.PatientModel
/**
 * Model Appointment
 * 
 */
export type Appointment = Prisma.AppointmentModel
/**
 * Model Conversation
 * 
 */
export type Conversation = Prisma.ConversationModel
/**
 * Model Message
 * 
 */
export type Message = Prisma.MessageModel
/**
 * Model Reminder
 * 
 */
export type Reminder = Prisma.ReminderModel
/**
 * Model NotificationJob
 * 
 */
export type NotificationJob = Prisma.NotificationJobModel
/**
 * Model Campaign
 * 
 */
export type Campaign = Prisma.CampaignModel
/**
 * Model ClinicSettings
 * 
 */
export type ClinicSettings = Prisma.ClinicSettingsModel
/**
 * Model BusinessHours
 * 
 */
export type BusinessHours = Prisma.BusinessHoursModel
/**
 * Model Lead
 * 
 */
export type Lead = Prisma.LeadModel
/**
 * Model EscalationLog
 * 
 */
export type EscalationLog = Prisma.EscalationLogModel
