
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  owner: 'owner',
  admin: 'admin',
  doctor: 'doctor',
  staff: 'staff',
  receptionist: 'receptionist'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const SubscriptionPlan = {
  free: 'free',
  basic: 'basic',
  premium: 'premium',
  enterprise: 'enterprise'
} as const

export type SubscriptionPlan = (typeof SubscriptionPlan)[keyof typeof SubscriptionPlan]


export const AppointmentStatus = {
  scheduled: 'scheduled',
  confirmation_pending: 'confirmation_pending',
  confirmed: 'confirmed',
  in_progress: 'in_progress',
  completed: 'completed',
  cancelled: 'cancelled',
  no_show: 'no_show',
  rescheduled: 'rescheduled'
} as const

export type AppointmentStatus = (typeof AppointmentStatus)[keyof typeof AppointmentStatus]


export const Channel = {
  web: 'web',
  whatsapp: 'whatsapp',
  sms: 'sms',
  email: 'email'
} as const

export type Channel = (typeof Channel)[keyof typeof Channel]


export const SenderType = {
  patient: 'patient',
  clinic: 'clinic',
  system: 'system'
} as const

export type SenderType = (typeof SenderType)[keyof typeof SenderType]


export const MessageType = {
  text: 'text',
  image: 'image',
  file: 'file',
  template: 'template'
} as const

export type MessageType = (typeof MessageType)[keyof typeof MessageType]


export const MessageStatus = {
  sent: 'sent',
  delivered: 'delivered',
  read: 'read',
  failed: 'failed'
} as const

export type MessageStatus = (typeof MessageStatus)[keyof typeof MessageStatus]


export const ReminderType = {
  email: 'email',
  sms: 'sms',
  whatsapp: 'whatsapp',
  push: 'push'
} as const

export type ReminderType = (typeof ReminderType)[keyof typeof ReminderType]


export const ReminderStatus = {
  pending: 'pending',
  sent: 'sent',
  failed: 'failed',
  cancelled: 'cancelled'
} as const

export type ReminderStatus = (typeof ReminderStatus)[keyof typeof ReminderStatus]


export const NotificationJobStatus = {
  pending: 'pending',
  queued: 'queued',
  sent: 'sent',
  failed: 'failed'
} as const

export type NotificationJobStatus = (typeof NotificationJobStatus)[keyof typeof NotificationJobStatus]


export const CampaignType = {
  announcement: 'announcement',
  reminder: 'reminder',
  promotion: 'promotion',
  follow_up: 'follow_up'
} as const

export type CampaignType = (typeof CampaignType)[keyof typeof CampaignType]


export const CampaignStatus = {
  draft: 'draft',
  scheduled: 'scheduled',
  running: 'running',
  completed: 'completed',
  cancelled: 'cancelled'
} as const

export type CampaignStatus = (typeof CampaignStatus)[keyof typeof CampaignStatus]


export const Severity = {
  info: 'info',
  warning: 'warning',
  error: 'error',
  critical: 'critical'
} as const

export type Severity = (typeof Severity)[keyof typeof Severity]


export const EntityType = {
  appointment: 'appointment',
  patient: 'patient',
  conversation: 'conversation',
  system: 'system'
} as const

export type EntityType = (typeof EntityType)[keyof typeof EntityType]
