-- AlterEnum
ALTER TYPE "ConversationState" ADD VALUE 'RESCHEDULE_PENDING';
ALTER TYPE "ConversationState" ADD VALUE 'RESCHEDULE_DATE';
ALTER TYPE "ConversationState" ADD VALUE 'RESCHEDULE_TIME';
ALTER TYPE "ConversationState" ADD VALUE 'RESCHEDULE_CONFIRMED';
