import { ConversationState } from '@/lib/prisma-client/enums'

export class InvalidTransitionError extends Error {
  constructor(public currentState: ConversationState, public trigger: string) {
    super(`Invalid transition: ${currentState} + ${trigger}`)
    this.name = 'InvalidTransitionError'
  }
}

export const TERMINAL_STATES: ConversationState[] = [
  'BOOKING_CONFIRMED',
  'CANCELLATION_CONFIRMED',
  'RESCHEDULE_CONFIRMED',
  'BOOKING_FAILED',
  'EXPIRED',
  'CORRUPTED',
]

type TransitionMap = Partial<Record<ConversationState, Partial<Record<string, ConversationState>>>>

export const FSM_TRANSITIONS: TransitionMap = {
  IDLE: {
    MESSAGE_RECEIVED:            'LANGUAGE_DETECTION',
    INTENT_BOOKING:              'SLOT_COLLECTION_SERVICE',
    INTENT_CANCEL:               'CANCELLATION_PENDING',
    INTENT_RESCHEDULE:           'RESCHEDULE_PENDING',
    USER_REQUESTED_ESCALATION:   'HUMAN_ESCALATION_PENDING',
  },
  LANGUAGE_DETECTION: {
    LANGUAGE_DETECTED:           'INTENT_DISAMBIGUATION',
    LANGUAGE_UNDETECTABLE:       'INTENT_DISAMBIGUATION',
    INTENT_BOOKING:              'SLOT_COLLECTION_SERVICE',
    INTENT_CANCEL:               'CANCELLATION_PENDING',
    INTENT_RESCHEDULE:           'RESCHEDULE_PENDING',
    USER_REQUESTED_ESCALATION:   'HUMAN_ESCALATION_PENDING',
  },
  INTENT_DISAMBIGUATION: {
    INTENT_BOOKING:              'SLOT_COLLECTION_SERVICE',
    INTENT_CANCEL:               'CANCELLATION_PENDING',
    INTENT_RESCHEDULE:           'RESCHEDULE_PENDING',
    INTENT_ESCALATE:             'HUMAN_ESCALATION_PENDING',
    INTENT_SELECTED:             'SLOT_COLLECTION_SERVICE',
    MAX_RETRIES:                 'HUMAN_ESCALATION_PENDING',
    INVALID_INPUT:               'INTENT_DISAMBIGUATION',
    USER_REQUESTED_ESCALATION:   'HUMAN_ESCALATION_PENDING',
  },
  SLOT_COLLECTION_SERVICE: {
    SLOT_VALID:                  'SLOT_COLLECTION_DATE',
    INTENT_CANCEL:               'CANCELLATION_PENDING',
    INTENT_RESCHEDULE:           'RESCHEDULE_PENDING',
    MAX_RETRIES:                 'HUMAN_ESCALATION_PENDING',
    INVALID_INPUT:               'SLOT_COLLECTION_SERVICE',
    USER_REQUESTED_ESCALATION:   'HUMAN_ESCALATION_PENDING',
  },
  SLOT_COLLECTION_DATE: {
    SLOT_VALID:                  'SLOT_COLLECTION_TIME',
    INTENT_CANCEL:               'CANCELLATION_PENDING',
    INTENT_RESCHEDULE:           'RESCHEDULE_PENDING',
    NO_AVAILABILITY:             'SLOT_COLLECTION_DATE',
    MAX_RETRIES:                 'HUMAN_ESCALATION_PENDING',
    INVALID_INPUT:               'SLOT_COLLECTION_DATE',
    USER_REQUESTED_ESCALATION:   'HUMAN_ESCALATION_PENDING',
  },
  SLOT_COLLECTION_TIME: {
    SLOT_VALID:                  'SLOT_COLLECTION_PATIENT_NAME',
    DATE_OVERRIDE:               'SLOT_COLLECTION_TIME',
    INTENT_CANCEL:               'CANCELLATION_PENDING',
    INTENT_RESCHEDULE:           'RESCHEDULE_PENDING',
    MAX_RETRIES:                 'HUMAN_ESCALATION_PENDING',
    INVALID_INPUT:               'SLOT_COLLECTION_TIME',
    USER_REQUESTED_ESCALATION:   'HUMAN_ESCALATION_PENDING',
  },
  SLOT_COLLECTION_PATIENT_NAME: {
    SLOT_VALID:                  'SLOT_COLLECTION_PATIENT_DOB',
    DATE_OVERRIDE:               'SLOT_COLLECTION_TIME',
    INTENT_CANCEL:               'CANCELLATION_PENDING',
    INTENT_RESCHEDULE:           'RESCHEDULE_PENDING',
    MAX_RETRIES:                 'HUMAN_ESCALATION_PENDING',
    INVALID_INPUT:               'SLOT_COLLECTION_PATIENT_NAME',
    USER_REQUESTED_ESCALATION:   'HUMAN_ESCALATION_PENDING',
  },
  SLOT_COLLECTION_PATIENT_DOB: {
    SLOT_VALID:                  'SLOT_COLLECTION_PHONE_CONFIRM',
    DATE_OVERRIDE:               'SLOT_COLLECTION_TIME',
    INTENT_CANCEL:               'CANCELLATION_PENDING',
    INTENT_RESCHEDULE:           'RESCHEDULE_PENDING',
    MAX_RETRIES:                 'HUMAN_ESCALATION_PENDING',
    INVALID_INPUT:               'SLOT_COLLECTION_PATIENT_DOB',
    USER_REQUESTED_ESCALATION:   'HUMAN_ESCALATION_PENDING',
  },
  SLOT_COLLECTION_PHONE_CONFIRM: {
    CONFIRMED:                   'CONFIRMATION_PENDING',
    ALT_PHONE:                   'CONFIRMATION_PENDING',
    DATE_OVERRIDE:               'SLOT_COLLECTION_TIME',
    INTENT_CANCEL:               'CANCELLATION_PENDING',
    INTENT_RESCHEDULE:           'RESCHEDULE_PENDING',
    MAX_RETRIES:                 'HUMAN_ESCALATION_PENDING',
    INVALID_INPUT:               'SLOT_COLLECTION_PHONE_CONFIRM',
    USER_REQUESTED_ESCALATION:   'HUMAN_ESCALATION_PENDING',
  },
  CONFIRMATION_PENDING: {
    AFFIRM:                      'BOOKING_PROCESSING',
    DENY:                        'SLOT_COLLECTION_SERVICE',
    DATE_OVERRIDE:               'SLOT_COLLECTION_TIME',
    INTENT_CANCEL:               'CANCELLATION_PENDING',
    INTENT_RESCHEDULE:           'RESCHEDULE_PENDING',
    TIMEOUT:                     'EXPIRED',
    USER_REQUESTED_ESCALATION:   'HUMAN_ESCALATION_PENDING',
  },
  BOOKING_PROCESSING: {
    BOOKING_SUCCESS:             'BOOKING_CONFIRMED',
    SLOT_CONFLICT:               'SLOT_COLLECTION_TIME',
    BOOKING_ERROR:               'BOOKING_FAILED',
    HOLD_EXPIRED:                'BOOKING_FAILED',
    USER_REQUESTED_ESCALATION:   'HUMAN_ESCALATION_PENDING',
  },
  BOOKING_CONFIRMED: {
    SESSION_RESET_AFTER_BOOKING: 'IDLE',
  },
  BOOKING_FAILED: {
    MESSAGE_RECEIVED:            'IDLE',
    USER_REQUESTED_ESCALATION:   'HUMAN_ESCALATION_PENDING',
  },
  CANCELLATION_PENDING: {
    AFFIRM:                      'CANCELLATION_CONFIRMED',
    DENY:                        'IDLE',
    TIMEOUT:                     'EXPIRED',
    USER_REQUESTED_ESCALATION:   'HUMAN_ESCALATION_PENDING',
  },
  CANCELLATION_CONFIRMED: {
    SESSION_RESET_AFTER_CANCELLATION: 'IDLE',
    USER_REQUESTED_ESCALATION:        'HUMAN_ESCALATION_PENDING',
  },
  RESCHEDULE_PENDING: {
    SLOT_VALID:                  'RESCHEDULE_TIME',
    NO_AVAILABILITY:             'RESCHEDULE_DATE',
    MAX_RETRIES:                 'HUMAN_ESCALATION_PENDING',
    INVALID_INPUT:               'RESCHEDULE_PENDING',
    INTENT_CANCEL:               'IDLE',
    USER_REQUESTED_ESCALATION:   'HUMAN_ESCALATION_PENDING',
  },
  RESCHEDULE_DATE: {
    SLOT_VALID:                  'RESCHEDULE_TIME',
    NO_AVAILABILITY:             'RESCHEDULE_DATE',
    MAX_RETRIES:                 'HUMAN_ESCALATION_PENDING',
    INVALID_INPUT:               'RESCHEDULE_DATE',
    INTENT_CANCEL:               'IDLE',
    USER_REQUESTED_ESCALATION:   'HUMAN_ESCALATION_PENDING',
  },
  RESCHEDULE_TIME: {
    RESCHEDULE_SUCCESS:          'RESCHEDULE_CONFIRMED',
    SLOT_CONFLICT:               'RESCHEDULE_TIME',
    MAX_RETRIES:                 'HUMAN_ESCALATION_PENDING',
    INVALID_INPUT:               'RESCHEDULE_TIME',
    INTENT_CANCEL:               'IDLE',
    USER_REQUESTED_ESCALATION:   'HUMAN_ESCALATION_PENDING',
  },
  RESCHEDULE_CONFIRMED: {
    MESSAGE_RECEIVED:            'IDLE',
  },
  HUMAN_ESCALATION_PENDING: {
    STAFF_CLAIMED: 'HUMAN_ESCALATION_ACTIVE',
    TIMEOUT:       'EXPIRED',
  },
  HUMAN_ESCALATION_ACTIVE: {
    STAFF_RELEASED:  'IDLE',
    STAFF_RESOLVED:  'BOOKING_CONFIRMED',
  },
  EXPIRED: {
    MESSAGE_RECEIVED:          'IDLE',
    USER_REQUESTED_ESCALATION: 'HUMAN_ESCALATION_PENDING',
  },
  CORRUPTED: {
    MESSAGE_RECEIVED:          'IDLE',
    USER_REQUESTED_ESCALATION: 'HUMAN_ESCALATION_PENDING',
  },
}

export function transition(
  currentState: ConversationState,
  trigger: string
): ConversationState {
  const stateMap = FSM_TRANSITIONS[currentState]

  if (!stateMap) {
    throw new InvalidTransitionError(currentState, trigger)
  }

  const nextState = stateMap[trigger]

  if (!nextState) {
    throw new InvalidTransitionError(currentState, trigger)
  }

  return nextState
}

export function isTerminal(state: ConversationState): boolean {
  return TERMINAL_STATES.includes(state)
}
